import type {
  Incident,
  IncidentEvent,
  IncidentLink,
} from "./types";

export const incidents: Incident[] = [
  {
    id: "INC-001",
    severity: "critical",
    status: "investigating",
    category: "treasury",
    title: "Treasury Settlement Batch Delayed",
    description: "Wire transfer batch BATCH-441 stuck in PROCESSING for 45+ minutes. Manual intervention may be required to unblock settlement.",
    owner: "Alice Chen",
    team: "Treasury Operations",
    watchers: ["Bob Martinez", "Carol Lee"],
    escalationContact: "David Kumar (Treasury Lead)",
    linkedTransactionId: "TXN-8821",
    linkedWorkflowId: "WF-441",
    created: new Date(Date.now() - 45 * 60000).toISOString(),
    updated: new Date(Date.now() - 5 * 60000).toISOString(),
    slaResponseDeadline: new Date(Date.now() + 15 * 60000).toISOString(),
    slaResolutionDeadline: new Date(Date.now() + 4 * 3600000).toISOString(),
    escalationLevel: 2,
    businessImpact: "High — $1.2M in outbound wires delayed. Counterparty settlement at risk.",
    rootCause: "Under investigation — suspected upstream bank API timeout",
    priority: "P1",
  },
  {
    id: "INC-002",
    severity: "critical",
    status: "open",
    category: "approvals",
    title: "CFO Approval Escalation — Threshold Exceeded",
    description: "Transaction TXN-8834 ($250,000) exceeds single-approval limit. Dual approval required but only one obtained. Escalation triggered.",
    owner: "Bob Martinez",
    team: "Compliance",
    watchers: ["Alice Chen", "Diana Park"],
    escalationContact: "Eve Richards (Chief Compliance Officer)",
    linkedTransactionId: "TXN-8834",
    linkedApprovalId: "APPR-8834",
    linkedPolicyId: "POL-001",
    created: new Date(Date.now() - 4 * 3600000).toISOString(),
    updated: new Date(Date.now() - 10 * 60000).toISOString(),
    slaResponseDeadline: new Date(Date.now() - 1 * 3600000).toISOString(),
    slaResolutionDeadline: new Date(Date.now() + 2 * 3600000).toISOString(),
    escalationLevel: 1,
    businessImpact: "Medium — $250,000 payment pending. Counterparty expecting funds EOD.",
    priority: "P1",
  },
  {
    id: "INC-003",
    severity: "high",
    status: "investigating",
    category: "ledger",
    title: "Ledger Posting Failure — Currency Mismatch",
    description: "Journal entry JE-773 failed to post. Debit leg in USD, credit leg in EUR. Currency mismatch detected by Ledger Engine.",
    owner: "Carol Lee",
    team: "Engineering",
    watchers: ["Alice Chen"],
    linkedTransactionId: "TXN-8825",
    linkedLedgerEntryId: "JE-773",
    created: new Date(Date.now() - 2 * 3600000).toISOString(),
    updated: new Date(Date.now() - 30 * 60000).toISOString(),
    slaResponseDeadline: new Date(Date.now() + 2 * 3600000).toISOString(),
    slaResolutionDeadline: new Date(Date.now() + 24 * 3600000).toISOString(),
    escalationLevel: 0,
    businessImpact: "Low — Single journal entry affected. No customer impact.",
    priority: "P2",
  },
  {
    id: "INC-004",
    severity: "high",
    status: "open",
    category: "reconciliation",
    title: "Reconciliation Failure — Q1 Batch",
    description: "Bank statement reconciliation for Q1 batch REC-2024-Q1 failed with 14 unmatched transactions. Manual review required.",
    owner: "Diana Park",
    team: "Finance Operations",
    watchers: ["Bob Martinez", "Carol Lee"],
    escalationContact: "Frank Wu (Finance Director)",
    created: new Date(Date.now() - 6 * 3600000).toISOString(),
    updated: new Date(Date.now() - 45 * 60000).toISOString(),
    slaResponseDeadline: new Date(Date.now() - 2 * 3600000).toISOString(),
    slaResolutionDeadline: new Date(Date.now() + 18 * 3600000).toISOString(),
    escalationLevel: 1,
    businessImpact: "Medium — Q1 financial close at risk. 14 unmatched items requiring investigation.",
    priority: "P2",
  },
  {
    id: "INC-005",
    severity: "medium",
    status: "awaiting_info",
    category: "notifications",
    title: "Webhook Delivery Retry Loop",
    description: "Webhook endpoint https://internal.corp/webhooks/payments has been retrying for 22 minutes. 3 deliveries failed with 502 responses.",
    owner: "Eve Richards",
    team: "Integrations",
    watchers: ["Alice Chen"],
    linkedWorkflowId: "WF-442",
    created: new Date(Date.now() - 22 * 60000).toISOString(),
    updated: new Date(Date.now() - 2 * 60000).toISOString(),
    slaResponseDeadline: new Date(Date.now() + 38 * 60000).toISOString(),
    slaResolutionDeadline: new Date(Date.now() + 4 * 3600000).toISOString(),
    escalationLevel: 0,
    businessImpact: "Low — Notification delivery degraded. No financial impact.",
    priority: "P3",
  },
  {
    id: "INC-006",
    severity: "medium",
    status: "investigating",
    category: "api",
    title: "Bank Connection Latency Spike",
    description: "Silvergate Bank connection reporting degraded latency (2.4s response time). 4 retries in last hour. API timeout threshold at 3s.",
    owner: "Alice Chen",
    team: "Treasury Operations",
    watchers: ["Bob Martinez"],
    created: new Date(Date.now() - 75 * 60000).toISOString(),
    updated: new Date(Date.now() - 3 * 60000).toISOString(),
    slaResponseDeadline: new Date(Date.now() + 45 * 60000).toISOString(),
    slaResolutionDeadline: new Date(Date.now() + 6 * 3600000).toISOString(),
    escalationLevel: 0,
    businessImpact: "Low — Latency degrading but not yet impacting transaction processing.",
    priority: "P3",
  },
  {
    id: "INC-007",
    severity: "low",
    status: "resolved",
    category: "policy",
    title: "Policy Rule Evaluation Timeout",
    description: "Policy rule 'High-Value Wire' evaluation exceeded 5s timeout during peak load. Rule re-evaluated successfully after retry.",
    owner: "Carol Lee",
    team: "Engineering",
    watchers: [],
    linkedPolicyId: "POL-003",
    linkedRiskAssessmentId: "RA-001",
    created: new Date(Date.now() - 48 * 3600000).toISOString(),
    updated: new Date(Date.now() - 24 * 3600000).toISOString(),
    slaResponseDeadline: new Date(Date.now() - 44 * 3600000).toISOString(),
    slaResolutionDeadline: new Date(Date.now() - 30 * 3600000).toISOString(),
    slaRespondedAt: new Date(Date.now() - 44 * 3600000).toISOString(),
    slaResolvedAt: new Date(Date.now() - 30 * 3600000).toISOString(),
    escalationLevel: 0,
    businessImpact: "None — Retry succeeded. No impact on transaction processing.",
    rootCause: "Transient CPU spike during batch reconcile job",
    resolutionSummary: "Increased policy engine timeout from 5s to 10s and added circuit breaker.",
    lessonsLearned: "Policy engine timeout was too tight for peak periods. Added monitoring threshold at 4s.",
    rootCauseClassification: "Performance / Capacity",
    priority: "P4",
  },
  {
    id: "INC-008",
    severity: "low",
    status: "closed",
    category: "risk",
    title: "False Positive Risk Alert — Transaction Review",
    description: "Risk engine flagged TXN-8840 for unusual pattern. Manual review determined transaction is legitimate. False positive.",
    owner: "Diana Park",
    team: "Risk Management",
    watchers: [],
    linkedTransactionId: "TXN-8840",
    linkedRiskAssessmentId: "RA-002",
    created: new Date(Date.now() - 72 * 3600000).toISOString(),
    updated: new Date(Date.now() - 48 * 3600000).toISOString(),
    slaResponseDeadline: new Date(Date.now() - 68 * 3600000).toISOString(),
    slaResolutionDeadline: new Date(Date.now() - 54 * 3600000).toISOString(),
    slaRespondedAt: new Date(Date.now() - 68 * 3600000).toISOString(),
    slaResolvedAt: new Date(Date.now() - 54 * 3600000).toISOString(),
    escalationLevel: 0,
    businessImpact: "None — No action required. False positive.",
    rootCause: "Risk engine false positive — transaction pattern matched legitimate seasonal activity",
    resolutionSummary: "Reviewed and cleared. Added transaction pattern to exception list.",
    lessonsLearned: "Seasonal patterns should be pre-registered to reduce false positives.",
    rootCauseClassification: "Configuration / Rules",
    priority: "P4",
  },
];

export const incidentEvents: IncidentEvent[] = [
  {
    id: "evt-001",
    incidentId: "INC-001",
    type: "created",
    actor: "System",
    timestamp: new Date(Date.now() - 45 * 60000).toISOString(),
    description: "Incident auto-created — Treasury settlement batch BATCH-441 exceeded processing threshold",
  },
  {
    id: "evt-002",
    incidentId: "INC-001",
    type: "assigned",
    actor: "System",
    timestamp: new Date(Date.now() - 42 * 60000).toISOString(),
    description: "Assigned to Alice Chen (Treasury Operations) based on rotation schedule",
  },
  {
    id: "evt-003",
    incidentId: "INC-001",
    type: "comment",
    actor: "Alice Chen",
    timestamp: new Date(Date.now() - 30 * 60000).toISOString(),
    description: "Investigating bank API status. Contacted Silvergate support. Awaiting response.",
  },
  {
    id: "evt-004",
    incidentId: "INC-001",
    type: "escalated",
    actor: "Alice Chen",
    timestamp: new Date(Date.now() - 15 * 60000).toISOString(),
    description: "Escalated to Level 2 — Treasury Lead David Kumar notified. SLA warning triggered.",
  },
  {
    id: "evt-005",
    incidentId: "INC-001",
    type: "sla_warning",
    actor: "System",
    timestamp: new Date(Date.now() - 10 * 60000).toISOString(),
    description: "SLA Response Deadline approaching — 15 minutes remaining",
  },
  {
    id: "evt-006",
    incidentId: "INC-001",
    type: "comment",
    actor: "David Kumar",
    timestamp: new Date(Date.now() - 5 * 60000).toISOString(),
    description: "Treasury Lead engaged. Initiating manual fallback procedure for batch settlement.",
  },
  {
    id: "evt-007",
    incidentId: "INC-002",
    type: "created",
    actor: "System",
    timestamp: new Date(Date.now() - 4 * 3600000).toISOString(),
    description: "Incident auto-created — Approval threshold exceeded for TXN-8834",
  },
  {
    id: "evt-008",
    incidentId: "INC-002",
    type: "assigned",
    actor: "System",
    timestamp: new Date(Date.now() - 4 * 3600000).toISOString(),
    description: "Assigned to Bob Martinez (Compliance) based on escalation rules",
  },
  {
    id: "evt-009",
    incidentId: "INC-002",
    type: "escalated",
    actor: "System",
    timestamp: new Date(Date.now() - 2 * 3600000).toISOString(),
    description: "Auto-escalated — No response within 2-hour SLA window",
  },
  {
    id: "evt-010",
    incidentId: "INC-002",
    type: "sla_warning",
    actor: "System",
    timestamp: new Date(Date.now() - 70 * 60000).toISOString(),
    description: "SLA Response Deadline breached. Escalation to Level 2 triggered.",
  },
  {
    id: "evt-011",
    incidentId: "INC-003",
    type: "created",
    actor: "System",
    timestamp: new Date(Date.now() - 2 * 3600000).toISOString(),
    description: "Incident auto-created — Ledger posting failure JE-773",
  },
  {
    id: "evt-012",
    incidentId: "INC-003",
    type: "assigned",
    actor: "System",
    timestamp: new Date(Date.now() - 2 * 3600000).toISOString(),
    description: "Assigned to Carol Lee (Engineering) based on expertise match",
  },
  {
    id: "evt-013",
    incidentId: "INC-003",
    type: "comment",
    actor: "Carol Lee",
    timestamp: new Date(Date.now() - 60 * 60000).toISOString(),
    description: "Identified currency mismatch: debit in USD, credit in EUR. Investigating conversion logic.",
  },
  {
    id: "evt-014",
    incidentId: "INC-004",
    type: "created",
    actor: "System",
    timestamp: new Date(Date.now() - 6 * 3600000).toISOString(),
    description: "Incident auto-created — Reconciliation batch REC-2024-Q1 failed",
  },
  {
    id: "evt-015",
    incidentId: "INC-004",
    type: "assigned",
    actor: "System",
    timestamp: new Date(Date.now() - 6 * 3600000).toISOString(),
    description: "Assigned to Diana Park (Finance Operations)",
  },
  {
    id: "evt-016",
    incidentId: "INC-004",
    type: "sla_warning",
    actor: "System",
    timestamp: new Date(Date.now() - 3 * 3600000).toISOString(),
    description: "SLA Response Deadline breached. Escalating to Finance Director.",
  },
  {
    id: "evt-017",
    incidentId: "INC-005",
    type: "created",
    actor: "System",
    timestamp: new Date(Date.now() - 22 * 60000).toISOString(),
    description: "Incident created — Webhook delivery retry loop detected",
  },
  {
    id: "evt-018",
    incidentId: "INC-005",
    type: "assigned",
    actor: "System",
    timestamp: new Date(Date.now() - 20 * 60000).toISOString(),
    description: "Assigned to Eve Richards (Integrations)",
  },
  {
    id: "evt-019",
    incidentId: "INC-006",
    type: "created",
    actor: "System",
    timestamp: new Date(Date.now() - 75 * 60000).toISOString(),
    description: "Incident created — Bank connection latency spike detected",
  },
  {
    id: "evt-020",
    incidentId: "INC-006",
    type: "assigned",
    actor: "System",
    timestamp: new Date(Date.now() - 70 * 60000).toISOString(),
    description: "Assigned to Alice Chen (Treasury Operations)",
  },
  {
    id: "evt-021",
    incidentId: "INC-007",
    type: "created",
    actor: "System",
    timestamp: new Date(Date.now() - 48 * 3600000).toISOString(),
    description: "Incident created — Policy rule evaluation timeout",
  },
  {
    id: "evt-022",
    incidentId: "INC-007",
    type: "assigned",
    actor: "System",
    timestamp: new Date(Date.now() - 48 * 3600000).toISOString(),
    description: "Assigned to Carol Lee (Engineering)",
  },
  {
    id: "evt-023",
    incidentId: "INC-007",
    type: "resolved",
    actor: "Carol Lee",
    timestamp: new Date(Date.now() - 30 * 3600000).toISOString(),
    description: "Resolved — Increased policy engine timeout and added circuit breaker",
  },
  {
    id: "evt-024",
    incidentId: "INC-007",
    type: "closed",
    actor: "Carol Lee",
    timestamp: new Date(Date.now() - 24 * 3600000).toISOString(),
    description: "Incident closed. Lessons learned documented.",
  },
  {
    id: "evt-025",
    incidentId: "INC-008",
    type: "created",
    actor: "System",
    timestamp: new Date(Date.now() - 72 * 3600000).toISOString(),
    description: "Incident created — Risk alert flagged for manual review",
  },
  {
    id: "evt-026",
    incidentId: "INC-008",
    type: "assigned",
    actor: "System",
    timestamp: new Date(Date.now() - 72 * 3600000).toISOString(),
    description: "Assigned to Diana Park (Risk Management)",
  },
  {
    id: "evt-027",
    incidentId: "INC-008",
    type: "resolved",
    actor: "Diana Park",
    timestamp: new Date(Date.now() - 54 * 3600000).toISOString(),
    description: "Resolved — Reviewed and cleared as false positive",
  },
  {
    id: "evt-028",
    incidentId: "INC-008",
    type: "closed",
    actor: "Diana Park",
    timestamp: new Date(Date.now() - 48 * 3600000).toISOString(),
    description: "Incident closed. Pattern added to exception list.",
  },
];

export function getIncidentLinks(incident: Incident): IncidentLink[] {
  const links: IncidentLink[] = [];
  if (incident.linkedTransactionId) {
    links.push({
      id: `link-txn-${incident.id}`,
      type: "transaction",
      label: `Transaction ${incident.linkedTransactionId}`,
      href: `/transactions/${incident.linkedTransactionId}`,
    });
  }
  if (incident.linkedApprovalId) {
    links.push({
      id: `link-appr-${incident.id}`,
      type: "approval",
      label: `Approval ${incident.linkedApprovalId}`,
      href: `/approvals/${incident.linkedApprovalId}`,
    });
  }
  if (incident.linkedWorkflowId) {
    links.push({
      id: `link-wf-${incident.id}`,
      type: "workflow",
      label: `Workflow ${incident.linkedWorkflowId}`,
      href: `/transactions?workflow=${incident.linkedWorkflowId}`,
    });
  }
  if (incident.linkedLedgerEntryId) {
    links.push({
      id: `link-ledger-${incident.id}`,
      type: "ledger",
      label: `Ledger Entry ${incident.linkedLedgerEntryId}`,
      href: `/ledger?entry=${incident.linkedLedgerEntryId}`,
    });
  }
  if (incident.linkedPolicyId) {
    links.push({
      id: `link-policy-${incident.id}`,
      type: "policy",
      label: `Policy ${incident.linkedPolicyId}`,
      href: `/policies/${incident.linkedPolicyId}`,
    });
  }
  if (incident.linkedRiskAssessmentId) {
    links.push({
      id: `link-risk-${incident.id}`,
      type: "risk",
      label: `Risk Assessment ${incident.linkedRiskAssessmentId}`,
      href: `/risk?assessment=${incident.linkedRiskAssessmentId}`,
    });
  }
  return links;
}

export function getIncidentEvents(incidentId: string): IncidentEvent[] {
  return incidentEvents
    .filter((e) => e.incidentId === incidentId)
    .sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime());
}
