import type {
  RiskKpi,
  HeatmapRow,
  PolicyMetric,
  Vendor,
  Region,
  TrendPeriod,
  ExceptionMetric,
  Recommendation,
} from "./types";

export const riskKpis: RiskKpi[] = [
  {
    id: "enterprise-risk-score",
    title: "Enterprise Risk Score",
    value: "42",
    trend: "up",
    trendLabel: "+3 pts this quarter",
    status: "warning",
    insight: "Moderate risk driven by geographic concentration in APAC",
    sparklineData: [38, 40, 39, 42, 41, 43, 42, 44, 42],
  },
  {
    id: "policy-compliance",
    title: "Policy Compliance",
    value: "94.2%",
    trend: "up",
    trendLabel: "+1.8% this month",
    status: "healthy",
    insight: "Improved compliance across all business units",
    sparklineData: [89, 90, 91, 92, 93, 93, 94, 94, 94],
  },
  {
    id: "high-risk-transactions",
    title: "High Risk Transactions",
    value: "28",
    trend: "down",
    trendLabel: "-12% this week",
    status: "warning",
    insight: "Declining but concentration in cross-border payments persists",
    sparklineData: [42, 38, 35, 33, 32, 30, 29, 28, 28],
  },
  {
    id: "vendor-risk",
    title: "Vendor Risk Index",
    value: "67",
    trend: "up",
    trendLabel: "+4 pts this month",
    status: "critical",
    insight: "New high-risk vendors in EMEA require immediate review",
    sparklineData: [58, 60, 62, 61, 63, 65, 64, 66, 67],
  },
  {
    id: "critical-exceptions",
    title: "Critical Exceptions",
    value: "14",
    trend: "down",
    trendLabel: "-3 from last week",
    status: "warning",
    insight: "Manual overrides decreasing after policy refinement",
    sparklineData: [22, 20, 19, 18, 17, 16, 15, 14, 14],
  },
  {
    id: "compliance-health",
    title: "Compliance Health",
    value: "88%",
    trend: "up",
    trendLabel: "+5% this quarter",
    status: "healthy",
    insight: "Regulatory alignment improving across all jurisdictions",
    sparklineData: [78, 80, 82, 83, 85, 86, 87, 88, 88],
  },
];

export const heatmapData: HeatmapRow[] = [
  {
    businessUnit: "North America Treasury",
    categories: [
      { category: "Credit Risk", level: "low", value: 15 },
      { category: "Liquidity Risk", level: "medium", value: 38 },
      { category: "Operational Risk", level: "low", value: 22 },
      { category: "Compliance Risk", level: "low", value: 12 },
      { category: "FX Risk", level: "medium", value: 35 },
    ],
  },
  {
    businessUnit: "Europe Treasury",
    categories: [
      { category: "Credit Risk", level: "medium", value: 42 },
      { category: "Liquidity Risk", level: "high", value: 65 },
      { category: "Operational Risk", level: "medium", value: 45 },
      { category: "Compliance Risk", level: "critical", value: 82 },
      { category: "FX Risk", level: "high", value: 70 },
    ],
  },
  {
    businessUnit: "APAC Treasury",
    categories: [
      { category: "Credit Risk", level: "critical", value: 88 },
      { category: "Liquidity Risk", level: "high", value: 72 },
      { category: "Operational Risk", level: "critical", value: 85 },
      { category: "Compliance Risk", level: "high", value: 68 },
      { category: "FX Risk", level: "critical", value: 91 },
    ],
  },
  {
    businessUnit: "Latin America",
    categories: [
      { category: "Credit Risk", level: "high", value: 74 },
      { category: "Liquidity Risk", level: "critical", value: 80 },
      { category: "Operational Risk", level: "medium", value: 48 },
      { category: "Compliance Risk", level: "high", value: 71 },
      { category: "FX Risk", level: "critical", value: 86 },
    ],
  },
  {
    businessUnit: "Middle East & Africa",
    categories: [
      { category: "Credit Risk", level: "high", value: 76 },
      { category: "Liquidity Risk", level: "critical", value: 84 },
      { category: "Operational Risk", level: "high", value: 69 },
      { category: "Compliance Risk", level: "critical", value: 90 },
      { category: "FX Risk", level: "high", value: 78 },
    ],
  },
  {
    businessUnit: "Global Corporate",
    categories: [
      { category: "Credit Risk", level: "medium", value: 34 },
      { category: "Liquidity Risk", level: "low", value: 28 },
      { category: "Operational Risk", level: "medium", value: 41 },
      { category: "Compliance Risk", level: "medium", value: 44 },
      { category: "FX Risk", level: "low", value: 18 },
    ],
  },
];

export const policyMetrics: PolicyMetric[] = [
  {
    id: "most-triggered",
    label: "Most Triggered Policies",
    value: "Cross-Border Payment Limit",
    trend: "up",
    trendLabel: "+18% this month",
    description: "Policy triggered 142 times, primarily EU→APAC transactions",
    status: "warning",
  },
  {
    id: "most-violated",
    label: "Most Violated Policies",
    value: "Dual Approval Required",
    trend: "up",
    trendLabel: "+7% this month",
    description: "32 violations bypassed approval workflow for urgent payments",
    status: "critical",
  },
  {
    id: "approval-escalations",
    label: "Approval Escalations",
    value: "24",
    trend: "down",
    trendLabel: "-15% this month",
    description: "Escalations decreasing after delegation rule updates",
    status: "warning",
  },
  {
    id: "blocked-payments",
    label: "Blocked Payments",
    value: "18",
    trend: "down",
    trendLabel: "-22% this month",
    description: "Policy engine blocked 18 high-risk payments this week",
    status: "healthy",
  },
  {
    id: "override-requests",
    label: "Override Requests",
    value: "9",
    trend: "up",
    trendLabel: "+3 from last week",
    description: "Urgent business override requests requiring executive approval",
    status: "warning",
  },
  {
    id: "policy-trends",
    label: "Policy Effectiveness",
    value: "86%",
    trend: "up",
    trendLabel: "+4% this quarter",
    description: "Policy refinement reducing false positives while maintaining coverage",
    status: "healthy",
  },
];

export const vendors: Vendor[] = [
  {
    id: "v1",
    name: "PagoGlobal Ltd",
    riskLevel: "critical",
    category: "Payment Processing",
    country: "Russia",
    status: "watchlist",
    recommendation: "Increase monitoring frequency to daily",
    addedAt: "2 weeks ago",
  },
  {
    id: "v2",
    name: "SwiftPay Solutions",
    riskLevel: "high",
    category: "Cross-Border Payments",
    country: "China",
    status: "review",
    recommendation: "Review compliance certification validity",
    addedAt: "1 month ago",
  },
  {
    id: "v3",
    name: "Eastern Commerce Group",
    riskLevel: "high",
    category: "ERP Integration",
    country: "Ukraine",
    status: "active",
    recommendation: "Geopolitical risk assessment recommended",
    addedAt: "3 months ago",
  },
  {
    id: "v4",
    name: "Nile Financial Services",
    riskLevel: "critical",
    category: "Banking Partner",
    country: "Nigeria",
    status: "watchlist",
    recommendation: "Pending sanctions screening results",
    addedAt: "1 week ago",
  },
  {
    id: "v5",
    name: "EuroClear Partners",
    riskLevel: "medium",
    category: "Settlement",
    country: "Cyprus",
    status: "review",
    recommendation: "Enhanced due diligence in progress",
    addedAt: "2 months ago",
  },
  {
    id: "v6",
    name: "Pacific Rim Trade",
    riskLevel: "medium",
    category: "Trade Finance",
    country: "Vietnam",
    status: "active",
    recommendation: "Standard monitoring adequate",
    addedAt: "6 months ago",
  },
];

export const regions: Region[] = [
  {
    id: "na",
    name: "North America",
    transactionVolume: "$2.4B",
    riskScore: 28,
    riskLevel: "low",
    policyExceptions: 8,
    trend: "neutral",
    trendLabel: "Stable",
  },
  {
    id: "eu",
    name: "Europe",
    transactionVolume: "$1.8B",
    riskScore: 52,
    riskLevel: "medium",
    policyExceptions: 22,
    trend: "up",
    trendLabel: "+6% this quarter",
  },
  {
    id: "apac",
    name: "Asia-Pacific",
    transactionVolume: "$3.1B",
    riskScore: 78,
    riskLevel: "high",
    policyExceptions: 34,
    trend: "up",
    trendLabel: "+12% this quarter",
  },
  {
    id: "mea",
    name: "Middle East & Africa",
    transactionVolume: "$890M",
    riskScore: 82,
    riskLevel: "critical",
    policyExceptions: 28,
    trend: "up",
    trendLabel: "+9% this quarter",
  },
  {
    id: "latam",
    name: "Latin America",
    transactionVolume: "$620M",
    riskScore: 65,
    riskLevel: "high",
    policyExceptions: 18,
    trend: "down",
    trendLabel: "-3% this month",
  },
  {
    id: "sa",
    name: "South America",
    transactionVolume: "$450M",
    riskScore: 44,
    riskLevel: "medium",
    policyExceptions: 14,
    trend: "down",
    trendLabel: "-2% this month",
  },
];

export const trendPeriods: TrendPeriod[] = [
  {
    id: "weekly",
    label: "Weekly Trend",
    data: [
      { label: "Mon", value: 45, color: "emerald" },
      { label: "Tue", value: 52, color: "emerald" },
      { label: "Wed", value: 48, color: "emerald" },
      { label: "Thu", value: 61, color: "amber" },
      { label: "Fri", value: 55, color: "emerald" },
      { label: "Sat", value: 38, color: "emerald" },
      { label: "Sun", value: 42, color: "emerald" },
    ],
    insight: "Mid-week risk spike driven by high-value EUR settlements",
  },
  {
    id: "monthly",
    label: "Monthly Trend",
    data: [
      { label: "Jan", value: 48, color: "emerald" },
      { label: "Feb", value: 52, color: "emerald" },
      { label: "Mar", value: 58, color: "amber" },
      { label: "Apr", value: 55, color: "emerald" },
      { label: "May", value: 62, color: "amber" },
      { label: "Jun", value: 68, color: "red" },
    ],
    insight: "Sustained upward trend driven by APAC geographic expansion",
  },
  {
    id: "quarterly",
    label: "Quarterly Trend",
    data: [
      { label: "Q1", value: 44, color: "emerald" },
      { label: "Q2", value: 52, color: "amber" },
      { label: "Q3", value: 58, color: "amber" },
      { label: "Q4", value: 62, color: "red" },
    ],
    insight: "Quarter-over-quarter increase of 18 points since Q1",
  },
  {
    id: "yearly",
    label: "Yearly Trend",
    data: [
      { label: "2021", value: 38, color: "emerald" },
      { label: "2022", value: 42, color: "emerald" },
      { label: "2023", value: 48, color: "emerald" },
      { label: "2024", value: 55, color: "amber" },
      { label: "2025", value: 62, color: "red" },
    ],
    insight: "5-year trend shows progressive risk increase as enterprise expands globally",
  },
];

export const exceptionMetrics: ExceptionMetric[] = [
  {
    id: "approval-overrides",
    label: "Approval Overrides",
    count: 14,
    trend: "down",
    trendLabel: "-3 from last week",
    impact: "$2.8M in high-risk payments approved without standard workflow",
    status: "warning",
  },
  {
    id: "policy-bypasses",
    label: "Policy Bypasses",
    count: 9,
    trend: "up",
    trendLabel: "+2 from last week",
    impact: "Bypasses primarily for urgent vendor payments in APAC region",
    status: "critical",
  },
  {
    id: "manual-reviews",
    label: "Manual Reviews",
    count: 38,
    trend: "down",
    trendLabel: "-8% this month",
    impact: "Average review time of 4.2 hours per exception",
    status: "warning",
  },
  {
    id: "failed-controls",
    label: "Failed Controls",
    count: 6,
    trend: "down",
    trendLabel: "-2 from last week",
    impact: "Control failures isolated to legacy sanction screening system",
    status: "healthy",
  },
  {
    id: "escalations",
    label: "Escalations",
    count: 24,
    trend: "down",
    trendLabel: "-15% this month",
    impact: "Escalations reaching CRO level decreased after delegation updates",
    status: "warning",
  },
  {
    id: "rejected-payments",
    label: "Rejected Payments",
    count: 18,
    trend: "down",
    trendLabel: "-22% this month",
    impact: "Rejected payments saved $4.1M in potential compliance penalties",
    status: "healthy",
  },
];

export const recommendations: Recommendation[] = [
  {
    id: "r1",
    title: "Approval Bottlenecks Increasing",
    description: "Manual approval delays growing 15% month-over-month in APAC treasury operations. Consider dynamic delegation rules.",
    impact: "high",
    category: "Process",
    trend: "up",
  },
  {
    id: "r2",
    title: "Vendor Onboarding Risk Improving",
    description: "Enhanced due diligence reduced high-risk vendor onboarding by 28%. Maintain current screening cadence.",
    impact: "medium",
    category: "Vendor",
    trend: "down",
  },
  {
    id: "r3",
    title: "Policy Violations Decreasing",
    description: "Policy refinement reduced false positives by 22% while maintaining 99.8% coverage of high-risk transactions.",
    impact: "high",
    category: "Policy",
    trend: "down",
  },
  {
    id: "r4",
    title: "Treasury Exposure Shifting to Europe",
    description: "European treasury exposure increased 34% this quarter. Review hedging strategy for EUR-denominated positions.",
    impact: "high",
    category: "Geographic",
    trend: "up",
  },
  {
    id: "r5",
    title: "Manual Review Volume Increasing",
    description: "Manual review queue grew 12% this month despite decreasing transaction volumes. Evaluate automated decisioning.",
    impact: "medium",
    category: "Operations",
    trend: "up",
  },
  {
    id: "r6",
    title: "Risk Concentration Detected",
    description: "Top 3 vendors account for 62% of high-risk transaction volume. Diversification strategy recommended.",
    impact: "high",
    category: "Vendor",
    trend: "up",
  },
];
