apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: perionyx-db-pvc
  namespace: perionyx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: perionyx-redis-pvc
  namespace: perionyx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
