import {
  BankingRegion,
  ProviderCapability,
  ConnectionProtocol,
  PaymentRail,
} from "../../domain/types";
import type { ProviderDefinition } from "./types";

export const PROVIDER_DEFINITIONS: ProviderDefinition[] = [
  {
    kind: "plaid",
    name: "Plaid",
    description: "Open banking platform covering US, Canada, and Europe with broad institution coverage and rich transaction data",
    website: "https://plaid.com",
    documentationUrl: "https://plaid.com/docs",
    regions: [
      { region: BankingRegion.NORTH_AMERICA, countries: ["US", "CA"], recommended: true, fallback: false },
      { region: BankingRegion.ASIA_PACIFIC, countries: ["AU", "NZ"], recommended: true, fallback: false },
    ],
    capabilities: [
      ProviderCapability.BALANCES,
      ProviderCapability.TRANSACTIONS,
      ProviderCapability.PAYMENTS,
      ProviderCapability.IDENTITY,
      ProviderCapability.WEBHOOKS,
      ProviderCapability.HISTORICAL_SYNC,
      ProviderCapability.REAL_TIME,
      ProviderCapability.ACCOUNT_DISCOVERY,
      ProviderCapability.ACCOUNT_VERIFICATION,
      ProviderCapability.STATEMENTS,
      ProviderCapability.RECONCILIATION,
    ],
    protocols: [ConnectionProtocol.OAUTH2],
    paymentRails: [PaymentRail.ACH, PaymentRail.ACH_SAME_DAY, PaymentRail.WIRE_DOMESTIC, PaymentRail.RTP, PaymentRail.FEDNOW],
    currencies: ["USD", "CAD", "EUR", "GBP", "AUD", "NZD"],
    requestsPerMinute: 100,
    requestsPerHour: 3000,
    requestsPerDay: 50000,
    maxConcurrentConnections: 50,
    maxHistoryDays: 730,
    sandboxAvailable: true,
    globalPriority: 1,
    failoverPriority: 2,
    requiresClientSecret: true,
    requiresCertificate: false,
    healthEndpoint: "https://status.plaid.com",
    logoUrl: "/logos/plaid.svg",
  },
  {
    kind: "lean",
    name: "Lean",
    description: "Middle Eastern open banking platform covering Saudi Arabia, UAE, Kuwait, Oman, Bahrain, and Qatar with SAMA, CBUAE, and regulatory compliance",
    website: "https://lean.tech",
    documentationUrl: "https://docs.lean.tech",
    regions: [
      { region: BankingRegion.MIDDLE_EAST, countries: ["SA", "AE", "KW", "OM", "BH", "QA"], recommended: true, fallback: false },
      { region: BankingRegion.SAUDI_ARABIA, countries: ["SA"], recommended: true, fallback: false },
      { region: BankingRegion.UAE, countries: ["AE"], recommended: false, fallback: true },
      { region: BankingRegion.KUWAIT, countries: ["KW"], recommended: true, fallback: false },
      { region: BankingRegion.OMAN, countries: ["OM"], recommended: true, fallback: false },
    ],
    capabilities: [
      ProviderCapability.BALANCES,
      ProviderCapability.TRANSACTIONS,
      ProviderCapability.IDENTITY,
      ProviderCapability.WEBHOOKS,
      ProviderCapability.HISTORICAL_SYNC,
      ProviderCapability.ACCOUNT_DISCOVERY,
      ProviderCapability.ACCOUNT_VERIFICATION,
      ProviderCapability.STATEMENTS,
    ],
    protocols: [ConnectionProtocol.OAUTH2, ConnectionProtocol.API_KEY],
    paymentRails: [PaymentRail.SARIE, PaymentRail.MADA, PaymentRail.UAEFTS, PaymentRail.SEPA],
    currencies: ["SAR", "AED", "KWD", "OMR", "BHD", "QAR", "USD", "EUR"],
    requestsPerMinute: 60,
    requestsPerHour: 1800,
    requestsPerDay: 30000,
    maxConcurrentConnections: 30,
    maxHistoryDays: 365,
    sandboxAvailable: true,
    globalPriority: 2,
    failoverPriority: 3,
    requiresClientSecret: true,
    requiresCertificate: false,
    healthEndpoint: "https://status.lean.tech",
  },
  {
    kind: "tarabut",
    name: "Tarabut",
    description: "Open banking platform for Bahrain, Qatar, UAE, and Saudi Arabia with regulatory-compliant connections",
    website: "https://tarabut.com",
    documentationUrl: "https://docs.tarabut.com",
    regions: [
      { region: BankingRegion.MIDDLE_EAST, countries: ["BH", "QA", "AE", "SA"], recommended: false, fallback: false },
      { region: BankingRegion.BAHRAIN, countries: ["BH"], recommended: true, fallback: false },
      { region: BankingRegion.QATAR, countries: ["QA"], recommended: true, fallback: false },
      { region: BankingRegion.SAUDI_ARABIA, countries: ["SA"], recommended: false, fallback: true },
    ],
    capabilities: [
      ProviderCapability.BALANCES,
      ProviderCapability.TRANSACTIONS,
      ProviderCapability.PAYMENTS,
      ProviderCapability.IDENTITY,
      ProviderCapability.WEBHOOKS,
      ProviderCapability.HISTORICAL_SYNC,
      ProviderCapability.ACCOUNT_DISCOVERY,
    ],
    protocols: [ConnectionProtocol.OPEN_BANKING, ConnectionProtocol.OAUTH2],
    paymentRails: [PaymentRail.UAEFTS, PaymentRail.SARIE, PaymentRail.SEPA, PaymentRail.BIPS],
    currencies: ["BHD", "QAR", "AED", "SAR", "USD", "EUR"],
    requestsPerMinute: 50,
    requestsPerHour: 1500,
    requestsPerDay: 25000,
    maxConcurrentConnections: 25,
    maxHistoryDays: 365,
    sandboxAvailable: true,
    globalPriority: 3,
    failoverPriority: 4,
    requiresClientSecret: true,
    requiresCertificate: true,
    healthEndpoint: "https://status.tarabut.com",
  },
  {
    kind: "truelayer",
    name: "TrueLayer",
    description: "European open banking platform covering UK and EU with PSD2-compliant connections and instant payments",
    website: "https://truelayer.com",
    documentationUrl: "https://docs.truelayer.com",
    regions: [
      { region: BankingRegion.EUROPE, countries: ["GB", "DE", "FR", "IT", "ES", "NL", "BE", "AT", "PT", "IE", "PL", "CZ", "HU", "RO", "GR", "LU"], recommended: true, fallback: false },
      { region: BankingRegion.UNITED_KINGDOM, countries: ["GB"], recommended: true, fallback: false },
    ],
    capabilities: [
      ProviderCapability.BALANCES,
      ProviderCapability.TRANSACTIONS,
      ProviderCapability.PAYMENTS,
      ProviderCapability.IDENTITY,
      ProviderCapability.WEBHOOKS,
      ProviderCapability.HISTORICAL_SYNC,
      ProviderCapability.REAL_TIME,
      ProviderCapability.DIRECT_DEBIT,
      ProviderCapability.ACCOUNT_DISCOVERY,
    ],
    protocols: [ConnectionProtocol.OAUTH2, ConnectionProtocol.OPEN_BANKING],
    paymentRails: [PaymentRail.SEPA, PaymentRail.SEPA_INSTANT, PaymentRail.FASTER_PAYMENTS, PaymentRail.BACS, PaymentRail.CHAPS],
    currencies: ["GBP", "EUR", "DKK", "SEK", "NOK", "PLN", "CZK", "HUF"],
    requestsPerMinute: 80,
    requestsPerHour: 2400,
    requestsPerDay: 40000,
    maxConcurrentConnections: 40,
    maxHistoryDays: 730,
    sandboxAvailable: true,
    globalPriority: 4,
    failoverPriority: 5,
    requiresClientSecret: true,
    requiresCertificate: false,
    healthEndpoint: "https://status.truelayer.com",
  },
  {
    kind: "tink",
    name: "Tink",
    description: "European open banking platform with broad PSD2 coverage across 18 markets and data enrichment",
    website: "https://tink.com",
    documentationUrl: "https://docs.tink.com",
    regions: [
      { region: BankingRegion.EUROPE, countries: ["SE", "NO", "DK", "FI", "DE", "FR", "ES", "NL", "BE", "AT", "PT", "IE", "PL", "CZ", "HU", "RO", "GR"], recommended: false, fallback: false },
      { region: BankingRegion.UNITED_KINGDOM, countries: ["GB"], recommended: false, fallback: true },
    ],
    capabilities: [
      ProviderCapability.BALANCES,
      ProviderCapability.TRANSACTIONS,
      ProviderCapability.PAYMENTS,
      ProviderCapability.IDENTITY,
      ProviderCapability.WEBHOOKS,
      ProviderCapability.HISTORICAL_SYNC,
      ProviderCapability.REAL_TIME,
      ProviderCapability.ACCOUNT_VERIFICATION,
      ProviderCapability.ACCOUNT_DISCOVERY,
      ProviderCapability.STATEMENTS,
    ],
    protocols: [ConnectionProtocol.OAUTH2, ConnectionProtocol.OPEN_BANKING],
    paymentRails: [PaymentRail.SEPA, PaymentRail.SEPA_INSTANT],
    currencies: ["EUR", "SEK", "NOK", "DKK", "PLN", "CZK", "HUF", "GBP"],
    requestsPerMinute: 70,
    requestsPerHour: 2100,
    requestsPerDay: 35000,
    maxConcurrentConnections: 35,
    maxHistoryDays: 730,
    sandboxAvailable: true,
    globalPriority: 5,
    failoverPriority: 6,
    requiresClientSecret: true,
    requiresCertificate: false,
    healthEndpoint: "https://status.tink.com",
  },
  {
    kind: "salted",
    name: "Salt Edge",
    description: "Open banking data aggregator covering 90+ countries with broad institution support",
    website: "https://saltedge.com",
    documentationUrl: "https://docs.saltedge.com",
    regions: [
      { region: BankingRegion.EUROPE, countries: ["GB", "DE", "FR", "IT", "ES", "NL", "BE", "AT", "CH", "SE", "NO", "DK", "FI", "PT", "IE", "PL", "CZ", "HU", "RO", "GR", "LU"], recommended: false, fallback: true },
      { region: BankingRegion.NORTH_AMERICA, countries: ["US", "CA"], recommended: false, fallback: true },
      { region: BankingRegion.ASIA_PACIFIC, countries: ["AU", "SG", "HK", "JP", "IN"], recommended: false, fallback: true },
      { region: BankingRegion.AFRICA, countries: ["ZA", "NG", "KE"], recommended: false, fallback: true },
    ],
    capabilities: [
      ProviderCapability.BALANCES,
      ProviderCapability.TRANSACTIONS,
      ProviderCapability.IDENTITY,
      ProviderCapability.WEBHOOKS,
      ProviderCapability.HISTORICAL_SYNC,
      ProviderCapability.ACCOUNT_DISCOVERY,
      ProviderCapability.STATEMENTS,
    ],
    protocols: [ConnectionProtocol.OAUTH2, ConnectionProtocol.API_KEY],
    paymentRails: [PaymentRail.SEPA, PaymentRail.ACH],
    currencies: ["USD", "EUR", "GBP", "CAD", "AUD", "CHF", "JPY", "SGD", "HKD", "ZAR", "NGN", "KES"],
    requestsPerMinute: 60,
    requestsPerHour: 1800,
    requestsPerDay: 30000,
    maxConcurrentConnections: 30,
    maxHistoryDays: 365,
    sandboxAvailable: true,
    globalPriority: 6,
    failoverPriority: 7,
    requiresClientSecret: true,
    requiresCertificate: false,
    healthEndpoint: null,
  },
  {
    kind: "mx",
    name: "MX Technologies",
    description: "US-based open finance platform with data enrichment, categorization, and account verification",
    website: "https://mx.com",
    documentationUrl: "https://docs.mx.com",
    regions: [
      { region: BankingRegion.NORTH_AMERICA, countries: ["US", "CA"], recommended: false, fallback: true },
    ],
    capabilities: [
      ProviderCapability.BALANCES,
      ProviderCapability.TRANSACTIONS,
      ProviderCapability.IDENTITY,
      ProviderCapability.WEBHOOKS,
      ProviderCapability.HISTORICAL_SYNC,
      ProviderCapability.ACCOUNT_DISCOVERY,
      ProviderCapability.ACCOUNT_VERIFICATION,
      ProviderCapability.REPORTING,
    ],
    protocols: [ConnectionProtocol.OAUTH2, ConnectionProtocol.API_KEY],
    paymentRails: [PaymentRail.ACH, PaymentRail.WIRE_DOMESTIC],
    currencies: ["USD", "CAD"],
    requestsPerMinute: 50,
    requestsPerHour: 1500,
    requestsPerDay: 25000,
    maxConcurrentConnections: 25,
    maxHistoryDays: 730,
    sandboxAvailable: true,
    globalPriority: 7,
    failoverPriority: 8,
    requiresClientSecret: true,
    requiresCertificate: false,
    healthEndpoint: "https://status.mx.com",
  },
  {
    kind: "finicity",
    name: "Finicity (Mastercard)",
    description: "US-based open banking platform with income verification and asset reporting for lending",
    website: "https://finicity.com",
    documentationUrl: "https://developer.finicity.com",
    regions: [
      { region: BankingRegion.NORTH_AMERICA, countries: ["US"], recommended: false, fallback: true },
    ],
    capabilities: [
      ProviderCapability.BALANCES,
      ProviderCapability.TRANSACTIONS,
      ProviderCapability.IDENTITY,
      ProviderCapability.ACCOUNT_VERIFICATION,
      ProviderCapability.HISTORICAL_SYNC,
      ProviderCapability.REPORTING,
      ProviderCapability.STATEMENTS,
    ],
    protocols: [ConnectionProtocol.OAUTH2, ConnectionProtocol.API_KEY],
    paymentRails: [PaymentRail.ACH, PaymentRail.WIRE_DOMESTIC],
    currencies: ["USD"],
    requestsPerMinute: 40,
    requestsPerHour: 1200,
    requestsPerDay: 20000,
    maxConcurrentConnections: 20,
    maxHistoryDays: 730,
    sandboxAvailable: true,
    globalPriority: 8,
    failoverPriority: 9,
    requiresClientSecret: true,
    requiresCertificate: false,
    healthEndpoint: "https://status.finicity.com",
  },
  {
    kind: "akoya",
    name: "Akoya",
    description: "US-based open finance platform with tokenized data access and multi-institution aggregation",
    website: "https://akoya.com",
    documentationUrl: "https://docs.akoya.com",
    regions: [
      { region: BankingRegion.NORTH_AMERICA, countries: ["US"], recommended: false, fallback: true },
    ],
    capabilities: [
      ProviderCapability.BALANCES,
      ProviderCapability.TRANSACTIONS,
      ProviderCapability.IDENTITY,
      ProviderCapability.WEBHOOKS,
      ProviderCapability.HISTORICAL_SYNC,
      ProviderCapability.REAL_TIME,
      ProviderCapability.ACCOUNT_DISCOVERY,
    ],
    protocols: [ConnectionProtocol.OAUTH2],
    paymentRails: [PaymentRail.ACH],
    currencies: ["USD"],
    requestsPerMinute: 30,
    requestsPerHour: 900,
    requestsPerDay: 15000,
    maxConcurrentConnections: 15,
    maxHistoryDays: 730,
    sandboxAvailable: true,
    globalPriority: 9,
    failoverPriority: 10,
    requiresClientSecret: true,
    requiresCertificate: false,
    healthEndpoint: null,
  },
  {
    kind: "yodlee",
    name: "Yodlee (Envestnet)",
    description: "Global data aggregation platform covering financial, banking, and investment accounts across 20+ countries",
    website: "https://yodlee.com",
    documentationUrl: "https://developer.yodlee.com",
    regions: [
      { region: BankingRegion.NORTH_AMERICA, countries: ["US", "CA"], recommended: false, fallback: true },
      { region: BankingRegion.ASIA_PACIFIC, countries: ["AU", "SG", "HK", "JP", "IN", "MY", "TH", "PH"], recommended: false, fallback: true },
    ],
    capabilities: [
      ProviderCapability.BALANCES,
      ProviderCapability.TRANSACTIONS,
      ProviderCapability.IDENTITY,
      ProviderCapability.STATEMENTS,
      ProviderCapability.HISTORICAL_SYNC,
      ProviderCapability.REPORTING,
      ProviderCapability.ACCOUNT_DISCOVERY,
    ],
    protocols: [ConnectionProtocol.API_KEY, ConnectionProtocol.OAUTH2],
    paymentRails: [PaymentRail.ACH],
    currencies: ["USD", "CAD", "AUD", "SGD", "HKD", "JPY", "INR", "EUR", "GBP"],
    requestsPerMinute: 40,
    requestsPerHour: 1200,
    requestsPerDay: 20000,
    maxConcurrentConnections: 20,
    maxHistoryDays: 730,
    sandboxAvailable: true,
    globalPriority: 10,
    failoverPriority: 11,
    requiresClientSecret: true,
    requiresCertificate: false,
    healthEndpoint: "https://status.yodlee.com",
  },
  {
    kind: "gocardless",
    name: "GoCardless (Nordigen)",
    description: "European open banking data provider merged with GoCardless, offering free access to bank account data via PSD2",
    website: "https://gocardless.com",
    documentationUrl: "https://developer.gocardless.com",
    regions: [
      { region: BankingRegion.EUROPE, countries: ["GB", "DE", "FR", "ES", "NL", "BE", "AT", "IT", "PT", "IE", "PL", "CZ", "HU", "RO", "GR", "SE", "NO", "DK", "FI"], recommended: false, fallback: true },
      { region: BankingRegion.UNITED_KINGDOM, countries: ["GB"], recommended: false, fallback: true },
    ],
    capabilities: [
      ProviderCapability.BALANCES,
      ProviderCapability.TRANSACTIONS,
      ProviderCapability.DIRECT_DEBIT,
      ProviderCapability.SCHEDULED_PAYMENTS,
      ProviderCapability.WEBHOOKS,
      ProviderCapability.HISTORICAL_SYNC,
      ProviderCapability.ACCOUNT_DISCOVERY,
    ],
    protocols: [ConnectionProtocol.OAUTH2, ConnectionProtocol.API_KEY],
    paymentRails: [PaymentRail.SEPA, PaymentRail.BACS, PaymentRail.FASTER_PAYMENTS],
    currencies: ["EUR", "GBP", "DKK", "SEK", "NOK"],
    requestsPerMinute: 100,
    requestsPerHour: 3000,
    requestsPerDay: 50000,
    maxConcurrentConnections: 50,
    maxHistoryDays: 365,
    sandboxAvailable: true,
    globalPriority: 11,
    failoverPriority: 12,
    requiresClientSecret: true,
    requiresCertificate: false,
    healthEndpoint: "https://status.gocardless.com",
  },
  {
    kind: "direct-api",
    name: "Direct REST API",
    description: "Direct REST API integration for banks that provide their own APIs, supporting auth and balance/transaction retrieval",
    website: "",
    documentationUrl: "",
    regions: [
      { region: BankingRegion.MIDDLE_EAST, countries: ["AE", "SA", "QA", "BH", "KW", "OM", "EG", "JO", "LB"], recommended: false, fallback: true },
      { region: BankingRegion.SAUDI_ARABIA, countries: ["SA"], recommended: false, fallback: true },
      { region: BankingRegion.EGYPT, countries: ["EG"], recommended: true, fallback: true },
      { region: BankingRegion.AFRICA, countries: ["ZA", "NG", "KE", "GH", "MA", "TN", "DZ", "SN", "CI", "ET"], recommended: true, fallback: false },
      { region: BankingRegion.ASIA_PACIFIC, countries: ["AU", "SG", "HK", "JP", "KR", "IN", "ID", "MY", "TH", "VN", "PH", "TW", "CN"], recommended: false, fallback: true },
    ],
    capabilities: [
      ProviderCapability.BALANCES,
      ProviderCapability.TRANSACTIONS,
    ],
    protocols: [ConnectionProtocol.API_KEY, ConnectionProtocol.CERTIFICATE, ConnectionProtocol.MUTUAL_TLS, ConnectionProtocol.BEARER_TOKEN],
    paymentRails: [],
    currencies: ["USD", "EUR", "GBP", "AED", "SAR", "QAR", "BHD", "KWD", "OMR", "EGP", "ZAR", "NGN", "KES", "INR", "JPY", "SGD", "HKD", "AUD"],
    requestsPerMinute: 30,
    requestsPerHour: 600,
    requestsPerDay: 5000,
    maxConcurrentConnections: 10,
    maxHistoryDays: 365,
    sandboxAvailable: false,
    globalPriority: 12,
    failoverPriority: 1,
    requiresClientSecret: true,
    requiresCertificate: true,
    healthEndpoint: null,
  },
  {
    kind: "swift",
    name: "SWIFT Gateway",
    description: "SWIFT network gateway for cross-border payments, statements, and ISO 15022 messaging",
    website: "https://swift.com",
    documentationUrl: "https://developer.swift.com",
    regions: [
      { region: BankingRegion.GLOBAL, countries: [], recommended: true, fallback: false },
    ],
    capabilities: [
      ProviderCapability.PAYMENTS,
      ProviderCapability.BENEFICIARIES,
      ProviderCapability.FX,
      ProviderCapability.STATEMENTS,
      ProviderCapability.REPORTING,
      ProviderCapability.BALANCES,
      ProviderCapability.TRANSACTIONS,
    ],
    protocols: [ConnectionProtocol.SWIFT, ConnectionProtocol.MUTUAL_TLS],
    paymentRails: [PaymentRail.SWIFT, PaymentRail.WIRE_INTERNATIONAL, PaymentRail.TARGET2],
    currencies: ["USD", "EUR", "GBP", "JPY", "CHF", "CAD", "AUD", "CNY", "HKD", "SGD", "SEK", "NOK", "DKK", "NZD", "KRW", "INR", "ZAR", "BRL", "MXN", "SAR", "AED", "TRY"],
    requestsPerMinute: 10,
    requestsPerHour: 300,
    requestsPerDay: 5000,
    maxConcurrentConnections: 5,
    maxHistoryDays: 0,
    sandboxAvailable: true,
    globalPriority: 13,
    failoverPriority: 14,
    requiresClientSecret: false,
    requiresCertificate: true,
    healthEndpoint: null,
  },
  {
    kind: "iso20022",
    name: "ISO 20022 Gateway",
    description: "ISO 20022 XML messaging gateway supporting camt.053, camt.054, pacs.008, and pain.001 messages",
    website: "",
    documentationUrl: "https://www.iso20022.org",
    regions: [
      { region: BankingRegion.GLOBAL, countries: [], recommended: false, fallback: true },
      { region: BankingRegion.EUROPE, countries: ["DE", "FR", "NL", "BE", "AT", "CH", "IT", "ES"], recommended: false, fallback: true },
      { region: BankingRegion.ASIA_PACIFIC, countries: ["JP", "SG", "HK", "AU", "CN"], recommended: false, fallback: true },
    ],
    capabilities: [
      ProviderCapability.BALANCES,
      ProviderCapability.TRANSACTIONS,
      ProviderCapability.STATEMENTS,
      ProviderCapability.PAYMENTS,
      ProviderCapability.SCHEDULED_PAYMENTS,
      ProviderCapability.REPORTING,
      ProviderCapability.RECONCILIATION,
    ],
    protocols: [ConnectionProtocol.ISO_20022, ConnectionProtocol.MUTUAL_TLS, ConnectionProtocol.CERTIFICATE],
    paymentRails: [PaymentRail.SEPA, PaymentRail.SEPA_INSTANT, PaymentRail.SWIFT, PaymentRail.TARGET2, PaymentRail.WIRE_INTERNATIONAL],
    currencies: ["USD", "EUR", "GBP", "JPY", "CHF", "AUD", "CAD", "SGD", "HKD", "CNY"],
    requestsPerMinute: 20,
    requestsPerHour: 500,
    requestsPerDay: 5000,
    maxConcurrentConnections: 10,
    maxHistoryDays: 90,
    sandboxAvailable: true,
    globalPriority: 14,
    failoverPriority: 15,
    requiresClientSecret: false,
    requiresCertificate: true,
    healthEndpoint: null,
  },
  {
    kind: "manual",
    name: "Manual Entry",
    description: "Manual bank account and transaction entry for banks without API access, supporting CSV upload and direct form input",
    website: "",
    documentationUrl: "",
    regions: [
      { region: BankingRegion.GLOBAL, countries: [], recommended: false, fallback: true },
      { region: BankingRegion.NORTH_AMERICA, countries: ["US", "CA", "MX"], recommended: false, fallback: true },
      { region: BankingRegion.EUROPE, countries: [], recommended: false, fallback: true },
      { region: BankingRegion.MIDDLE_EAST, countries: [], recommended: false, fallback: true },
      { region: BankingRegion.AFRICA, countries: [], recommended: false, fallback: true },
      { region: BankingRegion.ASIA_PACIFIC, countries: [], recommended: false, fallback: true },
    ],
    capabilities: [
      ProviderCapability.BALANCES,
      ProviderCapability.TRANSACTIONS,
      ProviderCapability.STATEMENTS,
    ],
    protocols: [ConnectionProtocol.MANUAL],
    paymentRails: [],
    currencies: [],
    requestsPerMinute: 0,
    requestsPerHour: 0,
    requestsPerDay: 0,
    maxConcurrentConnections: 0,
    maxHistoryDays: 0,
    sandboxAvailable: false,
    globalPriority: 15,
    failoverPriority: 16,
    requiresClientSecret: false,
    requiresCertificate: false,
    healthEndpoint: null,
  },
  {
    kind: "csv",
    name: "CSV Import",
    description: "CSV file import for banks and treasury management systems, with auto-column detection and mapping",
    website: "",
    documentationUrl: "",
    regions: [
      { region: BankingRegion.GLOBAL, countries: [], recommended: false, fallback: true },
      { region: BankingRegion.NORTH_AMERICA, countries: ["US", "CA", "MX"], recommended: false, fallback: true },
      { region: BankingRegion.EUROPE, countries: [], recommended: false, fallback: true },
      { region: BankingRegion.MIDDLE_EAST, countries: [], recommended: false, fallback: true },
      { region: BankingRegion.AFRICA, countries: [], recommended: false, fallback: true },
      { region: BankingRegion.ASIA_PACIFIC, countries: [], recommended: false, fallback: true },
    ],
    capabilities: [
      ProviderCapability.BALANCES,
      ProviderCapability.TRANSACTIONS,
    ],
    protocols: [ConnectionProtocol.FILE_IMPORT],
    paymentRails: [],
    currencies: [],
    requestsPerMinute: 0,
    requestsPerHour: 0,
    requestsPerDay: 0,
    maxConcurrentConnections: 0,
    maxHistoryDays: 0,
    sandboxAvailable: false,
    globalPriority: 16,
    failoverPriority: 17,
    requiresClientSecret: false,
    requiresCertificate: false,
    healthEndpoint: null,
  },
];

export const PROVIDER_DEFINITION_MAP = new Map<string, ProviderDefinition>(
  PROVIDER_DEFINITIONS.map((def) => [def.kind, def]),
);

export const PROVIDER_KINDS = PROVIDER_DEFINITIONS.map((def) => def.kind);

export function getProviderDefinition(kind: string): ProviderDefinition | undefined {
  return PROVIDER_DEFINITION_MAP.get(kind);
}

export function getProvidersByRegion(region: BankingRegion): ProviderDefinition[] {
  return PROVIDER_DEFINITIONS.filter((def) =>
    def.regions.some((r) => r.region === region),
  );
}

export function getProvidersByCountry(countryCode: string): ProviderDefinition[] {
  return PROVIDER_DEFINITIONS.filter((def) =>
    def.regions.some((r) => r.countries.includes(countryCode) || r.countries.length === 0),
  );
}

export function getProvidersByCapability(capability: ProviderCapability): ProviderDefinition[] {
  return PROVIDER_DEFINITIONS.filter((def) =>
    def.capabilities.includes(capability),
  );
}

export function getProvidersByCurrency(currency: string): ProviderDefinition[] {
  return PROVIDER_DEFINITIONS.filter((def) =>
    def.currencies.length === 0 || def.currencies.includes(currency),
  );
}
