// ─────────────────────────────────────────────────────────────
// Executive Command Center — Demo Scenarios
// 11 guided scenarios demonstrating cross-specialist collaboration
// ─────────────────────────────────────────────────────────────

import type { DemoScenario } from "./types";

export const DEMO_SCENARIOS: DemoScenario[] = [
  // ─── 1. Month-End Close ─────────────────────────────────
  {
    id: "scenario-month-end-close",
    name: "Month-End Close",
    description: "Execute a full month-end close cycle across all accounting domains, from journal review through statement publication.",
    category: "close",
    difficulty: "beginner",
    duration: "25 min",
    specialists: ["controller", "cfo-advisor", "fpa", "audit"],
    learningObjectives: [
      "Understand the month-end close workflow",
      "Identify bottlenecks in close management",
      "Review statement readiness indicators",
      "Generate CFO close briefing",
    ],
    prerequisites: ["Active chart of accounts", "Posted transactions for the period"],
    steps: [
      {
        id: "close-1",
        title: "Review Close Period Status",
        description: "Check the current close period status and identify any incomplete steps.",
        specialist: "controller",
        action: "Navigate to Controller Dashboard → Close Periods",
        expectedResult: "View open close periods with completion percentages and outstanding tasks",
        drillDown: { type: "specialist", specialist: "controller", label: "Close Period Details" },
        tips: ["Look for periods with red indicators — these need immediate attention"],
      },
      {
        id: "close-2",
        title: "Journal Entry Risk Review",
        description: "Review journal entries for risk indicators, late postings, and unusual amounts.",
        specialist: "controller",
        action: "Navigate to Controller → Journal Review",
        expectedResult: "View journal risk summary with flagged entries for manual review",
        tips: ["Focus on entries posted in the last 3 days of the period", "Check for round-dollar entries and reversal patterns"],
      },
      {
        id: "close-3",
        title: "Reconciliation Status Check",
        description: "Verify all bank and intercompany reconciliations are complete.",
        specialist: "controller",
        action: "Check reconciliation dashboard within Close Management",
        expectedResult: "All critical accounts reconciled with no unexplained variances",
        tips: ["Unreconciled items over $10K require investigation before close"],
      },
      {
        id: "close-4",
        title: "Accounting Health Assessment",
        description: "Review the overall accounting health score and identify any anomalies.",
        specialist: "controller",
        action: "Navigate to Controller → Accounting Health",
        expectedResult: "Health score displayed with trend indicators and recommendations",
        tips: ["A score below 70 requires investigation before closing"],
      },
      {
        id: "close-5",
        title: "FP&A Variance Analysis",
        description: "Compare actuals to budget and investigate significant variances.",
        specialist: "fpa",
        action: "Navigate to FP&A → Variance Analysis",
        expectedResult: "Variance report with auto-flagged items exceeding thresholds",
        drillDown: { type: "specialist", specialist: "fpa", label: "Variance Details" },
        tips: ["Variances >10% are auto-flagged", "Commentary is required for material variances"],
      },
      {
        id: "close-6",
        title: "Statement Readiness Verification",
        description: "Check if all financial statements are ready for publication.",
        specialist: "controller",
        action: "Navigate to Controller → Statement Readiness",
        expectedResult: "Readiness checklist with all statements in green status",
        tips: ["Each statement has 6 readiness criteria including reconciliation completion"],
      },
      {
        id: "close-7",
        title: "Generate CFO Briefing",
        description: "Generate the month-end CFO briefing with close summary and key metrics.",
        specialist: "cfo-advisor",
        action: "Navigate to CFO Advisor → Generate Briefing",
        expectedResult: "Briefing generated with executive summary, cash position, and recommendations",
        drillDown: { type: "specialist", specialist: "cfo-advisor", label: "Briefing Details" },
        tips: ["The briefing auto-composes data from controller, treasury, and compliance"],
      },
      {
        id: "close-8",
        title: "Audit Trail Verification",
        description: "Verify the audit trail is complete for all close activities.",
        specialist: "audit",
        action: "Navigate to Audit → Continuous Audit",
        expectedResult: "Audit log showing all close actions with timestamps and actors",
        tips: ["Every close action should have an audit trail entry"],
      },
    ],
  },

  // ─── 2. Treasury Review ─────────────────────────────────
  {
    id: "scenario-treasury-review",
    name: "Treasury Review",
    description: "Review enterprise treasury position including cash, liquidity, FX exposure, debt, and investments.",
    category: "treasury",
    difficulty: "beginner",
    duration: "20 min",
    specialists: ["treasury", "cfo-advisor", "governance"],
    learningObjectives: [
      "Understand treasury dashboard composition",
      "Review cash position across entities",
      "Assess FX exposure and hedging needs",
      "Evaluate debt covenant compliance",
    ],
    prerequisites: ["Bank account connections", "Cash position data loaded"],
    steps: [
      {
        id: "treasury-1",
        title: "Cash Position Overview",
        description: "Review consolidated cash position across all entities and currencies.",
        specialist: "treasury",
        action: "Navigate to Treasury → Cash Position",
        expectedResult: "Global cash position with currency breakdown and entity allocation",
        drillDown: { type: "specialist", specialist: "treasury", label: "Cash Position Detail" },
        tips: ["Check for accounts below minimum balance thresholds"],
      },
      {
        id: "treasury-2",
        title: "Liquidity Horizon Analysis",
        description: "Review 7-day, 30-day, 90-day, and 12-month liquidity projections.",
        specialist: "treasury",
        action: "Navigate to Treasury → Liquidity",
        expectedResult: "Liquidity waterfall with forecast boundary clearly marked",
        tips: ["Focus on the 30-day window for operational liquidity"],
      },
      {
        id: "treasury-3",
        title: "FX Exposure Assessment",
        description: "Review foreign currency exposures and hedging positions.",
        specialist: "treasury",
        action: "Navigate to Treasury → FX Exposure",
        expectedResult: "FX exposure by currency with hedge ratios and gain/loss estimates",
        drillDown: { type: "specialist", specialist: "treasury", label: "FX Exposure Detail" },
        tips: ["Unhedged exposures >$100K require attention"],
      },
      {
        id: "treasury-4",
        title: "Debt Covenant Check",
        description: "Verify all debt covenants are in compliance.",
        specialist: "treasury",
        action: "Navigate to Treasury → Debt Instruments",
        expectedResult: "Debt instruments with covenant compliance indicators",
        tips: ["Red covenant indicators require immediate action"],
      },
      {
        id: "treasury-5",
        title: "Investment Portfolio Review",
        description: "Review investment portfolio performance and allocation.",
        specialist: "treasury",
        action: "Navigate to Treasury → Investments",
        expectedResult: "Portfolio summary with allocation, returns, and maturity schedule",
        tips: ["Check for investments maturing within 90 days"],
      },
      {
        id: "treasury-6",
        title: "Generate CFO Treasury Briefing",
        description: "Compose treasury data into CFO-level briefing.",
        specialist: "cfo-advisor",
        action: "Navigate to CFO Advisor → Latest Briefing",
        expectedResult: "Briefing with treasury section highlighting key metrics and risks",
        drillDown: { type: "specialist", specialist: "cfo-advisor", label: "CFO Briefing" },
        tips: ["The briefing auto-pulls data from treasury specialist"],
      },
    ],
  },

  // ─── 3. Board Meeting Preparation ───────────────────────
  {
    id: "scenario-board-meeting",
    name: "Board Meeting Preparation",
    description: "Prepare all materials for an upcoming board meeting, composing inputs from all specialists.",
    category: "governance",
    difficulty: "advanced",
    duration: "35 min",
    specialists: ["governance", "cfo-advisor", "controller", "treasury", "compliance", "audit", "fpa", "tax"],
    learningObjectives: [
      "Understand cross-specialist data composition for board packs",
      "Review governance readiness indicators",
      "Assess board meeting preparation completeness",
      "Generate board briefing materials",
    ],
    prerequisites: ["Board meeting scheduled", "At least one board pack template"],
    steps: [
      {
        id: "board-1",
        title: "Review Upcoming Board Meeting",
        description: "Check meeting details, agenda items, and attendance requirements.",
        specialist: "governance",
        action: "Navigate to Governance → Board Meetings",
        expectedResult: "Meeting details with agenda, attendee list, and quorum status",
        drillDown: { type: "specialist", specialist: "governance", label: "Meeting Details" },
        tips: ["Verify quorum will be met before the meeting"],
      },
      {
        id: "board-2",
        title: "Collect Financial Highlights",
        description: "Gather financial overview from CFO Advisor for board presentation.",
        specialist: "cfo-advisor",
        action: "Generate CFO Board Pack for current period",
        expectedResult: "Board pack section with financial highlights, risks, and opportunities",
        tips: ["The board pack auto-composes from briefings and recommendations"],
      },
      {
        id: "board-3",
        title: "Controller Close Status",
        description: "Verify close status and statement readiness for board reporting period.",
        specialist: "controller",
        action: "Check Controller → Statement Readiness",
        expectedResult: "All financial statements in 'ready' status for the reporting period",
        tips: ["Board packs require statements to be finalized"],
      },
      {
        id: "board-4",
        title: "Treasury Position Summary",
        description: "Include treasury highlights in board materials.",
        specialist: "treasury",
        action: "Navigate to Treasury → Dashboard",
        expectedResult: "Cash position, liquidity, and risk summary for board review",
        tips: ["Include forward-looking liquidity outlook"],
      },
      {
        id: "board-5",
        title: "Compliance & Risk Overview",
        description: "Include compliance status and risk summary in board pack.",
        specialist: "compliance",
        action: "Navigate to Compliance → Executive Summary",
        expectedResult: "Compliance health, open violations, and regulatory updates",
        drillDown: { type: "specialist", specialist: "compliance", label: "Compliance Status" },
        tips: ["Highlight any critical compliance issues"],
      },
      {
        id: "board-6",
        title: "Audit Findings Summary",
        description: "Include open audit findings and remediation status.",
        specialist: "audit",
        action: "Navigate to Audit → Executive Summary",
        expectedResult: "Findings summary with remediation progress and open items",
        tips: ["Board should see both open findings and remediation progress"],
      },
      {
        id: "board-7",
        title: "FP&A Strategic Outlook",
        description: "Include forecast and strategic planning highlights.",
        specialist: "fpa",
        action: "Navigate to FP&A → Executive Support",
        expectedResult: "Strategic outlook with forecast highlights and capital allocation",
        tips: ["Include scenario analysis results if available"],
      },
      {
        id: "board-8",
        title: "Assemble Board Pack",
        description: "Compose all specialist inputs into final board pack.",
        specialist: "governance",
        action: "Navigate to Governance → Board Packs → Create Pack",
        expectedResult: "Board pack assembled with all sections from all specialists",
        drillDown: { type: "specialist", specialist: "governance", label: "Board Pack" },
        tips: ["Review all sections before distribution"],
      },
    ],
  },

  // ─── 4. Audit Preparation ──────────────────────────────
  {
    id: "scenario-audit-preparation",
    name: "Audit Preparation",
    description: "Prepare for an external audit by reviewing controls, findings, evidence, and remediation status.",
    category: "audit",
    difficulty: "advanced",
    duration: "30 min",
    specialists: ["audit", "controller", "compliance", "cfo-advisor"],
    learningObjectives: [
      "Understand audit readiness assessment",
      "Review control effectiveness metrics",
      "Track findings and remediation progress",
      "Prepare evidence for auditors",
    ],
    prerequisites: ["Audit planning completed", "Controls documented"],
    steps: [
      {
        id: "audit-1",
        title: "Audit Readiness Assessment",
        description: "Review the overall audit readiness score and identify gaps.",
        specialist: "audit",
        action: "Navigate to Audit → Readiness",
        expectedResult: "Readiness score with gap analysis and remediation timeline",
        drillDown: { type: "specialist", specialist: "audit", label: "Audit Readiness" },
        tips: ["Focus on gaps with severity 'high' or 'critical'"],
      },
      {
        id: "audit-2",
        title: "Control Effectiveness Review",
        description: "Review control testing results and effectiveness scores.",
        specialist: "audit",
        action: "Navigate to Audit → Control Monitoring",
        expectedResult: "Control effectiveness dashboard with pass/fail rates by domain",
        tips: ["Controls with <80% effectiveness need remediation before audit"],
      },
      {
        id: "audit-3",
        title: "Open Findings Triage",
        description: "Review and prioritize all open audit findings.",
        specialist: "audit",
        action: "Navigate to Audit → Findings",
        expectedResult: "Findings list sorted by severity with remediation status",
        drillDown: { type: "specialist", specialist: "audit", label: "Findings Detail" },
        tips: ["Critical findings must be remediated or have a documented plan"],
      },
      {
        id: "audit-4",
        title: "Evidence Collection",
        description: "Verify all required evidence is collected and catalogued.",
        specialist: "audit",
        action: "Navigate to Audit → Evidence Management",
        expectedResult: "Evidence inventory with completeness check",
        tips: ["Evidence should be dated, sourced, and cross-referenced"],
      },
      {
        id: "audit-5",
        title: "Remediation Progress",
        description: "Review remediation plan progress for all open findings.",
        specialist: "audit",
        action: "Navigate to Audit → Remediation",
        expectedResult: "Remediation plans with progress indicators and deadlines",
        tips: ["Overdue remediations need escalation"],
      },
      {
        id: "audit-6",
        title: "Controller Readiness Verification",
        description: "Verify accounting controls and reconciliation status.",
        specialist: "controller",
        action: "Navigate to Controller → Accounting Health",
        expectedResult: "Accounting health score with reconciliation and close status",
        tips: ["Accounting health should be >80 before audit"],
      },
      {
        id: "audit-7",
        title: "Compliance Controls Check",
        description: "Review compliance framework controls and policy adherence.",
        specialist: "compliance",
        action: "Navigate to Compliance → Monitoring",
        expectedResult: "Compliance health with policy adherence and violation status",
        drillDown: { type: "specialist", specialist: "compliance", label: "Compliance Status" },
        tips: ["Audit will review compliance controls alongside financial controls"],
      },
      {
        id: "audit-8",
        title: "Generate Audit Readiness Report",
        description: "Compose all findings into a final audit readiness report.",
        specialist: "audit",
        action: "Generate audit readiness summary",
        expectedResult: "Comprehensive readiness report with score, gaps, and remediation plan",
        tips: ["This report should be shared with audit committee"],
      },
    ],
  },

  // ─── 5. Compliance Review ──────────────────────────────
  {
    id: "scenario-compliance-review",
    name: "Compliance Review",
    description: "Comprehensive compliance review covering frameworks, policies, obligations, violations, and filings.",
    category: "compliance",
    difficulty: "intermediate",
    duration: "20 min",
    specialists: ["compliance", "audit", "cfo-advisor"],
    learningObjectives: [
      "Review compliance framework status",
      "Assess policy adherence and violations",
      "Track regulatory obligations and filings",
      "Understand compliance monitoring workflow",
    ],
    prerequisites: ["Compliance frameworks configured", "Policies published"],
    steps: [
      {
        id: "compliance-1",
        title: "Framework Overview",
        description: "Review all active compliance frameworks and their status.",
        specialist: "compliance",
        action: "Navigate to Compliance → Frameworks",
        expectedResult: "List of active frameworks with compliance scores",
        drillDown: { type: "specialist", specialist: "compliance", label: "Framework Details" },
        tips: ["Check for frameworks with status 'needs-attention'"],
      },
      {
        id: "compliance-2",
        title: "Policy Engine Review",
        description: "Review active policies and their enforcement status.",
        specialist: "compliance",
        action: "Navigate to Compliance → Policies",
        expectedResult: "Policy list with enforcement status and violation counts",
        tips: ["Policies with recent violations need review"],
      },
      {
        id: "compliance-3",
        title: "Obligation Tracker",
        description: "Review regulatory obligations and their compliance status.",
        specialist: "compliance",
        action: "Navigate to Compliance → Obligations",
        expectedResult: "Obligations list with status, due dates, and compliance indicators",
        tips: ["Overdue obligations are auto-flagged as critical"],
      },
      {
        id: "compliance-4",
        title: "Violation Assessment",
        description: "Review open violations and their severity distribution.",
        specialist: "compliance",
        action: "Navigate to Compliance → Violations",
        expectedResult: "Violations by severity with remediation status",
        drillDown: { type: "specialist", specialist: "compliance", label: "Violation Details" },
        tips: ["Critical violations require immediate escalation"],
      },
      {
        id: "compliance-5",
        title: "Filing Calendar",
        description: "Review upcoming compliance filings and deadlines.",
        specialist: "compliance",
        action: "Navigate to Compliance → Filings",
        expectedResult: "Filing calendar with upcoming deadlines and completion status",
        tips: ["Filings due within 7 days should be prioritized"],
      },
      {
        id: "compliance-6",
        title: "Audit Cross-Check",
        description: "Cross-reference compliance findings with audit controls.",
        specialist: "audit",
        action: "Navigate to Audit → Control Monitoring",
        expectedResult: "Audit controls mapped to compliance requirements",
        tips: ["Compliance violations often correlate with control weaknesses"],
      },
    ],
  },

  // ─── 6. Tax Planning ───────────────────────────────────
  {
    id: "scenario-tax-planning",
    name: "Tax Planning",
    description: "Review tax position, provisions, transfer pricing, and plan optimization strategies.",
    category: "tax",
    difficulty: "advanced",
    duration: "25 min",
    specialists: ["tax", "cfo-advisor", "compliance"],
    learningObjectives: [
      "Understand tax provision calculations",
      "Review transfer pricing compliance",
      "Assess tax risk across jurisdictions",
      "Generate tax optimization recommendations",
    ],
    prerequisites: ["Tax jurisdictions configured", "Transfer pricing policies defined"],
    steps: [
      {
        id: "tax-1",
        title: "Tax Dashboard Overview",
        description: "Review overall tax position across all jurisdictions.",
        specialist: "tax",
        action: "Navigate to Tax Specialist → Dashboard",
        expectedResult: "Tax dashboard with liability, payments, and deadline status",
        drillDown: { type: "specialist", specialist: "tax", label: "Tax Dashboard" },
        tips: ["Check for overdue deadlines first"],
      },
      {
        id: "tax-2",
        title: "Tax Provision Review",
        description: "Review current and deferred tax provisions.",
        specialist: "tax",
        action: "Navigate to Tax → Provisions",
        expectedResult: "Tax provision calculations with effective tax rate analysis",
        tips: ["Provisions should reconcile with financial statements"],
      },
      {
        id: "tax-3",
        title: "Transfer Pricing Assessment",
        description: "Review transfer pricing policies and intercompany transactions.",
        specialist: "tax",
        action: "Navigate to Tax → Transfer Pricing",
        expectedResult: "Transfer pricing summary with arm's-length compliance indicators",
        drillDown: { type: "specialist", specialist: "tax", label: "Transfer Pricing" },
        tips: ["Document all transfer pricing decisions with supporting evidence"],
      },
      {
        id: "tax-4",
        title: "Tax Risk Evaluation",
        description: "Assess tax risks across all jurisdictions.",
        specialist: "tax",
        action: "Navigate to Tax → Risk Assessment",
        expectedResult: "Risk matrix by jurisdiction with likelihood and impact scores",
        tips: ["High-risk jurisdictions need proactive planning"],
      },
      {
        id: "tax-5",
        title: "Tax Calendar Review",
        description: "Review upcoming tax deadlines and filing requirements.",
        specialist: "tax",
        action: "Navigate to Tax → Calendar",
        expectedResult: "Tax calendar with upcoming deadlines and filing status",
        tips: ["Missing tax deadlines can result in penalties"],
      },
      {
        id: "tax-6",
        title: "CFO Tax Briefing",
        description: "Generate tax-specific briefing for CFO review.",
        specialist: "cfo-advisor",
        action: "Navigate to CFO Advisor → Latest Briefing",
        expectedResult: "Briefing with tax section highlighting key risks and opportunities",
        tips: ["Briefing auto-composes tax data from the specialist"],
      },
    ],
  },

  // ─── 7. Budget Review ──────────────────────────────────
  {
    id: "scenario-budget-review",
    name: "Budget Review",
    description: "Review budget performance, analyze variances, and update forecasts based on actual results.",
    category: "planning",
    difficulty: "intermediate",
    duration: "25 min",
    specialists: ["fpa", "cfo-advisor", "controller"],
    learningObjectives: [
      "Understand budget variance analysis",
      "Review forecast accuracy",
      "Assess capital allocation effectiveness",
      "Generate FP&A recommendations",
    ],
    prerequisites: ["Active budget loaded", "Actual data available for comparison"],
    steps: [
      {
        id: "budget-1",
        title: "Budget Overview",
        description: "Review overall budget status and spending progress.",
        specialist: "fpa",
        action: "Navigate to FP&A → Budgets",
        expectedResult: "Budget dashboard with spend vs. plan by department",
        drillDown: { type: "specialist", specialist: "fpa", label: "Budget Detail" },
        tips: ["Focus on departments with >15% variance"],
      },
      {
        id: "budget-2",
        title: "Variance Analysis",
        description: "Deep dive into significant budget variances.",
        specialist: "fpa",
        action: "Navigate to FP&A → Variance Analysis",
        expectedResult: "Variance report with auto-flagged items exceeding thresholds",
        tips: ["Material variances require management commentary"],
      },
      {
        id: "budget-3",
        title: "Forecast Update",
        description: "Review and update forecasts based on year-to-date actuals.",
        specialist: "fpa",
        action: "Navigate to FP&A → Forecasts",
        expectedResult: "Forecast comparison with revised projections",
        tips: ["Rolling forecasts should be updated monthly"],
      },
      {
        id: "budget-4",
        title: "Strategic Plan Alignment",
        description: "Verify budget alignment with strategic plans.",
        specialist: "fpa",
        action: "Navigate to FP&A → Strategic Plans",
        expectedResult: "Strategic plan progress with budget allocation tracking",
        tips: ["Check that spending supports strategic priorities"],
      },
      {
        id: "budget-5",
        title: "Capital Allocation Review",
        description: "Review capital expenditure proposals and allocation.",
        specialist: "fpa",
        action: "Navigate to FP&A → Capital Allocation",
        expectedResult: "Capital proposals with ROI analysis and approval status",
        tips: ["Proposals >$100K need CFO approval"],
      },
      {
        id: "budget-6",
        title: "Controller Data Validation",
        description: "Verify actual data integrity from controller specialist.",
        specialist: "controller",
        action: "Navigate to Controller → Accounting Health",
        expectedResult: "Accounting health score confirming data reliability",
        tips: ["Budget analysis should only use validated data"],
      },
    ],
  },

  // ─── 8. Cash Crisis ────────────────────────────────────
  {
    id: "scenario-cash-crisis",
    name: "Cash Crisis",
    description: "Respond to a simulated cash emergency: low balances, covenant breach risk, and emergency funding needs.",
    category: "crisis",
    difficulty: "advanced",
    duration: "20 min",
    specialists: ["treasury", "cfo-advisor", "governance", "compliance"],
    learningObjectives: [
      "Respond to a cash emergency scenario",
      "Understand emergency funding options",
      "Assess covenant breach implications",
      "Coordinate cross-functional crisis response",
    ],
    prerequisites: ["Treasury data loaded with alert thresholds configured"],
    steps: [
      {
        id: "crisis-1",
        title: "Cash Emergency Detection",
        description: "Identify accounts below minimum balance thresholds and projected cash shortfalls.",
        specialist: "treasury",
        action: "Navigate to Treasury → Cash Position",
        expectedResult: "Cash position showing accounts below threshold with shortfall projections",
        drillDown: { type: "specialist", specialist: "treasury", label: "Cash Emergency" },
        tips: ["Focus on accounts with negative projected balances within 7 days"],
      },
      {
        id: "crisis-2",
        title: "Liquidity Stress Assessment",
        description: "Review liquidity under stress scenarios.",
        specialist: "treasury",
        action: "Navigate to Treasury → Liquidity",
        expectedResult: "Liquidity waterfall showing stress scenario impact",
        tips: ["Check 7-day and 30-day liquidity windows first"],
      },
      {
        id: "crisis-3",
        title: "Covenant Breach Risk",
        description: "Assess risk of debt covenant breach due to cash shortfall.",
        specialist: "treasury",
        action: "Navigate to Treasury → Debt Instruments",
        expectedResult: "Covenant compliance status with breach risk indicators",
        drillDown: { type: "specialist", specialist: "treasury", label: "Covenant Status" },
        tips: ["Proactive lender communication is critical if breach is likely"],
      },
      {
        id: "crisis-4",
        title: "Emergency Funding Options",
        description: "Evaluate available emergency funding sources.",
        specialist: "treasury",
        action: "Review available credit facilities and short-term funding options",
        expectedResult: "List of available funding sources with terms and capacity",
        tips: ["Compare cost of different funding options"],
      },
      {
        id: "crisis-5",
        title: "CFO Escalation",
        description: "Escalate cash crisis to CFO with situation summary and recommendations.",
        specialist: "cfo-advisor",
        action: "Navigate to CFO Advisor → Generate Emergency Briefing",
        expectedResult: "Emergency briefing with situation summary, options, and recommendations",
        tips: ["Briefing should include all specialist inputs for the crisis"],
      },
      {
        id: "crisis-6",
        title: "Board Notification",
        description: "Notify board governance of the cash situation and planned response.",
        specialist: "governance",
        action: "Navigate to Governance → Actions → Create Emergency Action",
        expectedResult: "Emergency action item created for board notification",
        tips: ["Material cash events may require board notification per bylaws"],
      },
    ],
  },

  // ─── 9. Fraud Investigation ────────────────────────────
  {
    id: "scenario-fraud-investigation",
    name: "Fraud Investigation",
    description: "Respond to a suspected fraud scenario: evidence collection, control review, and compliance assessment.",
    category: "investigation",
    difficulty: "advanced",
    duration: "30 min",
    specialists: ["audit", "compliance", "controller", "cfo-advisor"],
    learningObjectives: [
      "Understand fraud investigation workflow",
      "Collect and preserve audit evidence",
      "Review control weaknesses that enabled fraud",
      "Assess compliance implications",
    ],
    prerequisites: ["Audit evidence management configured", "Compliance framework active"],
    steps: [
      {
        id: "fraud-1",
        title: "Initial Assessment",
        description: "Assess the scope and nature of suspected fraudulent activity.",
        specialist: "audit",
        action: "Navigate to Audit → Findings → Create Finding",
        expectedResult: "Finding created with fraud classification and initial scope",
        drillDown: { type: "specialist", specialist: "audit", label: "Finding Details" },
        tips: ["Preserve all evidence before investigation begins"],
      },
      {
        id: "fraud-2",
        title: "Evidence Collection",
        description: "Collect and catalog all relevant evidence.",
        specialist: "audit",
        action: "Navigate to Audit → Evidence Management",
        expectedResult: "Evidence inventory with chain of custody documentation",
        tips: ["Evidence must be time-stamped and attributed"],
      },
      {
        id: "fraud-3",
        title: "Control Weakness Analysis",
        description: "Identify control weaknesses that enabled or failed to detect the fraud.",
        specialist: "audit",
        action: "Navigate to Audit → Control Monitoring",
        expectedResult: "Control effectiveness review with weakness identification",
        drillDown: { type: "specialist", specialist: "audit", label: "Control Analysis" },
        tips: ["Document the root cause of control failure"],
      },
      {
        id: "fraud-4",
        title: "Journal Entry Investigation",
        description: "Review journal entries for suspicious patterns.",
        specialist: "controller",
        action: "Navigate to Controller → Journal Review",
        expectedResult: "Journal entries flagged for unusual patterns or amounts",
        tips: ["Look for entries without proper documentation or approvals"],
      },
      {
        id: "fraud-5",
        title: "Compliance Implications",
        description: "Assess regulatory reporting requirements and compliance implications.",
        specialist: "compliance",
        action: "Navigate to Compliance → Violations → Create Violation",
        expectedResult: "Compliance violation created with regulatory reporting assessment",
        tips: ["Some fraud events require mandatory regulatory reporting"],
      },
      {
        id: "fraud-6",
        title: "CFO Briefing and Escalation",
        description: "Brief CFO on findings and determine escalation path.",
        specialist: "cfo-advisor",
        action: "Generate emergency briefing for CFO",
        expectedResult: "Briefing with investigation status, evidence summary, and recommended actions",
        tips: ["Legal counsel should be involved before external disclosure"],
      },
    ],
  },

  // ─── 10. Acquisition Scenario ──────────────────────────
  {
    id: "scenario-acquisition",
    name: "Acquisition Scenario",
    description: "Evaluate a potential acquisition: due diligence across all specialist domains.",
    category: "ma",
    difficulty: "advanced",
    duration: "35 min",
    specialists: ["fpa", "tax", "compliance", "audit", "governance", "cfo-advisor"],
    learningObjectives: [
      "Understand cross-specialist due diligence workflow",
      "Assess financial, tax, and compliance risks",
      "Evaluate operational synergies",
      "Prepare board presentation for acquisition decision",
    ],
    prerequisites: ["Target company data available", "Board meeting scheduled for decision"],
    steps: [
      {
        id: "ma-1",
        title: "Financial Due Diligence",
        description: "Review target company financials and valuation.",
        specialist: "fpa",
        action: "Navigate to FP&A → Scenario Modeling",
        expectedResult: "Acquisition scenario with pro-forma financials and synergy estimates",
        drillDown: { type: "specialist", specialist: "fpa", label: "Financial Model" },
        tips: ["Focus on quality of earnings and sustainable revenue"],
      },
      {
        id: "ma-2",
        title: "Tax Structure Assessment",
        description: "Evaluate tax implications of the acquisition structure.",
        specialist: "tax",
        action: "Navigate to Tax → Transfer Pricing → New Entity Analysis",
        expectedResult: "Tax structure analysis with entity-level tax impact",
        tips: ["Consider both immediate and long-term tax implications"],
      },
      {
        id: "ma-3",
        title: "Compliance Risk Assessment",
        description: "Assess compliance risks and regulatory requirements.",
        specialist: "compliance",
        action: "Navigate to Compliance → Frameworks → Assessment",
        expectedResult: "Compliance risk profile with regulatory obligations",
        drillDown: { type: "specialist", specialist: "compliance", label: "Compliance Risk" },
        tips: ["Check for pending regulatory actions against the target"],
      },
      {
        id: "ma-4",
        title: "Internal Controls Review",
        description: "Assess the target's internal controls and audit findings.",
        specialist: "audit",
        action: "Navigate to Audit → Control Monitoring → Due Diligence View",
        expectedResult: "Control effectiveness report with weakness assessment",
        tips: ["Material control weaknesses affect valuation"],
      },
      {
        id: "ma-5",
        title: "Governance Integration",
        description: "Plan governance integration for the acquired entity.",
        specialist: "governance",
        action: "Navigate to Governance → Board → Integration Planning",
        expectedResult: "Governance integration plan with board structure recommendations",
        tips: ["Consider board representation and committee membership"],
      },
      {
        id: "ma-6",
        title: "Executive Summary",
        description: "Compose all specialist inputs into acquisition recommendation.",
        specialist: "cfo-advisor",
        action: "Navigate to CFO Advisor → Scenario Analysis",
        expectedResult: "Executive summary with recommendation, risks, and integration timeline",
        tips: ["Board should see both the case for and against the acquisition"],
      },
    ],
  },

  // ─── 11. Executive Briefing ────────────────────────────
  {
    id: "scenario-executive-briefing",
    name: "Executive Briefing",
    description: "Generate a comprehensive executive briefing composing insights from all specialist domains.",
    category: "briefing",
    difficulty: "beginner",
    duration: "15 min",
    specialists: ["cfo-advisor", "controller", "treasury", "compliance", "audit", "fpa", "tax", "governance"],
    learningObjectives: [
      "Understand how specialist data composes into executive briefings",
      "Review cross-domain metrics and alerts",
      "Understand the health score composition",
      "Navigate the unified executive dashboard",
    ],
    prerequisites: ["All specialist modules configured with data"],
    steps: [
      {
        id: "briefing-1",
        title: "Open Executive Command Center",
        description: "Navigate to the unified executive dashboard.",
        specialist: "cfo-advisor",
        action: "Navigate to Executive Command Center",
        expectedResult: "Unified dashboard with health score, KPIs, alerts, and recommendations",
        drillDown: { type: "specialist", specialist: "cfo-advisor", label: "Command Center" },
        tips: ["The dashboard loads all specialist data in parallel"],
      },
      {
        id: "briefing-2",
        title: "Review Enterprise Health Score",
        description: "Understand the weighted health score from all domains.",
        specialist: "cfo-advisor",
        action: "Review health score breakdown in Command Center",
        expectedResult: "Health score with per-domain breakdown and source attribution",
        tips: ["Each domain score is weighted and sourced from its specialist"],
      },
      {
        id: "briefing-3",
        title: "Review Unified KPIs",
        description: "Review key performance indicators from all specialists.",
        specialist: "cfo-advisor",
        action: "Review KPI section in Command Center",
        expectedResult: "Unified KPI list with source specialist, trend, and status",
        tips: ["KPIs are extracted from each specialist's dashboard data"],
      },
      {
        id: "briefing-4",
        title: "Alert Triage",
        description: "Review and triage alerts from all specialist domains.",
        specialist: "cfo-advisor",
        action: "Review alerts section in Command Center",
        expectedResult: "Sorted alerts by severity with source and action requirements",
        tips: ["Critical alerts from any specialist bubble up to the command center"],
      },
      {
        id: "briefing-5",
        title: "Risk Summary Review",
        description: "Review the enterprise risk summary across all domains.",
        specialist: "cfo-advisor",
        action: "Review risk summary in Command Center",
        expectedResult: "Risk categories with scores and top risks from each specialist",
        tips: ["Risk scores are inverted health scores — higher means more risk"],
      },
      {
        id: "briefing-6",
        title: "Calendar Overview",
        description: "Review upcoming events from all specialists.",
        specialist: "cfo-advisor",
        action: "Review calendar section in Command Center",
        expectedResult: "Unified calendar with events from governance, compliance, tax, and audit",
        tips: ["Calendar events are sorted by date across all specialists"],
      },
    ],
  },
];
