import type {
  SuggestedQuestion,
  ContextSource,
  EnterpriseInsight,
  RecommendedAction,
  Session,
  KnowledgeSource,
} from "./types";

export const suggestedQuestions: SuggestedQuestion[] = [
  { id: "q1", text: "Why was this payment blocked?", category: "Transactions" },
  { id: "q2", text: "Show my pending approvals", category: "Approvals" },
  { id: "q3", text: "Forecast liquidity for next 30 days", category: "Treasury" },
  { id: "q4", text: "Which vendors are highest risk?", category: "Risk" },
  { id: "q5", text: "Find duplicate invoices", category: "Transactions" },
  { id: "q6", text: "Explain this journal entry", category: "Ledger" },
  { id: "q7", text: "Show treasury health overview", category: "Treasury" },
  { id: "q8", text: "Summarize today's activity", category: "Dashboard" },
  { id: "q9", text: "What changed since yesterday?", category: "Dashboard" },
  { id: "q10", text: "Trace a payment lifecycle", category: "Transactions" },
  { id: "q11", text: "Show blocked payments this month", category: "Transactions" },
  { id: "q12", text: "Generate executive briefing", category: "Executive" },
];

export const contextSources: ContextSource[] = [
  { id: "cs-treasury", name: "Treasury", status: "connected", lastUpdated: "Real-time", availability: "live" },
  { id: "cs-wallets", name: "Wallets", status: "connected", lastUpdated: "Real-time", availability: "live" },
  { id: "cs-transactions", name: "Transactions", status: "connected", lastUpdated: "Real-time", availability: "live" },
  { id: "cs-ledger", name: "Ledger", status: "connected", lastUpdated: "Real-time", availability: "live" },
  { id: "cs-approvals", name: "Approvals", status: "connected", lastUpdated: "Real-time", availability: "live" },
  { id: "cs-policies", name: "Policies", status: "connected", lastUpdated: "Real-time", availability: "live" },
  { id: "cs-audit", name: "Audit", status: "connected", lastUpdated: "Real-time", availability: "live" },
  { id: "cs-risk", name: "Risk", status: "connected", lastUpdated: "5 min ago", availability: "live" },
  { id: "cs-recon", name: "Reconciliation", status: "connected", lastUpdated: "10 min ago", availability: "live" },
  { id: "cs-rates", name: "Exchange Rates", status: "connected", lastUpdated: "15 min ago", availability: "live" },
  { id: "cs-calendar", name: "Calendar", status: "connected", lastUpdated: "Real-time", availability: "live" },
  { id: "cs-notifications", name: "Notifications", status: "connected", lastUpdated: "Real-time", availability: "live" },
  { id: "cs-connectors", name: "Connectors", status: "connected", lastUpdated: "2 min ago", availability: "live" },
  { id: "cs-platform", name: "Platform Health", status: "connected", lastUpdated: "1 min ago", availability: "live" },
  { id: "cs-developer", name: "Developer Portal", status: "connected", lastUpdated: "10 min ago", availability: "live" },
  { id: "cs-webhooks", name: "Webhooks", status: "connected", lastUpdated: "5 min ago", availability: "live" },
];

export const enterpriseInsights: EnterpriseInsight[] = [
  {
    id: "ei-1",
    title: "Approval Efficiency Increased",
    description: "Average approval time decreased to 1.8 hours. Delegation rule updates reduced escalation volume by 22%.",
    trend: "up",
    trendLabel: "+18% efficiency",
    category: "Approvals",
  },
  {
    id: "ei-2",
    title: "Treasury Liquidity Remains Healthy",
    description: "$4.2B available across all accounts. All covenant ratios compliant. No liquidity concerns for next 30 days.",
    trend: "neutral",
    trendLabel: "Stable",
    category: "Treasury",
  },
  {
    id: "ei-3",
    title: "Risk Exposure Decreased",
    description: "Enterprise Risk Score improved to 42 (-3 pts). Critical exceptions down 18% from last month.",
    trend: "down",
    trendLabel: "-3 pts",
    category: "Risk",
  },
  {
    id: "ei-4",
    title: "No Critical Platform Incidents",
    description: "All platform services operating normally. Zero P0 incidents. Average uptime 99.97%.",
    trend: "neutral",
    trendLabel: "All clear",
    category: "Platform",
  },
  {
    id: "ei-5",
    title: "Settlement Performance Exceeded Target",
    description: "98.7% of settlements completed within SLA. Average settlement time reduced to 2.4 hours.",
    trend: "up",
    trendLabel: "+2.1% vs target",
    category: "Operations",
  },
  {
    id: "ei-6",
    title: "Compliance Score Improved",
    description: "Regulatory compliance score reached 94.2%. Policy refinement reduced false positives while maintaining coverage.",
    trend: "up",
    trendLabel: "+1.8% this quarter",
    category: "Compliance",
  },
];

export const recommendedActions: RecommendedAction[] = [
  {
    id: "ra-1",
    title: "Generate Executive Briefing",
    description: "Comprehensive briefing for board or management",
    href: "/copilot",
    icon: "file-text",
  },
  {
    id: "ra-2",
    title: "Review High Risk Transactions",
    description: "Transactions flagged by policy or risk engine",
    href: "/risk",
    icon: "alert-triangle",
  },
  {
    id: "ra-3",
    title: "Review Treasury Position",
    description: "Liquidity, balances, FX exposure analysis",
    href: "/wallets",
    icon: "landmark",
  },
  {
    id: "ra-4",
    title: "Trace Payment Lifecycle",
    description: "Full event timeline from creation to settlement",
    href: "/copilot",
    icon: "monitor",
  },
  {
    id: "ra-5",
    title: "Analyze Vendor Risk",
    description: "Vendor risk index and recommendations",
    href: "/risk",
    icon: "building-2",
  },
  {
    id: "ra-6",
    title: "Summarize Audit Activity",
    description: "Recent audit log activity and policy changes",
    href: "/audit-logs",
    icon: "scroll-text",
  },
  {
    id: "ra-7",
    title: "Run Reconciliation",
    description: "Bank-to-ledger matching and exception handling",
    href: "/reconciliation",
    icon: "book-open",
  },
  {
    id: "ra-8",
    title: "Review Platform Health",
    description: "Service monitoring and integration status",
    href: "/operations",
    icon: "activity",
  },
];

export const recentSessions: Session[] = [
  { id: "s-1", title: "Executive Briefing", preview: "Full enterprise briefing — treasury, risk, approvals, compliance", date: "2 hours ago", messageCount: 8 },
  { id: "s-2", title: "Treasury Intelligence", preview: "Cash position, liquidity analysis, FX exposure", date: "1 day ago", messageCount: 5 },
  { id: "s-3", title: "Risk Review", preview: "Vendor risk assessment, open incidents, policy violations", date: "3 days ago", messageCount: 6 },
  { id: "s-4", title: "Audit Trail Analysis", preview: "Recent policy changes, control failures, compliance status", date: "5 days ago", messageCount: 4 },
  { id: "s-5", title: "Operations Overview", preview: "Platform health, connector status, queue performance", date: "1 week ago", messageCount: 7 },
  { id: "s-6", title: "Payment Investigation", preview: "Traced TXN-1044 lifecycle — policy, approval, ledger, settlement", date: "1 week ago", messageCount: 9 },
  { id: "s-7", title: "Board Report", preview: "Monthly board briefing — KPIs, risk, liquidity, compliance", date: "2 weeks ago", messageCount: 12 },
  { id: "s-8", title: "Vendor Intelligence", preview: "Comprehensive vendor risk analysis and recommendations", date: "2 weeks ago", messageCount: 6 },
];

export const knowledgeSources: KnowledgeSource[] = [
  { id: "ks-dash", name: "Dashboard", recordsAvailable: "Real-time KPIs", lastIndexed: "Live", status: "synced" },
  { id: "ks-tx", name: "Transactions", recordsAvailable: "Full transaction history", lastIndexed: "Live", status: "synced" },
  { id: "ks-wallets", name: "Wallets", recordsAvailable: "Multi-currency balances", lastIndexed: "Live", status: "synced" },
  { id: "ks-treasury", name: "Treasury", recordsAvailable: "Accounts and controls", lastIndexed: "Live", status: "synced" },
  { id: "ks-ledger", name: "Ledger", recordsAvailable: "Double-entry postings", lastIndexed: "Live", status: "synced" },
  { id: "ks-approvals", name: "Approvals", recordsAvailable: "Approval threads and chains", lastIndexed: "Live", status: "synced" },
  { id: "ks-policy", name: "Policy Engine", recordsAvailable: "Policies and rules", lastIndexed: "Live", status: "synced" },
  { id: "ks-audit", name: "Audit", recordsAvailable: "Immutable audit events", lastIndexed: "Live", status: "synced" },
  { id: "ks-risk", name: "Risk", recordsAvailable: "Alerts and incidents", lastIndexed: "Live", status: "synced" },
  { id: "ks-recon", name: "Reconciliation", recordsAvailable: "Run history and exceptions", lastIndexed: "Live", status: "synced" },
  { id: "ks-rates", name: "Exchange Rates", recordsAvailable: "FX rate tables", lastIndexed: "Live", status: "synced" },
  { id: "ks-calendar", name: "Calendar", recordsAvailable: "Events and holidays", lastIndexed: "Live", status: "synced" },
  { id: "ks-notifications", name: "Notifications", recordsAvailable: "System notifications", lastIndexed: "Live", status: "synced" },
  { id: "ks-connectors", name: "Connectors", recordsAvailable: "Integration connections", lastIndexed: "Live", status: "synced" },
  { id: "ks-api", name: "API Keys", recordsAvailable: "Developer keys", lastIndexed: "Live", status: "synced" },
  { id: "ks-webhooks", name: "Webhooks", recordsAvailable: "Webhook configurations", lastIndexed: "Live", status: "synced" },
  { id: "ks-platform", name: "Platform Health", recordsAvailable: "Service monitoring", lastIndexed: "Live", status: "synced" },
];
