apiVersion: v1
kind: ConfigMap
metadata:
  name: perionyx-config
  namespace: perionyx
data:
  NODE_ENV: production
  NEXT_PUBLIC_APP_URL: https://app.perionyx.com
  NEXT_TELEMETRY_DISABLED: "1"
  PORT: "3000"
  HOSTNAME: "0.0.0.0"
  REDIS_HOST: perionyx-redis
  REDIS_PORT: "6379"
  LOG_LEVEL: info
  LOG_FORMAT: json
  CACHE_PROVIDER: redis
  QUEUE_PROVIDER: redis
  STORAGE_PATH: /data/storage
  FEATURE_INSTALLER: "true"
  FEATURE_DEPLOYMENT_DASHBOARD: "true"
