export type EntityType =
  | "ORGANIZATION" | "BUSINESS_UNIT" | "DEPARTMENT"
  | "USER" | "ROLE"
  | "WORKFLOW" | "WORKFLOW_INSTANCE"
  | "APPROVAL" | "POLICY" | "RULE"
  | "TREASURY_ACCOUNT" | "BANK"
  | "PAYMENT" | "INVOICE" | "VENDOR" | "CUSTOMER"
  | "RISK" | "COMPLIANCE_ITEM"
  | "AUDIT_EVENT" | "NOTIFICATION"
  | "AUTOMATION" | "DASHBOARD" | "REPORT";

export type RelationshipType =
  | "DEPENDS_ON" | "APPROVES" | "TRIGGERS" | "REFERENCES"
  | "CREATES" | "UPDATES" | "CONSUMES"
  | "VIOLATES" | "COMPLIES_WITH" | "ESCALATES_TO"
  | "BLOCKS" | "RELATED_TO" | "INHERITED_FROM"
  | "OWNED_BY" | "GENERATED_BY";

export interface GraphRelationship {
  id: string;
  sourceType: EntityType;
  sourceId: string;
  targetType: EntityType;
  targetId: string;
  relationshipType: RelationshipType;
  label: string;
  metadata: Record<string, unknown>;
  companyId: string;
  createdAt: string;
  expiresAt: string;
  auditRef: string;
}

export interface GraphNode {
  entityType: EntityType;
  entityId: string;
  label: string;
  metadata: Record<string, unknown>;
}

export interface RelationshipRuleDefinition {
  sourceType: EntityType;
  targetType: EntityType;
  relationshipType: RelationshipType;
  inverseType: RelationshipType;
  description: string;
  resolverPriority: number;
}

export interface BusinessContext {
  entityType: EntityType;
  entityId: string;
  label: string;
  relatedWorkflows: GraphRelationship[];
  relatedApprovals: GraphRelationship[];
  relatedRisks: GraphRelationship[];
  relatedPolicies: GraphRelationship[];
  relatedReports: GraphRelationship[];
  relatedDashboards: GraphRelationship[];
  relatedUsers: GraphRelationship[];
  relatedNotifications: GraphRelationship[];
  relatedAnalytics: GraphRelationship[];
  relatedAccounts: GraphRelationship[];
  relatedCompliance: GraphRelationship[];
  contextGeneratedAt: string;
}

export interface ImpactAnalysis {
  entityType: EntityType;
  entityId: string;
  directImpacts: GraphRelationship[];
  indirectImpacts: GraphRelationship[];
  blockedBy: GraphRelationship[];
  blocks: GraphRelationship[];
  riskLevel: "low" | "moderate" | "high" | "critical";
  affectedEntityCount: number;
  analyzedAt: string;
}

export interface DependencyChain {
  root: GraphNode;
  chain: { node: GraphNode; relationship: GraphRelationship; depth: number }[];
  cycleDetected: boolean;
  maxDepth: number;
}

export interface GraphQuery {
  sourceType?: EntityType;
  sourceId?: string;
  targetType?: EntityType;
  targetId?: string;
  relationshipType?: RelationshipType;
  companyId: string;
  maxDepth?: number;
  limit?: number;
}

export interface GraphQueryResult {
  relationships: GraphRelationship[];
  totalCount: number;
  query: GraphQuery;
  generatedAt: string;
}

export const ENTITY_LABELS: Record<EntityType, string> = {
  ORGANIZATION: "Organization",
  BUSINESS_UNIT: "Business Unit",
  DEPARTMENT: "Department",
  USER: "User",
  ROLE: "Role",
  WORKFLOW: "Workflow",
  WORKFLOW_INSTANCE: "Workflow Instance",
  APPROVAL: "Approval",
  POLICY: "Policy",
  RULE: "Rule",
  TREASURY_ACCOUNT: "Treasury Account",
  BANK: "Bank",
  PAYMENT: "Payment",
  INVOICE: "Invoice",
  VENDOR: "Vendor",
  CUSTOMER: "Customer",
  RISK: "Risk",
  COMPLIANCE_ITEM: "Compliance Item",
  AUDIT_EVENT: "Audit Event",
  NOTIFICATION: "Notification",
  AUTOMATION: "Automation",
  DASHBOARD: "Dashboard",
  REPORT: "Report",
};

export const RELATIONSHIP_LABELS: Record<RelationshipType, string> = {
  DEPENDS_ON: "Depends On",
  APPROVES: "Approves",
  TRIGGERS: "Triggers",
  REFERENCES: "References",
  CREATES: "Creates",
  UPDATES: "Updates",
  CONSUMES: "Consumes",
  VIOLATES: "Violates",
  COMPLIES_WITH: "Complies With",
  ESCALATES_TO: "Escalates To",
  BLOCKS: "Blocks",
  RELATED_TO: "Related To",
  INHERITED_FROM: "Inherited From",
  OWNED_BY: "Owned By",
  GENERATED_BY: "Generated By",
};
