#!/usr/bin/env tsx
/**
 * Phase 22.0B.5 — EDL CI Pipeline: Report Generator
 *
 * Generates DESIGN_COMPLIANCE_REPORT.md with all audit data.
 * Usage: pnpm edl:report
 */

import * as fs from "fs";
import * as path from "path";

const ROOT = path.resolve(__dirname, "../..");
const DOCS_DIR = path.join(ROOT, "docs/design");

// Import and run audits
const { scanCodebase } = require("./validators/codebase-scanner");
const { auditPages } = require("./auditors/page-auditor");

console.log("═══════════════════════════════════════════════");
console.log("  EDL Compliance Report Generator");
console.log("═══════════════════════════════════════════════\n");

const scan = scanCodebase();
const pages = auditPages();

// Count component violations
const componentsDir = path.join(ROOT, "src/components/enterprise");
let componentViolations = 0;
let componentCount = 0;

function countComponentViolations(dir: string) {
  if (!fs.existsSync(dir)) return;
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      countComponentViolations(full);
    } else if (entry.name.endsWith(".tsx")) {
      componentCount++;
      const content = fs.readFileSync(full, "utf-8");
      const hexMatches = content.match(/#([0-9a-fA-F]{3,8})\b/g) || [];
      const allowed = new Set(["#d4af37", "#e5c04a", "#c7a961", "#0a0a0f", "#111118", "#1a1a24", "#222230", "#f7f6f2", "#a1a1aa", "#71717a", "#52525b", "#22c55e", "#f59e0b", "#ef4444", "#3b82f6"]);
      const forbidden = hexMatches.filter((h) => !allowed.has(h.toLowerCase()));
      componentViolations += forbidden.length;
    }
  }
}

countComponentViolations(componentsDir);

const pageAvg = pages.length > 0 ? Math.round(pages.reduce((s: number, p: any) => s + p.score, 0) / pages.length) : 100;
const componentCompliance = componentCount > 0 ? Math.max(0, Math.round(100 - (componentViolations / componentCount) * 10)) : 100;

const now = new Date().toISOString().split("T")[0];

const report = `# Design Compliance Report

**Generated**: ${now}
**Phase**: 22.0B.5 — Enterprise Design Governance

---

## Executive Summary

| Metric | Score | Status |
|---|---|---|
| Codebase Scan | ${scan.score}% | ${scan.score >= 70 ? "✅ PASS" : scan.score >= 50 ? "⚠️ WARN" : "❌ FAIL"} |
| Page Compliance | ${pageAvg}% | ${pageAvg >= 70 ? "✅ PASS" : pageAvg >= 50 ? "⚠️ WARN" : "❌ FAIL"} |
| Component Compliance | ${componentCompliance}% | ${componentCompliance >= 70 ? "✅ PASS" : componentCompliance >= 50 ? "⚠️ WARN" : "❌ FAIL"} |

## Scan Statistics

| Metric | Value |
|---|---|
| Files scanned | ${scan.totalFiles} |
| Files with violations | ${scan.filesWithViolations} |
| Total violations | ${scan.totalViolations} |
| Pages audited | ${pages.length} |
| Components audited | ${componentCount} |

## Violation Breakdown

### By Rule

| Rule | Count |
|---|---|
| Hardcoded colors | ${scan.byRule.get("no-hardcoded-colors") || 0} |
| Hardcoded rgba | ${scan.byRule.get("no-hardcoded-rgba") || 0} |
| Hardcoded spacing | ${scan.byRule.get("no-hardcoded-spacing") || 0} |
| Hardcoded shadows | ${scan.byRule.get("no-hardcoded-shadow") || 0} |
| Hardcoded z-index | ${scan.byRule.get("no-hardcoded-zindex") || 0} |
| Hardcoded radius | ${scan.byRule.get("no-hardcoded-radius") || 0} |
| Hardcoded font-size | ${scan.byRule.get("no-hardcoded-fontsize") || 0} |
| Legacy imports | ${scan.byRule.get("no-legacy-imports") || 0} |
| Arbitrary Tailwind colors | ${scan.byRule.get("no-arbitrary-tailwind-colors") || 0} |

## Page Compliance

| Page | Score | Violations |
|---|---|---|
${pages.map((p: any) => `| ${p.relativePath} | ${p.score}% | ${p.totalViolations} |`).join("\n")}

## Migration Status

| Category | Status |
|---|---|
| Legacy gold hex → #d4af37 | ✅ Complete |
| Wrong surfaces → EDL surfaces | ✅ Complete |
| Tailwind arbitrary → EDL utilities | ✅ Complete |
| Legacy motion tokens → EDL re-export | ✅ Complete |
| Inline rgba() → EDL tokens | 🔄 Partial (~300 remaining) |
| Inline shadows → EDL tokens | 🔄 Partial (~50 remaining) |

## Enforcement

\`\`\`bash
pnpm edl:audit       # Full audit — all validators
pnpm edl:fix         # Auto-fix safe violations
pnpm edl:report      # Generate this report
pnpm edl:tokens      # Token health check
pnpm edl:compliance  # Component + page compliance
\`\`\`

---

*Generated by EDL Governance Tooling — Phase 22.0B.5*
*Architecture is enforced through tooling, not documentation.*
`;

if (!fs.existsSync(DOCS_DIR)) {
  fs.mkdirSync(DOCS_DIR, { recursive: true });
}

fs.writeFileSync(path.join(DOCS_DIR, "DESIGN_COMPLIANCE_REPORT.md"), report);
console.log(`\n✅ Report generated: docs/design/DESIGN_COMPLIANCE_REPORT.md`);
console.log(`   Overall: Codebase ${scan.score}% | Pages ${pageAvg}% | Components ${componentCompliance}%`);
