import type { ConsolidationService } from "./services/consolidation-service";
import type {
  LegalEntity, OwnershipRecord, ConsolidationRun, CurrencyTranslationRun, HistoricalRate,
  IntercompanyRecord, MinorityInterestRecord, EquityAccountRecord, ConsolidationAdjustment,
  FinancialStatementEntry, FinancialStatementSet, BoardReport, BoardReportSection,
  ManagementReportEntry, ConsolidationAlert, ConsolidationRecommendation, ConsolidationKPI,
} from "./types";

const NOW = new Date("2026-07-15T12:00:00Z");
const DAY = 86400000;
const COMPANY = "company-1";

function daysAgo(n: number): Date { return new Date(NOW.getTime() - n * DAY); }
function daysAhead(n: number): Date { return new Date(NOW.getTime() + n * DAY); }

export function seedConsolidationData(svc: ConsolidationService): void {
  // =========================================================================
  // 1. Legal Entities (10 entities across 6 countries)
  // =========================================================================
  const holding: LegalEntity = {
    id: "entity-holding",
    entityCode: "PGH-00",
    legalName: "Perionyx Group Holdings Ltd",
    tradingName: "Perionyx Group",
    entityType: "holding",
    countryOfIncorporation: "United States",
    taxId: "US-98-7654321",
    registrationNumber: "DE-442211",
    functionalCurrency: "USD",
    consolidationMethod: "full",
    isConsolidated: true,
    consolidationScope: "full",
    fiscalYearEnd: "12-31",
    fiscalPeriod: 7,
    address: "1200 Avenue of the Americas",
    city: "New York",
    country: "United States",
    status: "active",
    subsidiaries: ["entity-parent", "entity-ventures", "entity-properties", "entity-innovations"],
    createdById: "user-admin",
    companyId: COMPANY,
    createdAt: daysAgo(1095),
    updatedAt: daysAgo(30),
  };

  const parent: LegalEntity = {
    id: "entity-parent",
    entityCode: "PIN-01",
    legalName: "Perionyx Inc",
    tradingName: "Perionyx US",
    entityType: "parent",
    countryOfIncorporation: "United States",
    taxId: "US-12-3456789",
    registrationNumber: "DE-123456",
    functionalCurrency: "USD",
    consolidationMethod: "full",
    isConsolidated: true,
    consolidationScope: "full",
    fiscalYearEnd: "12-31",
    fiscalPeriod: 7,
    address: "1200 Avenue of the Americas, Floor 12",
    city: "New York",
    country: "United States",
    status: "active",
    parentEntityId: "entity-holding",
    subsidiaries: ["entity-eu", "entity-uk", "entity-asia", "entity-latam", "entity-india"],
    createdById: "user-admin",
    companyId: COMPANY,
    createdAt: daysAgo(1095),
    updatedAt: daysAgo(30),
  };

  const eu: LegalEntity = {
    id: "entity-eu",
    entityCode: "PBV-02",
    legalName: "Perionyx BV",
    tradingName: "Perionyx EU",
    entityType: "subsidiary",
    countryOfIncorporation: "Netherlands",
    taxId: "NL-823456789B01",
    registrationNumber: "KvK-30224567",
    functionalCurrency: "EUR",
    consolidationMethod: "full",
    isConsolidated: true,
    consolidationScope: "full",
    fiscalYearEnd: "12-31",
    fiscalPeriod: 7,
    address: "Keizersgracht 482",
    city: "Amsterdam",
    country: "Netherlands",
    status: "active",
    parentEntityId: "entity-parent",
    subsidiaries: [],
    createdById: "user-admin",
    companyId: COMPANY,
    createdAt: daysAgo(730),
    updatedAt: daysAgo(14),
  };

  const uk: LegalEntity = {
    id: "entity-uk",
    entityCode: "PUK-03",
    legalName: "Perionyx UK Ltd",
    tradingName: "Perionyx UK",
    entityType: "subsidiary",
    countryOfIncorporation: "United Kingdom",
    taxId: "GB-456789123",
    registrationNumber: "UK-09876543",
    functionalCurrency: "GBP",
    consolidationMethod: "full",
    isConsolidated: true,
    consolidationScope: "full",
    fiscalYearEnd: "12-31",
    fiscalPeriod: 7,
    address: "30 St Mary Axe",
    city: "London",
    country: "United Kingdom",
    status: "active",
    parentEntityId: "entity-parent",
    subsidiaries: [],
    createdById: "user-admin",
    companyId: COMPANY,
    createdAt: daysAgo(640),
    updatedAt: daysAgo(10),
  };

  const asia: LegalEntity = {
    id: "entity-asia",
    entityCode: "PAP-04",
    legalName: "Perionyx Asia Pte Ltd",
    tradingName: "Perionyx Asia",
    entityType: "subsidiary",
    countryOfIncorporation: "Singapore",
    taxId: "SG-201812345A",
    registrationNumber: "UEN-201812345A",
    functionalCurrency: "SGD",
    consolidationMethod: "full",
    isConsolidated: true,
    consolidationScope: "full",
    fiscalYearEnd: "12-31",
    fiscalPeriod: 7,
    address: "1 Raffles Place #20-01",
    city: "Singapore",
    country: "Singapore",
    status: "active",
    parentEntityId: "entity-parent",
    subsidiaries: ["entity-china"],
    createdById: "user-admin",
    companyId: COMPANY,
    createdAt: daysAgo(500),
    updatedAt: daysAgo(8),
  };

  const china: LegalEntity = {
    id: "entity-china",
    entityCode: "PCC-05",
    legalName: "Perionyx China Co Ltd",
    tradingName: "Perionyx China",
    entityType: "subsidiary",
    countryOfIncorporation: "China",
    taxId: "CN-310123456789012",
    registrationNumber: "CN-91310000MA1K1234X",
    functionalCurrency: "CNY",
    consolidationMethod: "full",
    isConsolidated: true,
    consolidationScope: "full",
    fiscalYearEnd: "12-31",
    fiscalPeriod: 7,
    address: "100 Century Avenue, Pudong",
    city: "Shanghai",
    country: "China",
    status: "active",
    parentEntityId: "entity-asia",
    subsidiaries: [],
    createdById: "user-admin",
    companyId: COMPANY,
    createdAt: daysAgo(365),
    updatedAt: daysAgo(5),
  };

  const latam: LegalEntity = {
    id: "entity-latam",
    entityCode: "PLL-06",
    legalName: "Perionyx LATAM Ltda",
    tradingName: "Perionyx LATAM",
    entityType: "subsidiary",
    countryOfIncorporation: "Brazil",
    taxId: "BR-11.222.333/0001-44",
    registrationNumber: "CNPJ-11222333000144",
    functionalCurrency: "BRL",
    consolidationMethod: "full",
    isConsolidated: true,
    consolidationScope: "full",
    fiscalYearEnd: "12-31",
    fiscalPeriod: 7,
    address: "Av. Paulista 1000, 15º andar",
    city: "São Paulo",
    country: "Brazil",
    status: "active",
    parentEntityId: "entity-parent",
    subsidiaries: [],
    createdById: "user-admin",
    companyId: COMPANY,
    createdAt: daysAgo(300),
    updatedAt: daysAgo(5),
  };

  const ventures: LegalEntity = {
    id: "entity-ventures",
    entityCode: "PVL-07",
    legalName: "Perionyx Ventures LLC",
    tradingName: "Perionyx Ventures",
    entityType: "associate",
    countryOfIncorporation: "United States",
    taxId: "US-87-6543210",
    registrationNumber: "DE-776655",
    functionalCurrency: "USD",
    consolidationMethod: "equity",
    isConsolidated: true,
    consolidationScope: "equity",
    fiscalYearEnd: "12-31",
    fiscalPeriod: 7,
    address: "200 Innovation Drive",
    city: "San Francisco",
    country: "United States",
    status: "active",
    parentEntityId: "entity-holding",
    subsidiaries: [],
    createdById: "user-admin",
    companyId: COMPANY,
    createdAt: daysAgo(540),
    updatedAt: daysAgo(20),
  };

  const innovations: LegalEntity = {
    id: "entity-innovations",
    entityCode: "PIJ-08",
    legalName: "Perionyx Innovations JV",
    tradingName: "Perionyx JV",
    entityType: "jointVenture",
    countryOfIncorporation: "United States",
    taxId: "US-56-7890123",
    registrationNumber: "DE-998877",
    functionalCurrency: "USD",
    consolidationMethod: "equity",
    isConsolidated: true,
    consolidationScope: "equity",
    fiscalYearEnd: "12-31",
    fiscalPeriod: 7,
    address: "500 Technology Park",
    city: "Boston",
    country: "United States",
    status: "active",
    parentEntityId: "entity-holding",
    subsidiaries: [],
    createdById: "user-admin",
    companyId: COMPANY,
    createdAt: daysAgo(180),
    updatedAt: daysAgo(10),
  };

  const properties: LegalEntity = {
    id: "entity-properties",
    entityCode: "PPL-09",
    legalName: "Perionyx Properties LLC",
    tradingName: "Perionyx Properties",
    entityType: "subsidiary",
    countryOfIncorporation: "United States",
    taxId: "US-34-5678901",
    registrationNumber: "DE-665544",
    functionalCurrency: "USD",
    consolidationMethod: "full",
    isConsolidated: true,
    consolidationScope: "full",
    fiscalYearEnd: "12-31",
    fiscalPeriod: 7,
    address: "750 Park Avenue",
    city: "New York",
    country: "United States",
    status: "active",
    parentEntityId: "entity-holding",
    subsidiaries: [],
    createdById: "user-admin",
    companyId: COMPANY,
    createdAt: daysAgo(900),
    updatedAt: daysAgo(15),
  };

  const india: LegalEntity = {
    id: "entity-india",
    entityCode: "PSI-10",
    legalName: "Perionyx Services India Branch",
    tradingName: "Perionyx India",
    entityType: "branch",
    countryOfIncorporation: "India",
    taxId: "IN-36AABCP1234D1ZV",
    registrationNumber: "CIN-U72900KA2020FTC123456",
    functionalCurrency: "INR",
    consolidationMethod: "full",
    isConsolidated: true,
    consolidationScope: "full",
    fiscalYearEnd: "03-31",
    fiscalPeriod: 7,
    address: "91 MG Road, Ashok Nagar",
    city: "Bangalore",
    country: "India",
    status: "active",
    parentEntityId: "entity-parent",
    subsidiaries: [],
    createdById: "user-admin",
    companyId: COMPANY,
    createdAt: daysAgo(200),
    updatedAt: daysAgo(3),
  };

  const entities: LegalEntity[] = [
    holding, parent, eu, uk, asia, china, latam, ventures, innovations, properties, india,
  ];
  for (const e of entities) svc.entityManagement.add(e);

  // =========================================================================
  // 2. Ownership Records
  // =========================================================================
  const ownerships: OwnershipRecord[] = [
    {
      id: "own-holding-parent",
      parentEntityId: "entity-holding",
      subsidiaryEntityId: "entity-parent",
      ownershipType: "direct",
      ownershipPercentage: 100,
      votingPercentage: 100,
      effectiveDate: daysAgo(1095),
      consolidationMethod: "full",
      goodwillAmount: 0,
      fairValueAdjustments: 0,
      acquisitionDate: daysAgo(1095),
      considerationTransferred: 500000000,
      isDirect: true,
      consolidationScope: "full",
      companyId: COMPANY,
      createdAt: daysAgo(1095),
      updatedAt: daysAgo(30),
    },
    {
      id: "own-parent-eu",
      parentEntityId: "entity-parent",
      subsidiaryEntityId: "entity-eu",
      ownershipType: "direct",
      ownershipPercentage: 100,
      votingPercentage: 100,
      effectiveDate: daysAgo(730),
      consolidationMethod: "full",
      goodwillAmount: 2500000,
      fairValueAdjustments: 500000,
      acquisitionDate: daysAgo(730),
      considerationTransferred: 25000000,
      isDirect: true,
      consolidationScope: "full",
      companyId: COMPANY,
      createdAt: daysAgo(730),
      updatedAt: daysAgo(14),
    },
    {
      id: "own-parent-uk",
      parentEntityId: "entity-parent",
      subsidiaryEntityId: "entity-uk",
      ownershipType: "direct",
      ownershipPercentage: 100,
      votingPercentage: 100,
      effectiveDate: daysAgo(640),
      consolidationMethod: "full",
      goodwillAmount: 1800000,
      fairValueAdjustments: 300000,
      acquisitionDate: daysAgo(640),
      considerationTransferred: 18000000,
      isDirect: true,
      consolidationScope: "full",
      companyId: COMPANY,
      createdAt: daysAgo(640),
      updatedAt: daysAgo(10),
    },
    {
      id: "own-parent-asia",
      parentEntityId: "entity-parent",
      subsidiaryEntityId: "entity-asia",
      ownershipType: "direct",
      ownershipPercentage: 85,
      votingPercentage: 85,
      effectiveDate: daysAgo(500),
      consolidationMethod: "full",
      goodwillAmount: 3200000,
      fairValueAdjustments: 800000,
      acquisitionDate: daysAgo(500),
      considerationTransferred: 17000000,
      isDirect: true,
      consolidationScope: "full",
      companyId: COMPANY,
      createdAt: daysAgo(500),
      updatedAt: daysAgo(8),
    },
    {
      id: "own-asia-china",
      parentEntityId: "entity-asia",
      subsidiaryEntityId: "entity-china",
      ownershipType: "direct",
      ownershipPercentage: 70,
      votingPercentage: 70,
      effectiveDate: daysAgo(365),
      consolidationMethod: "full",
      goodwillAmount: 1500000,
      fairValueAdjustments: 400000,
      acquisitionDate: daysAgo(365),
      considerationTransferred: 8500000,
      isDirect: true,
      ultimateParentId: "entity-parent",
      consolidationScope: "full",
      companyId: COMPANY,
      createdAt: daysAgo(365),
      updatedAt: daysAgo(5),
    },
    {
      id: "own-parent-china-indirect",
      parentEntityId: "entity-parent",
      subsidiaryEntityId: "entity-china",
      ownershipType: "indirect",
      ownershipPercentage: 59.5,
      votingPercentage: 59.5,
      effectiveDate: daysAgo(365),
      consolidationMethod: "full",
      acquisitionDate: daysAgo(365),
      isDirect: false,
      ultimateParentId: "entity-parent",
      consolidationScope: "full",
      companyId: COMPANY,
      createdAt: daysAgo(365),
      updatedAt: daysAgo(5),
    },
    {
      id: "own-parent-latam",
      parentEntityId: "entity-parent",
      subsidiaryEntityId: "entity-latam",
      ownershipType: "direct",
      ownershipPercentage: 90,
      votingPercentage: 90,
      effectiveDate: daysAgo(300),
      consolidationMethod: "full",
      goodwillAmount: 1200000,
      fairValueAdjustments: 200000,
      acquisitionDate: daysAgo(300),
      considerationTransferred: 9500000,
      isDirect: true,
      consolidationScope: "full",
      companyId: COMPANY,
      createdAt: daysAgo(300),
      updatedAt: daysAgo(5),
    },
    {
      id: "own-holding-ventures",
      parentEntityId: "entity-holding",
      subsidiaryEntityId: "entity-ventures",
      ownershipType: "direct",
      ownershipPercentage: 35,
      votingPercentage: 35,
      effectiveDate: daysAgo(540),
      consolidationMethod: "equity",
      goodwillAmount: 4000000,
      fairValueAdjustments: 1200000,
      acquisitionDate: daysAgo(540),
      considerationTransferred: 15000000,
      isDirect: true,
      consolidationScope: "equity",
      companyId: COMPANY,
      createdAt: daysAgo(540),
      updatedAt: daysAgo(20),
    },
    {
      id: "own-holding-innovations",
      parentEntityId: "entity-holding",
      subsidiaryEntityId: "entity-innovations",
      ownershipType: "direct",
      ownershipPercentage: 50,
      votingPercentage: 50,
      effectiveDate: daysAgo(180),
      consolidationMethod: "equity",
      goodwillAmount: 6000000,
      fairValueAdjustments: 2000000,
      acquisitionDate: daysAgo(180),
      considerationTransferred: 25000000,
      isDirect: true,
      consolidationScope: "equity",
      companyId: COMPANY,
      createdAt: daysAgo(180),
      updatedAt: daysAgo(10),
    },
    {
      id: "own-holding-properties",
      parentEntityId: "entity-holding",
      subsidiaryEntityId: "entity-properties",
      ownershipType: "direct",
      ownershipPercentage: 100,
      votingPercentage: 100,
      effectiveDate: daysAgo(900),
      consolidationMethod: "full",
      goodwillAmount: 0,
      fairValueAdjustments: 0,
      acquisitionDate: daysAgo(900),
      considerationTransferred: 75000000,
      isDirect: true,
      consolidationScope: "full",
      companyId: COMPANY,
      createdAt: daysAgo(900),
      updatedAt: daysAgo(15),
    },
    {
      id: "own-parent-india",
      parentEntityId: "entity-parent",
      subsidiaryEntityId: "entity-india",
      ownershipType: "direct",
      ownershipPercentage: 100,
      votingPercentage: 100,
      effectiveDate: daysAgo(200),
      consolidationMethod: "full",
      goodwillAmount: 500000,
      fairValueAdjustments: 100000,
      acquisitionDate: daysAgo(200),
      considerationTransferred: 5000000,
      isDirect: true,
      consolidationScope: "full",
      companyId: COMPANY,
      createdAt: daysAgo(200),
      updatedAt: daysAgo(3),
    },
  ];
  for (const o of ownerships) svc.ownership.add(o);

  // =========================================================================
  // 3. Consolidation Run (July 2026 month-end)
  // =========================================================================
  const consEntities = ["entity-eu", "entity-uk", "entity-asia", "entity-china", "entity-latam", "entity-india", "entity-properties"];
  const consEntitiesCompleted = ["entity-eu", "entity-uk", "entity-properties", "entity-india", "entity-latam"];
  const consRun: ConsolidationRun = {
    id: "cons-run-2026-07",
    periodId: "period-2026-07",
    runType: "monthly",
    fiscalYear: 2026,
    fiscalPeriod: 7,
    label: "Close monthly 2026-P7",
    status: "translation",
    startDate: daysAgo(5),
    currency: "USD",
    entitiesIncluded: consEntities,
    entitiesCompleted: consEntitiesCompleted,
    totalSteps: 7,
    completedSteps: 3,
    hasTranslationRun: true,
    hasEliminationsRun: false,
    hasMinorityInterest: false,
    hasAdjustments: false,
    hasFinancialStatements: false,
    companyId: COMPANY,
    createdAt: daysAgo(5),
    updatedAt: daysAgo(1),
  };
  svc.consolidationEngine.add(consRun);

  // =========================================================================
  // 4. Currency Translation Runs (6 source currencies -> USD)
  // =========================================================================
  const eurRun: CurrencyTranslationRun = {
    id: "trans-eur-usd",
    consolidationRunId: "cons-run-2026-07",
    periodId: "period-2026-07",
    sourceCurrency: "EUR",
    targetCurrency: "USD",
    translationMethod: "average",
    averageRate: 1.0825,
    closingRate: 1.0910,
    historicalRates: [
      { id: "hr-eur-avg", translationRunId: "trans-eur-usd", accountCategory: "revenue_expenses", rate: 1.0825, rateType: "average", effectiveDate: daysAgo(30) },
      { id: "hr-eur-cls", translationRunId: "trans-eur-usd", accountCategory: "monetary", rate: 1.0910, rateType: "closing", effectiveDate: NOW },
      { id: "hr-eur-hist", translationRunId: "trans-eur-usd", accountCategory: "equity", rate: 1.1500, rateType: "historical", effectiveDate: daysAgo(730) },
    ],
    status: "completed",
    ctaAmount: 238000,
    translatedBy: "user-consolidator",
    reviewedById: "user-reviewer",
    companyId: COMPANY,
    createdAt: daysAgo(3),
    updatedAt: daysAgo(1),
  };

  const gbpRun: CurrencyTranslationRun = {
    id: "trans-gbp-usd",
    consolidationRunId: "cons-run-2026-07",
    periodId: "period-2026-07",
    sourceCurrency: "GBP",
    targetCurrency: "USD",
    translationMethod: "average",
    averageRate: 1.2640,
    closingRate: 1.2780,
    historicalRates: [
      { id: "hr-gbp-avg", translationRunId: "trans-gbp-usd", accountCategory: "revenue_expenses", rate: 1.2640, rateType: "average", effectiveDate: daysAgo(30) },
      { id: "hr-gbp-cls", translationRunId: "trans-gbp-usd", accountCategory: "monetary", rate: 1.2780, rateType: "closing", effectiveDate: NOW },
      { id: "hr-gbp-hist", translationRunId: "trans-gbp-usd", accountCategory: "equity", rate: 1.3200, rateType: "historical", effectiveDate: daysAgo(640) },
    ],
    status: "completed",
    ctaAmount: 182000,
    translatedBy: "user-consolidator",
    reviewedById: "user-reviewer",
    companyId: COMPANY,
    createdAt: daysAgo(3),
    updatedAt: daysAgo(1),
  };

  const sgdRun: CurrencyTranslationRun = {
    id: "trans-sgd-usd",
    consolidationRunId: "cons-run-2026-07",
    periodId: "period-2026-07",
    sourceCurrency: "SGD",
    targetCurrency: "USD",
    translationMethod: "average",
    averageRate: 0.7410,
    closingRate: 0.7480,
    historicalRates: [
      { id: "hr-sgd-avg", translationRunId: "trans-sgd-usd", accountCategory: "revenue_expenses", rate: 0.7410, rateType: "average", effectiveDate: daysAgo(30) },
      { id: "hr-sgd-cls", translationRunId: "trans-sgd-usd", accountCategory: "monetary", rate: 0.7480, rateType: "closing", effectiveDate: NOW },
      { id: "hr-sgd-hist", translationRunId: "trans-sgd-usd", accountCategory: "equity", rate: 0.7400, rateType: "historical", effectiveDate: daysAgo(500) },
    ],
    status: "completed",
    ctaAmount: 65800,
    translatedBy: "user-consolidator",
    reviewedById: "user-reviewer",
    companyId: COMPANY,
    createdAt: daysAgo(3),
    updatedAt: daysAgo(1),
  };

  const cnyRun: CurrencyTranslationRun = {
    id: "trans-cny-usd",
    consolidationRunId: "cons-run-2026-07",
    periodId: "period-2026-07",
    sourceCurrency: "CNY",
    targetCurrency: "USD",
    translationMethod: "average",
    averageRate: 0.1375,
    closingRate: 0.1390,
    historicalRates: [
      { id: "hr-cny-avg", translationRunId: "trans-cny-usd", accountCategory: "revenue_expenses", rate: 0.1375, rateType: "average", effectiveDate: daysAgo(30) },
      { id: "hr-cny-cls", translationRunId: "trans-cny-usd", accountCategory: "monetary", rate: 0.1390, rateType: "closing", effectiveDate: NOW },
      { id: "hr-cny-hist", translationRunId: "trans-cny-usd", accountCategory: "equity", rate: 0.1380, rateType: "historical", effectiveDate: daysAgo(365) },
    ],
    status: "inProgress",
    ctaAmount: 41200,
    translatedBy: "user-consolidator",
    companyId: COMPANY,
    createdAt: daysAgo(2),
    updatedAt: daysAgo(0),
  };

  const brlRun: CurrencyTranslationRun = {
    id: "trans-brl-usd",
    consolidationRunId: "cons-run-2026-07",
    periodId: "period-2026-07",
    sourceCurrency: "BRL",
    targetCurrency: "USD",
    translationMethod: "average",
    averageRate: 0.1800,
    closingRate: 0.1835,
    historicalRates: [
      { id: "hr-brl-avg", translationRunId: "trans-brl-usd", accountCategory: "revenue_expenses", rate: 0.1800, rateType: "average", effectiveDate: daysAgo(30) },
      { id: "hr-brl-cls", translationRunId: "trans-brl-usd", accountCategory: "monetary", rate: 0.1835, rateType: "closing", effectiveDate: NOW },
      { id: "hr-brl-hist", translationRunId: "trans-brl-usd", accountCategory: "equity", rate: 0.1950, rateType: "historical", effectiveDate: daysAgo(300) },
    ],
    status: "completed",
    ctaAmount: 124500,
    translatedBy: "user-consolidator",
    reviewedById: "user-reviewer",
    companyId: COMPANY,
    createdAt: daysAgo(3),
    updatedAt: daysAgo(1),
  };

  const inrRun: CurrencyTranslationRun = {
    id: "trans-inr-usd",
    consolidationRunId: "cons-run-2026-07",
    periodId: "period-2026-07",
    sourceCurrency: "INR",
    targetCurrency: "USD",
    translationMethod: "average",
    averageRate: 0.0120,
    closingRate: 0.0122,
    historicalRates: [
      { id: "hr-inr-avg", translationRunId: "trans-inr-usd", accountCategory: "revenue_expenses", rate: 0.0120, rateType: "average", effectiveDate: daysAgo(30) },
      { id: "hr-inr-cls", translationRunId: "trans-inr-usd", accountCategory: "monetary", rate: 0.0122, rateType: "closing", effectiveDate: NOW },
      { id: "hr-inr-hist", translationRunId: "trans-inr-usd", accountCategory: "equity", rate: 0.0120, rateType: "historical", effectiveDate: daysAgo(200) },
    ],
    status: "draft",
    ctaAmount: 18500,
    translatedBy: "user-consolidator",
    companyId: COMPANY,
    createdAt: daysAgo(1),
    updatedAt: daysAgo(0),
  };

  const allTranslations = [eurRun, gbpRun, sgdRun, cnyRun, brlRun, inrRun];
  for (const t of allTranslations) svc.currencyTranslation.add(t);

  // =========================================================================
  // 5. Intercompany Records (14 transactions)
  // =========================================================================
  const icRecords: IntercompanyRecord[] = [
    {
      id: "ic-sales-eu-uk-01",
      consolidationRunId: "cons-run-2026-07",
      periodId: "period-2026-07",
      intercompanyType: "sales",
      status: "identified",
      fromEntityId: "entity-eu",
      toEntityId: "entity-uk",
      fromAmount: 850000,
      toAmount: 782000,
      difference: 68000,
      currency: "USD",
      eliminationAmount: 0,
      notes: "EU software license sales to UK. Rate difference at recognition.",
      createdBy: "user-consolidator",
      companyId: COMPANY,
      createdAt: daysAgo(4),
      updatedAt: daysAgo(4),
    },
    {
      id: "ic-sales-uk-eu-02",
      consolidationRunId: "cons-run-2026-07",
      periodId: "period-2026-07",
      intercompanyType: "sales",
      status: "identified",
      fromEntityId: "entity-uk",
      toEntityId: "entity-eu",
      fromAmount: 420000,
      toAmount: 420000,
      difference: 0,
      currency: "USD",
      eliminationAmount: 0,
      notes: "UK consulting services to EU. Matched.",
      createdBy: "user-consolidator",
      companyId: COMPANY,
      createdAt: daysAgo(4),
      updatedAt: daysAgo(4),
    },
    {
      id: "ic-loan-parent-eu-03",
      consolidationRunId: "cons-run-2026-07",
      periodId: "period-2026-07",
      intercompanyType: "loans",
      status: "matched",
      fromEntityId: "entity-parent",
      toEntityId: "entity-eu",
      fromAmount: 5000000,
      toAmount: 5000000,
      difference: 0,
      currency: "USD",
      eliminationAmount: 5000000,
      notes: "Intercompany loan to EU subsidiary for working capital.",
      createdBy: "user-consolidator",
      companyId: COMPANY,
      createdAt: daysAgo(4),
      updatedAt: daysAgo(2),
    },
    {
      id: "ic-interest-eu-parent-04",
      consolidationRunId: "cons-run-2026-07",
      periodId: "period-2026-07",
      intercompanyType: "interest",
      status: "unmatched",
      fromEntityId: "entity-eu",
      toEntityId: "entity-parent",
      fromAmount: 42500,
      toAmount: 41200,
      difference: 1300,
      currency: "USD",
      eliminationAmount: 0,
      notes: "Monthly interest on intercompany loan. Timing difference.",
      createdBy: "user-consolidator",
      companyId: COMPANY,
      createdAt: daysAgo(3),
      updatedAt: daysAgo(3),
    },
    {
      id: "ic-dividends-asia-parent-05",
      consolidationRunId: "cons-run-2026-07",
      periodId: "period-2026-07",
      intercompanyType: "dividends",
      status: "eliminated",
      fromEntityId: "entity-asia",
      toEntityId: "entity-parent",
      fromAmount: 200000,
      toAmount: 200000,
      difference: 0,
      currency: "USD",
      eliminationAmount: 200000,
      eliminationDate: daysAgo(2),
      eliminationJournalId: "gl-elim-div-001",
      notes: "Q2 dividend distribution to parent.",
      createdBy: "user-consolidator",
      approvedById: "user-reviewer",
      approvedAt: daysAgo(2),
      companyId: COMPANY,
      createdAt: daysAgo(3),
      updatedAt: daysAgo(2),
    },
    {
      id: "ic-sales-parent-asia-06",
      consolidationRunId: "cons-run-2026-07",
      periodId: "period-2026-07",
      intercompanyType: "sales",
      status: "identified",
      fromEntityId: "entity-parent",
      toEntityId: "entity-asia",
      fromAmount: 1200000,
      toAmount: 1200000,
      difference: 0,
      currency: "USD",
      eliminationAmount: 0,
      notes: "Product license fees charged to Asia entity.",
      createdBy: "user-consolidator",
      companyId: COMPANY,
      createdAt: daysAgo(4),
      updatedAt: daysAgo(4),
    },
    {
      id: "ic-receivables-eu-latam-07",
      consolidationRunId: "cons-run-2026-07",
      periodId: "period-2026-07",
      intercompanyType: "receivables",
      status: "unmatched",
      fromEntityId: "entity-eu",
      toEntityId: "entity-latam",
      fromAmount: 345000,
      toAmount: 310000,
      difference: 35000,
      currency: "USD",
      eliminationAmount: 0,
      notes: "Outstanding receivable from LATAM for EU services. FX variance.",
      createdBy: "user-consolidator",
      companyId: COMPANY,
      createdAt: daysAgo(3),
      updatedAt: daysAgo(3),
    },
    {
      id: "ic-payables-latam-eu-08",
      consolidationRunId: "cons-run-2026-07",
      periodId: "period-2026-07",
      intercompanyType: "payables",
      status: "unmatched",
      fromEntityId: "entity-latam",
      toEntityId: "entity-eu",
      fromAmount: 310000,
      toAmount: 345000,
      difference: -35000,
      currency: "USD",
      eliminationAmount: 0,
      notes: "Mirror payable entry for EU receivable. FX difference to reconcile.",
      createdBy: "user-consolidator",
      companyId: COMPANY,
      createdAt: daysAgo(3),
      updatedAt: daysAgo(3),
    },
    {
      id: "ic-sales-parent-uk-09",
      consolidationRunId: "cons-run-2026-07",
      periodId: "period-2026-07",
      intercompanyType: "sales",
      status: "matched",
      fromEntityId: "entity-parent",
      toEntityId: "entity-uk",
      fromAmount: 650000,
      toAmount: 650000,
      difference: 0,
      currency: "USD",
      eliminationAmount: 650000,
      notes: "Management fee charged to UK entity.",
      createdBy: "user-consolidator",
      companyId: COMPANY,
      createdAt: daysAgo(4),
      updatedAt: daysAgo(2),
    },
    {
      id: "ic-loan-parent-china-10",
      consolidationRunId: "cons-run-2026-07",
      periodId: "period-2026-07",
      intercompanyType: "loans",
      status: "identified",
      fromEntityId: "entity-parent",
      toEntityId: "entity-china",
      fromAmount: 2000000,
      toAmount: 1985000,
      difference: 15000,
      currency: "USD",
      eliminationAmount: 0,
      notes: "Working capital loan to China subsidiary. Origination fee difference.",
      createdBy: "user-consolidator",
      companyId: COMPANY,
      createdAt: daysAgo(4),
      updatedAt: daysAgo(4),
    },
    {
      id: "ic-purchases-uk-eu-11",
      consolidationRunId: "cons-run-2026-07",
      periodId: "period-2026-07",
      intercompanyType: "purchases",
      status: "identified",
      fromEntityId: "entity-eu",
      toEntityId: "entity-uk",
      fromAmount: 380000,
      toAmount: 380000,
      difference: 0,
      currency: "USD",
      eliminationAmount: 0,
      notes: "EU data center services purchased by UK.",
      createdBy: "user-consolidator",
      companyId: COMPANY,
      createdAt: daysAgo(4),
      updatedAt: daysAgo(4),
    },
    {
      id: "ic-interest-uk-parent-12",
      consolidationRunId: "cons-run-2026-07",
      periodId: "period-2026-07",
      intercompanyType: "interest",
      status: "matched",
      fromEntityId: "entity-uk",
      toEntityId: "entity-parent",
      fromAmount: 22500,
      toAmount: 22500,
      difference: 0,
      currency: "USD",
      eliminationAmount: 22500,
      notes: "Monthly interest on parent loan to UK.",
      createdBy: "user-consolidator",
      companyId: COMPANY,
      createdAt: daysAgo(3),
      updatedAt: daysAgo(2),
    },
    {
      id: "ic-dividends-eu-parent-13",
      consolidationRunId: "cons-run-2026-07",
      periodId: "period-2026-07",
      intercompanyType: "dividends",
      status: "eliminated",
      fromEntityId: "entity-eu",
      toEntityId: "entity-parent",
      fromAmount: 350000,
      toAmount: 350000,
      difference: 0,
      currency: "USD",
      eliminationAmount: 350000,
      eliminationDate: daysAgo(2),
      eliminationJournalId: "gl-elim-div-002",
      notes: "Q2 dividend from EU subsidiary.",
      createdBy: "user-consolidator",
      approvedById: "user-reviewer",
      approvedAt: daysAgo(2),
      companyId: COMPANY,
      createdAt: daysAgo(3),
      updatedAt: daysAgo(2),
    },
    {
      id: "ic-inventoryprofit-asia-china-14",
      consolidationRunId: "cons-run-2026-07",
      periodId: "period-2026-07",
      intercompanyType: "inventoryProfit",
      status: "identified",
      fromEntityId: "entity-asia",
      toEntityId: "entity-china",
      fromAmount: 185000,
      toAmount: 178000,
      difference: 7000,
      currency: "USD",
      eliminationAmount: 0,
      notes: "Unrealized profit in inventory from Asia to China. Markup 15%.",
      createdBy: "user-consolidator",
      companyId: COMPANY,
      createdAt: daysAgo(4),
      updatedAt: daysAgo(4),
    },
  ];
  for (const ic of icRecords) svc.intercompanyEliminations.add(ic);

  // =========================================================================
  // 6. Minority Interest Records
  // =========================================================================
  const minorityRecords: MinorityInterestRecord[] = [
    {
      id: "mi-asia-2026-07",
      consolidationRunId: "cons-run-2026-07",
      periodId: "period-2026-07",
      entityId: "entity-asia",
      entityName: "Perionyx Asia Pte Ltd",
      minorityPercentage: 15,
      totalEquity: 22000000,
      minorityEquity: 3300000,
      totalNetIncome: 4800000,
      minorityNetIncome: 720000,
      beginningBalance: 3100000,
      endingBalance: 3820000,
      dividendsPaid: 200000,
      currency: "USD",
      companyId: COMPANY,
      createdAt: daysAgo(2),
      updatedAt: daysAgo(1),
    },
    {
      id: "mi-china-2026-07",
      consolidationRunId: "cons-run-2026-07",
      periodId: "period-2026-07",
      entityId: "entity-china",
      entityName: "Perionyx China Co Ltd",
      minorityPercentage: 30,
      totalEquity: 10500000,
      minorityEquity: 3150000,
      totalNetIncome: 2200000,
      minorityNetIncome: 660000,
      beginningBalance: 2900000,
      endingBalance: 3560000,
      dividendsPaid: 0,
      currency: "USD",
      companyId: COMPANY,
      createdAt: daysAgo(2),
      updatedAt: daysAgo(1),
    },
  ];
  for (const mi of minorityRecords) svc.minorityInterest.add(mi);

  // =========================================================================
  // 7. Equity Accounting Records (JV and Associate)
  // =========================================================================
  const equityRecords: EquityAccountRecord[] = [
    {
      id: "eq-ventures-2026-07",
      consolidationRunId: "cons-run-2026-07",
      periodId: "period-2026-07",
      entityId: "entity-ventures",
      investmentCost: 15000000,
      equityShare: 4200000,
      goodwill: 4000000,
      fairValueAdjustment: 1200000,
      postAcquisitionReserves: 850000,
      carryingAmount: 25250000,
      currency: "USD",
      companyId: COMPANY,
      createdAt: daysAgo(2),
      updatedAt: daysAgo(1),
    },
    {
      id: "eq-innovations-2026-07",
      consolidationRunId: "cons-run-2026-07",
      periodId: "period-2026-07",
      entityId: "entity-innovations",
      investmentCost: 25000000,
      equityShare: 9500000,
      goodwill: 6000000,
      fairValueAdjustment: 2000000,
      postAcquisitionReserves: 1200000,
      carryingAmount: 43700000,
      currency: "USD",
      companyId: COMPANY,
      createdAt: daysAgo(2),
      updatedAt: daysAgo(1),
    },
  ];
  for (const eq of equityRecords) svc.equityAccounting.add(eq);

  // =========================================================================
  // 8. Consolidation Adjustments
  // =========================================================================
  const adjustments: ConsolidationAdjustment[] = [
    {
      id: "adj-fv-eu-001",
      consolidationRunId: "cons-run-2026-07",
      periodId: "period-2026-07",
      adjustmentType: "fairValue",
      status: "posted",
      description: "Fair value uplift on EU property - additional depreciation",
      amount: 125000,
      debitAccount: "6500-Depreciation",
      creditAccount: "2100-Accumulated Depreciation",
      entityId: "entity-eu",
      currency: "USD",
      fxRate: 1.0825,
      glJournalId: "gl-adj-fv-001",
      createdBy: "user-consolidator",
      reviewedById: "user-reviewer",
      approvedById: "user-manager",
      postedDate: daysAgo(2),
      companyId: COMPANY,
      createdAt: daysAgo(4),
      updatedAt: daysAgo(2),
    },
    {
      id: "adj-gw-asia-002",
      consolidationRunId: "cons-run-2026-07",
      periodId: "period-2026-07",
      adjustmentType: "goodwill",
      status: "approved",
      description: "Goodwill impairment on Asia subsidiary",
      amount: 450000,
      debitAccount: "6800-Goodwill Impairment",
      creditAccount: "1100-Goodwill",
      entityId: "entity-asia",
      currency: "USD",
      fxRate: 1,
      glJournalId: "gl-adj-gw-002",
      createdBy: "user-consolidator",
      reviewedById: "user-reviewer",
      approvedById: "user-manager",
      companyId: COMPANY,
      createdAt: daysAgo(3),
      updatedAt: daysAgo(1),
    },
    {
      id: "adj-err-eu-003",
      consolidationRunId: "cons-run-2026-07",
      periodId: "period-2026-07",
      adjustmentType: "errorCorrection",
      status: "draft",
      description: "Correction of intercompany accrual reversal - period mismatch",
      amount: 87500,
      debitAccount: "4000-Receivables",
      creditAccount: "6000-IC Income",
      entityId: "entity-eu",
      currency: "USD",
      fxRate: 1.0825,
      createdBy: "user-consolidator",
      companyId: COMPANY,
      createdAt: daysAgo(1),
      updatedAt: daysAgo(1),
    },
    {
      id: "adj-pp-uk-004",
      consolidationRunId: "cons-run-2026-07",
      periodId: "period-2026-07",
      adjustmentType: "purchasePriceAllocation",
      status: "review",
      description: "PPA adjustment - intangible asset amortization for UK acquisition",
      amount: 220000,
      debitAccount: "6600-Amortization",
      creditAccount: "1150-Intangible Assets",
      entityId: "entity-uk",
      currency: "USD",
      fxRate: 1.2640,
      createdBy: "user-consolidator",
      reviewedById: "user-reviewer",
      companyId: COMPANY,
      createdAt: daysAgo(2),
      updatedAt: daysAgo(1),
    },
  ];
  for (const a of adjustments) svc.consolidationAdjustments.add(a);

  // =========================================================================
  // 9. Financial Statements (BS, IS, CF)
  // =========================================================================
  const bsEntries: FinancialStatementEntry[] = [
    { id: "bs-entry-01", consolidationRunId: "cons-run-2026-07", periodId: "period-2026-07", statementType: "balanceSheet", lineItem: "Cash and Cash Equivalents", amount: 42500000, currency: "USD", sortOrder: 10, section: "assets", isTotal: false, isCalculated: false, companyId: COMPANY, createdAt: NOW },
    { id: "bs-entry-02", consolidationRunId: "cons-run-2026-07", periodId: "period-2026-07", statementType: "balanceSheet", lineItem: "Accounts Receivable", amount: 18200000, currency: "USD", sortOrder: 20, section: "assets", isTotal: false, isCalculated: false, companyId: COMPANY, createdAt: NOW },
    { id: "bs-entry-03", consolidationRunId: "cons-run-2026-07", periodId: "period-2026-07", statementType: "balanceSheet", lineItem: "Inventory", amount: 9800000, currency: "USD", sortOrder: 30, section: "assets", isTotal: false, isCalculated: false, companyId: COMPANY, createdAt: NOW },
    { id: "bs-entry-04", consolidationRunId: "cons-run-2026-07", periodId: "period-2026-07", statementType: "balanceSheet", lineItem: "Intercompany Receivables", amount: 7800000, currency: "USD", sortOrder: 40, section: "assets", isTotal: false, isCalculated: false, companyId: COMPANY, createdAt: NOW },
    { id: "bs-entry-05", consolidationRunId: "cons-run-2026-07", periodId: "period-2026-07", statementType: "balanceSheet", lineItem: "Property, Plant & Equipment", amount: 52000000, currency: "USD", sortOrder: 50, section: "assets", isTotal: false, isCalculated: false, companyId: COMPANY, createdAt: NOW },
    { id: "bs-entry-06", consolidationRunId: "cons-run-2026-07", periodId: "period-2026-07", statementType: "balanceSheet", lineItem: "Goodwill", amount: 18700000, currency: "USD", sortOrder: 60, section: "assets", isTotal: false, isCalculated: false, companyId: COMPANY, createdAt: NOW },
    { id: "bs-entry-07", consolidationRunId: "cons-run-2026-07", periodId: "period-2026-07", statementType: "balanceSheet", lineItem: "Intangible Assets", amount: 8500000, currency: "USD", sortOrder: 70, section: "assets", isTotal: false, isCalculated: false, companyId: COMPANY, createdAt: NOW },
    { id: "bs-entry-08", consolidationRunId: "cons-run-2026-07", periodId: "period-2026-07", statementType: "balanceSheet", lineItem: "Investments in Associates", amount: 25250000, currency: "USD", sortOrder: 80, section: "assets", isTotal: false, isCalculated: false, companyId: COMPANY, createdAt: NOW },
    { id: "bs-entry-09", consolidationRunId: "cons-run-2026-07", periodId: "period-2026-07", statementType: "balanceSheet", lineItem: "Other Assets", amount: 4300000, currency: "USD", sortOrder: 90, section: "assets", isTotal: false, isCalculated: false, companyId: COMPANY, createdAt: NOW },
    { id: "bs-entry-10", consolidationRunId: "cons-run-2026-07", periodId: "period-2026-07", statementType: "balanceSheet", lineItem: "Total Assets", amount: 187000000, currency: "USD", sortOrder: 100, section: "assets", isTotal: true, isCalculated: true, companyId: COMPANY, createdAt: NOW },

    { id: "bs-entry-11", consolidationRunId: "cons-run-2026-07", periodId: "period-2026-07", statementType: "balanceSheet", lineItem: "Accounts Payable", amount: 14500000, currency: "USD", sortOrder: 110, section: "liabilities", isTotal: false, isCalculated: false, companyId: COMPANY, createdAt: NOW },
    { id: "bs-entry-12", consolidationRunId: "cons-run-2026-07", periodId: "period-2026-07", statementType: "balanceSheet", lineItem: "Intercompany Payables", amount: 7800000, currency: "USD", sortOrder: 120, section: "liabilities", isTotal: false, isCalculated: false, companyId: COMPANY, createdAt: NOW },
    { id: "bs-entry-13", consolidationRunId: "cons-run-2026-07", periodId: "period-2026-07", statementType: "balanceSheet", lineItem: "Short-term Debt", amount: 8500000, currency: "USD", sortOrder: 130, section: "liabilities", isTotal: false, isCalculated: false, companyId: COMPANY, createdAt: NOW },
    { id: "bs-entry-14", consolidationRunId: "cons-run-2026-07", periodId: "period-2026-07", statementType: "balanceSheet", lineItem: "Long-term Debt", amount: 42000000, currency: "USD", sortOrder: 140, section: "liabilities", isTotal: false, isCalculated: false, companyId: COMPANY, createdAt: NOW },
    { id: "bs-entry-15", consolidationRunId: "cons-run-2026-07", periodId: "period-2026-07", statementType: "balanceSheet", lineItem: "Deferred Tax Liabilities", amount: 5200000, currency: "USD", sortOrder: 150, section: "liabilities", isTotal: false, isCalculated: false, companyId: COMPANY, createdAt: NOW },
    { id: "bs-entry-16", consolidationRunId: "cons-run-2026-07", periodId: "period-2026-07", statementType: "balanceSheet", lineItem: "Other Liabilities", amount: 3200000, currency: "USD", sortOrder: 160, section: "liabilities", isTotal: false, isCalculated: false, companyId: COMPANY, createdAt: NOW },
    { id: "bs-entry-17", consolidationRunId: "cons-run-2026-07", periodId: "period-2026-07", statementType: "balanceSheet", lineItem: "Total Liabilities", amount: 81200000, currency: "USD", sortOrder: 170, section: "liabilities", isTotal: true, isCalculated: true, companyId: COMPANY, createdAt: NOW },

    { id: "bs-entry-18", consolidationRunId: "cons-run-2026-07", periodId: "period-2026-07", statementType: "balanceSheet", lineItem: "Share Capital", amount: 60000000, currency: "USD", sortOrder: 180, section: "equity", isTotal: false, isCalculated: false, companyId: COMPANY, createdAt: NOW },
    { id: "bs-entry-19", consolidationRunId: "cons-run-2026-07", periodId: "period-2026-07", statementType: "balanceSheet", lineItem: "Retained Earnings", amount: 36800000, currency: "USD", sortOrder: 190, section: "equity", isTotal: false, isCalculated: false, companyId: COMPANY, createdAt: NOW },
    { id: "bs-entry-20", consolidationRunId: "cons-run-2026-07", periodId: "period-2026-07", statementType: "balanceSheet", lineItem: "Cumulative Translation Reserve", amount: 2800000, currency: "USD", sortOrder: 200, section: "equity", isTotal: false, isCalculated: false, companyId: COMPANY, createdAt: NOW },
    { id: "bs-entry-21", consolidationRunId: "cons-run-2026-07", periodId: "period-2026-07", statementType: "balanceSheet", lineItem: "Minority Interest", amount: 7380000, currency: "USD", sortOrder: 210, section: "equity", isTotal: false, isCalculated: false, companyId: COMPANY, createdAt: NOW },
    { id: "bs-entry-22", consolidationRunId: "cons-run-2026-07", periodId: "period-2026-07", statementType: "balanceSheet", lineItem: "Total Equity", amount: 106980000, currency: "USD", sortOrder: 220, section: "equity", isTotal: true, isCalculated: true, companyId: COMPANY, createdAt: NOW },
  ];
  const bsSet = svc.financialStatements.generateBalanceSheet(
    "cons-run-2026-07", "period-2026-07", "USD", bsEntries,
  );
  svc.financialStatements.update(bsSet.id, {
    totalAssets: 187000000,
    totalLiabilities: 81200000,
    totalEquity: 106980000,
    beginningCash: 38500000,
    endingCash: 42500000,
    isBalanced: true,
  });

  const isEntries: FinancialStatementEntry[] = [
    { id: "is-entry-01", consolidationRunId: "cons-run-2026-07", periodId: "period-2026-07", statementType: "incomeStatement", lineItem: "Product Revenue", amount: 42500000, currency: "USD", sortOrder: 10, section: "revenue", isTotal: false, isCalculated: false, companyId: COMPANY, createdAt: NOW },
    { id: "is-entry-02", consolidationRunId: "cons-run-2026-07", periodId: "period-2026-07", statementType: "incomeStatement", lineItem: "Service Revenue", amount: 18200000, currency: "USD", sortOrder: 20, section: "revenue", isTotal: false, isCalculated: false, companyId: COMPANY, createdAt: NOW },
    { id: "is-entry-03", consolidationRunId: "cons-run-2026-07", periodId: "period-2026-07", statementType: "incomeStatement", lineItem: "License Revenue", amount: 7800000, currency: "USD", sortOrder: 30, section: "revenue", isTotal: false, isCalculated: false, companyId: COMPANY, createdAt: NOW },
    { id: "is-entry-04", consolidationRunId: "cons-run-2026-07", periodId: "period-2026-07", statementType: "incomeStatement", lineItem: "Total Revenue", amount: 68500000, currency: "USD", sortOrder: 40, section: "revenue", isTotal: true, isCalculated: true, companyId: COMPANY, createdAt: NOW },

    { id: "is-entry-05", consolidationRunId: "cons-run-2026-07", periodId: "period-2026-07", statementType: "incomeStatement", lineItem: "Cost of Goods Sold", amount: 22500000, currency: "USD", sortOrder: 50, section: "expenses", isTotal: false, isCalculated: false, companyId: COMPANY, createdAt: NOW },
    { id: "is-entry-06", consolidationRunId: "cons-run-2026-07", periodId: "period-2026-07", statementType: "incomeStatement", lineItem: "Sales & Marketing", amount: 8500000, currency: "USD", sortOrder: 60, section: "expenses", isTotal: false, isCalculated: false, companyId: COMPANY, createdAt: NOW },
    { id: "is-entry-07", consolidationRunId: "cons-run-2026-07", periodId: "period-2026-07", statementType: "incomeStatement", lineItem: "Research & Development", amount: 12000000, currency: "USD", sortOrder: 70, section: "expenses", isTotal: false, isCalculated: false, companyId: COMPANY, createdAt: NOW },
    { id: "is-entry-08", consolidationRunId: "cons-run-2026-07", periodId: "period-2026-07", statementType: "incomeStatement", lineItem: "General & Administrative", amount: 6500000, currency: "USD", sortOrder: 80, section: "expenses", isTotal: false, isCalculated: false, companyId: COMPANY, createdAt: NOW },
    { id: "is-entry-09", consolidationRunId: "cons-run-2026-07", periodId: "period-2026-07", statementType: "incomeStatement", lineItem: "Depreciation & Amortization", amount: 4200000, currency: "USD", sortOrder: 90, section: "expenses", isTotal: false, isCalculated: false, companyId: COMPANY, createdAt: NOW },
    { id: "is-entry-10", consolidationRunId: "cons-run-2026-07", periodId: "period-2026-07", statementType: "incomeStatement", lineItem: "Total Expenses", amount: 53700000, currency: "USD", sortOrder: 100, section: "expenses", isTotal: true, isCalculated: true, companyId: COMPANY, createdAt: NOW },
  ];
  const isSet = svc.financialStatements.generateIncomeStatement(
    "cons-run-2026-07", "period-2026-07", "USD", isEntries,
  );
  svc.financialStatements.update(isSet.id, {
    totalRevenue: 68500000,
    totalExpenses: 53700000,
    netIncome: 14800000,
  });

  const cfEntries: FinancialStatementEntry[] = [
    { id: "cf-entry-01", consolidationRunId: "cons-run-2026-07", periodId: "period-2026-07", statementType: "cashFlow", lineItem: "Net Income", amount: 14800000, currency: "USD", sortOrder: 10, section: "operating", isTotal: false, isCalculated: false, companyId: COMPANY, createdAt: NOW },
    { id: "cf-entry-02", consolidationRunId: "cons-run-2026-07", periodId: "period-2026-07", statementType: "cashFlow", lineItem: "Depreciation & Amortization", amount: 4200000, currency: "USD", sortOrder: 20, section: "operating", isTotal: false, isCalculated: false, companyId: COMPANY, createdAt: NOW },
    { id: "cf-entry-03", consolidationRunId: "cons-run-2026-07", periodId: "period-2026-07", statementType: "cashFlow", lineItem: "Change in Working Capital", amount: -2100000, currency: "USD", sortOrder: 30, section: "operating", isTotal: false, isCalculated: false, companyId: COMPANY, createdAt: NOW },
    { id: "cf-entry-04", consolidationRunId: "cons-run-2026-07", periodId: "period-2026-07", statementType: "cashFlow", lineItem: "Net Cash from Operations", amount: 16900000, currency: "USD", sortOrder: 40, section: "operating", isTotal: true, isCalculated: true, companyId: COMPANY, createdAt: NOW },

    { id: "cf-entry-05", consolidationRunId: "cons-run-2026-07", periodId: "period-2026-07", statementType: "cashFlow", lineItem: "Purchase of PP&E", amount: -3800000, currency: "USD", sortOrder: 50, section: "investing", isTotal: false, isCalculated: false, companyId: COMPANY, createdAt: NOW },
    { id: "cf-entry-06", consolidationRunId: "cons-run-2026-07", periodId: "period-2026-07", statementType: "cashFlow", lineItem: "Acquisition of Intangibles", amount: -1200000, currency: "USD", sortOrder: 60, section: "investing", isTotal: false, isCalculated: false, companyId: COMPANY, createdAt: NOW },
    { id: "cf-entry-07", consolidationRunId: "cons-run-2026-07", periodId: "period-2026-07", statementType: "cashFlow", lineItem: "Net Cash from Investing", amount: -5000000, currency: "USD", sortOrder: 70, section: "investing", isTotal: true, isCalculated: true, companyId: COMPANY, createdAt: NOW },

    { id: "cf-entry-08", consolidationRunId: "cons-run-2026-07", periodId: "period-2026-07", statementType: "cashFlow", lineItem: "Proceeds from Debt", amount: 3000000, currency: "USD", sortOrder: 80, section: "financing", isTotal: false, isCalculated: false, companyId: COMPANY, createdAt: NOW },
    { id: "cf-entry-09", consolidationRunId: "cons-run-2026-07", periodId: "period-2026-07", statementType: "cashFlow", lineItem: "Dividends Paid", amount: -2200000, currency: "USD", sortOrder: 90, section: "financing", isTotal: false, isCalculated: false, companyId: COMPANY, createdAt: NOW },
    { id: "cf-entry-10", consolidationRunId: "cons-run-2026-07", periodId: "period-2026-07", statementType: "cashFlow", lineItem: "Share Repurchases", amount: -1000000, currency: "USD", sortOrder: 100, section: "financing", isTotal: false, isCalculated: false, companyId: COMPANY, createdAt: NOW },
    { id: "cf-entry-11", consolidationRunId: "cons-run-2026-07", periodId: "period-2026-07", statementType: "cashFlow", lineItem: "Net Cash from Financing", amount: -200000, currency: "USD", sortOrder: 110, section: "financing", isTotal: true, isCalculated: true, companyId: COMPANY, createdAt: NOW },
  ];
  const cfSet = svc.financialStatements.generateCashFlow(
    "cons-run-2026-07", "period-2026-07", "USD", cfEntries,
  );
  svc.financialStatements.update(cfSet.id, {
    cashFromOperations: 16900000,
    cashFromInvesting: -5000000,
    cashFromFinancing: -200000,
    netCashChange: 11700000,
    beginningCash: 30800000,
    endingCash: 42500000,
  });

  // =========================================================================
  // 10. Board Report with sections
  // =========================================================================
  const boardReport: BoardReport = {
    id: "board-2026-07",
    consolidationRunId: "cons-run-2026-07",
    periodId: "period-2026-07",
    title: "Board Report - July 2026 Consolidated Results",
    preparedDate: NOW,
    currency: "USD",
    sections: [],
    executiveSummary: "The Perionyx Group ended July 2026 with consolidated revenue of $68.5M, net income of $14.8M, and total assets of $187.0M. The month-end consolidation is progressing through currency translation, with 5 of 7 entities completed. Minority interest totals $7.38M. Key risks include unmatched intercompany transactions totaling $103,000 and a pending goodwill impairment review for the Asia subsidiary.",
    keyHighlights: [
      "Consolidated revenue of $68.5M up 8.2% year-over-year",
      "Net income margin of 21.6% exceeds budget by 180bps",
      "EU subsidiary achieved record quarterly revenue of $18.2M",
      "Cash position strengthened to $42.5M with positive operating cash flow of $16.9M",
      "Asia Pacific region grew 14% driven by China market expansion",
    ],
    keyRisks: [
      "Unmatched IC transactions totaling $103,000 between EU and LATAM entities",
      "Pending goodwill impairment of $450K for Asia subsidiary",
      "Currency translation exposure: BRL weakening 3.2% in July",
      "China subsidiary loan reconciliation discrepancy of $15K",
    ],
    recommendations: [
      "Complete IC matching for EU-LATAM transactions before month-end close",
      "Approve goodwill impairment assessment for Asia subsidiary",
      "Review hedge effectiveness for BRL exposure",
      "Resolve China loan origination fee discrepancy with counterparty",
    ],
    companyId: COMPANY,
    createdAt: daysAgo(1),
    updatedAt: NOW,
  };

  const section1: BoardReportSection = {
    title: "Financial Performance",
    content: "Consolidated revenue for July 2026 was $68.5M, exceeding budget of $65.0M by 5.4%. Operating expenses of $53.7M were in line with expectations. Net income of $14.8M represents a 21.6% margin, up from 20.1% in the prior period. Revenue growth was driven by strength in EU operations and continued expansion in Asia Pacific markets. The product revenue segment grew 11% year-over-year, while service revenue increased by 6%. License revenue benefited from three new enterprise agreements in the quarter.",
    metrics: [
      { label: "Revenue", value: "$68.5M", trend: "up" },
      { label: "Net Income", value: "$14.8M", trend: "up" },
      { label: "Gross Margin", value: "67.2%", trend: "up" },
      { label: "Net Margin", value: "21.6%", trend: "up" },
      { label: "EBITDA", value: "$19.0M", trend: "up" },
    ],
    charts: [
      {
        type: "bar",
        labels: ["Revenue", "COGS", "Gross Profit", "OpEx", "Net Income"],
        datasets: [{ label: "July 2026 (USD)", data: [68500000, 22500000, 46000000, 31200000, 14800000] }],
      },
      {
        type: "donut",
        labels: ["Product", "Service", "License"],
        datasets: [{ label: "Revenue by Type", data: [42500000, 18200000, 7800000] }],
      },
    ],
  };

  const section2: BoardReportSection = {
    title: "Consolidation Progress",
    content: "The July 2026 month-end consolidation run is currently in the translation phase with 3 of 7 steps completed (43% progress). Five of seven entities have submitted their financial data: EU, UK, Properties, India, and LATAM. Two entities remain pending: Asia and China. Six currency translation runs are in progress covering EUR, GBP, SGD, CNY, BRL, and INR to USD. Intercompany elimination has not yet commenced. Minority interest calculations are pending for Asia (15%) and China (30%).",
    metrics: [
      { label: "Entities Submitted", value: "5/7", trend: "up" },
      { label: "Translation Complete", value: "4/6", trend: "up" },
      { label: "IC Matched", value: "3/14", trend: "stable" },
      { label: "Adjustments Posted", value: "1/4", trend: "down" },
      { label: "Days in Close", value: "5", trend: "stable" },
    ],
  };

  const section3: BoardReportSection = {
    title: "Currency & FX Risk",
    content: "The group has exposure to six non-USD functional currencies. The EUR translation run is complete with a favorable CTA of $238K driven by EUR strengthening from 1.0825 to 1.0910. BRL exposure remains a concern with the Real weakening 3.2% during July. Total unhedged exposure is approximately $45M across all currencies. The cumulative translation reserve stands at $2.8M. The China CNY translation is still in progress with a current CTA estimate of $41K.",
    metrics: [
      { label: "EUR/USD Avg Rate", value: "1.0825", trend: "up" },
      { label: "Total CTA", value: "$670K", trend: "up" },
      { label: "CTA Reserve", value: "$2.8M", trend: "up" },
      { label: "Unhedged Exposure", value: "$45M", trend: "down" },
      { label: "Translations Complete", value: "4/6", trend: "up" },
    ],
  };

  const section4: BoardReportSection = {
    title: "Intercompany & Eliminations",
    content: "Fourteen intercompany transactions have been identified for the period, totaling $13.8M. Three transactions have been matched and two eliminated (dividends from Asia and EU). Two unmatched transactions between EU and LATAM ($35K difference each way) require reconciliation. The parent-to-EU loan of $5M is fully matched. Interest accruals on IC loans are generally consistent with one timing difference of $1,300 on the EU-parent interest entry.",
    metrics: [
      { label: "Total IC Transactions", value: "14", trend: "stable" },
      { label: "Matched", value: "3", trend: "up" },
      { label: "Eliminated", value: "2", trend: "up" },
      { label: "Unmatched", value: "2", trend: "down" },
      { label: "IC Balance", value: "$13.8M", trend: "stable" },
    ],
  };

  const finalReport = svc.boardReporting.add(boardReport);
  svc.boardReporting.addSection(finalReport.id, section1);
  svc.boardReporting.addSection(finalReport.id, section2);
  svc.boardReporting.addSection(finalReport.id, section3);
  svc.boardReporting.addSection(finalReport.id, section4);

  // =========================================================================
  // 11. Management Report Entries (one per consolidated entity)
  // =========================================================================
  const mgmtEntries: ManagementReportEntry[] = [
    {
      id: "mgmt-parent-2026-07",
      consolidationRunId: "cons-run-2026-07",
      periodId: "period-2026-07",
      entityId: "entity-parent",
      entityName: "Perionyx Inc",
      revenue: 28000000,
      expenses: 21500000,
      netIncome: 6500000,
      totalAssets: 78000000,
      totalLiabilities: 34000000,
      equity: 44000000,
      revenueVariance: 1200000,
      expenseVariance: -300000,
      netIncomeVariance: 900000,
      currency: "USD",
      fxRate: 1,
      companyId: COMPANY,
      createdAt: daysAgo(2),
    },
    {
      id: "mgmt-eu-2026-07",
      consolidationRunId: "cons-run-2026-07",
      periodId: "period-2026-07",
      entityId: "entity-eu",
      entityName: "Perionyx BV",
      revenue: 18200000,
      expenses: 13800000,
      netIncome: 4400000,
      totalAssets: 38000000,
      totalLiabilities: 16000000,
      equity: 22000000,
      revenueVariance: 1800000,
      expenseVariance: 400000,
      netIncomeVariance: 1400000,
      currency: "EUR",
      fxRate: 1.0825,
      companyId: COMPANY,
      createdAt: daysAgo(2),
    },
    {
      id: "mgmt-uk-2026-07",
      consolidationRunId: "cons-run-2026-07",
      periodId: "period-2026-07",
      entityId: "entity-uk",
      entityName: "Perionyx UK Ltd",
      revenue: 9500000,
      expenses: 7200000,
      netIncome: 2300000,
      totalAssets: 22000000,
      totalLiabilities: 9500000,
      equity: 12500000,
      revenueVariance: 500000,
      expenseVariance: -100000,
      netIncomeVariance: 400000,
      currency: "GBP",
      fxRate: 1.2640,
      companyId: COMPANY,
      createdAt: daysAgo(2),
    },
    {
      id: "mgmt-asia-2026-07",
      consolidationRunId: "cons-run-2026-07",
      periodId: "period-2026-07",
      entityId: "entity-asia",
      entityName: "Perionyx Asia Pte Ltd",
      revenue: 7200000,
      expenses: 4800000,
      netIncome: 2400000,
      totalAssets: 28000000,
      totalLiabilities: 6000000,
      equity: 22000000,
      revenueVariance: 800000,
      expenseVariance: 200000,
      netIncomeVariance: 600000,
      currency: "SGD",
      fxRate: 0.7410,
      companyId: COMPANY,
      createdAt: daysAgo(2),
    },
    {
      id: "mgmt-china-2026-07",
      consolidationRunId: "cons-run-2026-07",
      periodId: "period-2026-07",
      entityId: "entity-china",
      entityName: "Perionyx China Co Ltd",
      revenue: 3800000,
      expenses: 2700000,
      netIncome: 1100000,
      totalAssets: 15000000,
      totalLiabilities: 4500000,
      equity: 10500000,
      revenueVariance: 600000,
      expenseVariance: 150000,
      netIncomeVariance: 450000,
      currency: "CNY",
      fxRate: 0.1375,
      companyId: COMPANY,
      createdAt: daysAgo(2),
    },
    {
      id: "mgmt-latam-2026-07",
      consolidationRunId: "cons-run-2026-07",
      periodId: "period-2026-07",
      entityId: "entity-latam",
      entityName: "Perionyx LATAM Ltda",
      revenue: 2800000,
      expenses: 2200000,
      netIncome: 600000,
      totalAssets: 9000000,
      totalLiabilities: 4000000,
      equity: 5000000,
      revenueVariance: -200000,
      expenseVariance: 100000,
      netIncomeVariance: -300000,
      currency: "BRL",
      fxRate: 0.1800,
      companyId: COMPANY,
      createdAt: daysAgo(2),
    },
    {
      id: "mgmt-properties-2026-07",
      consolidationRunId: "cons-run-2026-07",
      periodId: "period-2026-07",
      entityId: "entity-properties",
      entityName: "Perionyx Properties LLC",
      revenue: 2200000,
      expenses: 1400000,
      netIncome: 800000,
      totalAssets: 28000000,
      totalLiabilities: 12000000,
      equity: 16000000,
      revenueVariance: 100000,
      expenseVariance: -50000,
      netIncomeVariance: 150000,
      currency: "USD",
      fxRate: 1,
      companyId: COMPANY,
      createdAt: daysAgo(2),
    },
    {
      id: "mgmt-india-2026-07",
      consolidationRunId: "cons-run-2026-07",
      periodId: "period-2026-07",
      entityId: "entity-india",
      entityName: "Perionyx Services India Branch",
      revenue: 1200000,
      expenses: 900000,
      netIncome: 300000,
      totalAssets: 3500000,
      totalLiabilities: 1500000,
      equity: 2000000,
      revenueVariance: 200000,
      expenseVariance: 50000,
      netIncomeVariance: 150000,
      currency: "INR",
      fxRate: 0.0120,
      companyId: COMPANY,
      createdAt: daysAgo(2),
    },
  ];
  for (const m of mgmtEntries) svc.managementReporting.add(m);

  // =========================================================================
  // 12. Alerts
  // =========================================================================
  const alerts: ConsolidationAlert[] = [
    {
      id: "alert-ic-unmatched-eu-latam-001",
      type: "elimination",
      severity: "warning",
      title: "Unmatched IC: receivables EU -> LATAM",
      message: "EU subsidiary has $35K unmatched receivable from LATAM. FX variance detected. entity-eu -> entity-latam: $345K vs $310K recorded.",
      consolidationRunId: "cons-run-2026-07",
      entityId: "entity-eu",
      isRead: false,
      isResolved: false,
      companyId: COMPANY,
      createdAt: daysAgo(1),
    },
    {
      id: "alert-adj-pending-error-003",
      type: "consolidation",
      severity: "info",
      title: "Pending adjustment: IC accrual correction",
      message: "Error correction adjustment for EU intercompany accrual reversal has been in draft for 1 day. Amount: $87,500 USD.",
      consolidationRunId: "cons-run-2026-07",
      entityId: "entity-eu",
      isRead: false,
      isResolved: false,
      companyId: COMPANY,
      createdAt: daysAgo(1),
    },
    {
      id: "alert-translation-latam-004",
      type: "translation",
      severity: "warning",
      title: "BRL translation risk",
      message: "Brazilian Real weakened 3.2% in July. BRL->USD translation CTA of $124.5K may require hedge adjustment. Closing rate: 0.1835.",
      consolidationRunId: "cons-run-2026-07",
      entityId: "entity-latam",
      isRead: false,
      isResolved: false,
      companyId: COMPANY,
      createdAt: daysAgo(1),
    },
    {
      id: "alert-entity-pending-asia-china-005",
      type: "entity",
      severity: "warning",
      title: "Entities not submitted: Perionyx Asia, Perionyx China",
      message: "Asia and China entities have not completed data submission for run Close monthly 2026-P7. Data is now 1 day overdue.",
      consolidationRunId: "cons-run-2026-07",
      entityId: "entity-asia",
      isRead: false,
      isResolved: false,
      companyId: COMPANY,
      createdAt: daysAgo(1),
    },
    {
      id: "alert-ic-interest-diff-006",
      type: "elimination",
      severity: "info",
      title: "Unmatched IC: interest EU -> Parent",
      message: "Interest on intercompany loan has $1,300 timing difference. entity-eu -> entity-parent: $42.5K vs $41.2K.",
      consolidationRunId: "cons-run-2026-07",
      entityId: "entity-eu",
      isRead: false,
      isResolved: false,
      companyId: COMPANY,
      createdAt: daysAgo(1),
    },
  ];
  for (const al of alerts) svc.alerts.add(al);

  // =========================================================================
  // 13. Recommendations
  // =========================================================================
  const recommendations: ConsolidationRecommendation[] = [
    {
      id: "rec-elim-mat-latam-001",
      type: "elimination",
      title: "Match and eliminate EU-LATAM IC receivables/payables",
      description: "EU and LATAM have reciprocal unmatched IC entries of $35K each way. Current difference $35K due to FX rate variance at recognition. Recommend FX revaluation and matching.",
      priority: "high",
      status: "active",
      impact: "Unmatched amount: $35,000 USD. May grow if FX rates diverge further.",
      effort: "medium",
      consolidationRunId: "cons-run-2026-07",
      entityId: "entity-eu",
      companyId: COMPANY,
      createdAt: daysAgo(1),
    },
    {
      id: "rec-trans-review-brl-002",
      type: "translation",
      title: "Review BRL translation and hedge effectiveness",
      description: "BRL weakened 3.2% in July with CTA of $124.5K. Average rate 0.1800, closing 0.1835. Spread of 0.0035 indicates volatility. Review hedge positions and consider increasing hedge coverage from current 40% to 60%.",
      priority: "high",
      status: "active",
      impact: "Unhedged BRL exposure approximately $8.5M. Every 1% BRL movement = $85K P&L impact.",
      effort: "medium",
      consolidationRunId: "cons-run-2026-07",
      companyId: COMPANY,
      createdAt: daysAgo(1),
    },
    {
      id: "rec-own-cleanup-china-003",
      type: "ownership",
      title: "Document indirect ownership chain for China subsidiary",
      description: "China entity is owned 70% by Asia (direct) and effectively 59.5% by Parent (indirect via 85% of Asia). Ensure consolidation scope is correctly documented and minority interest of 30% is properly attributed.",
      priority: "medium",
      status: "active",
      impact: "Minority interest of $3.56M at risk if ownership attribution is incorrect.",
      effort: "low",
      consolidationRunId: "cons-run-2026-07",
      entityId: "entity-china",
      companyId: COMPANY,
      createdAt: daysAgo(1),
    },
    {
      id: "rec-cons-impairment-asia-004",
      type: "consolidation",
      title: "Complete goodwill impairment assessment for Asia subsidiary",
      description: "Goodwill impairment adjustment of $450K has been approved but not yet posted. Asia's fair value indicators suggest potential further impairment. Complete assessment before month-end close.",
      priority: "critical",
      status: "active",
      impact: "Current goodwill on Asia books: $3.2M. Proposed impairment: $450K (14% reduction). Further testing may identify additional $200K at risk.",
      effort: "high",
      consolidationRunId: "cons-run-2026-07",
      entityId: "entity-asia",
      companyId: COMPANY,
      createdAt: daysAgo(1),
    },
  ];
  for (const r of recommendations) svc.recommendations.add(r);

  // =========================================================================
  // 14. KPIs
  // =========================================================================
  const kpis: ConsolidationKPI[] = [
    {
      id: "kpi-close-speed-001",
      name: "Close Duration",
      value: 5,
      target: 7,
      unit: "days",
      trend: "improving",
      category: "speed",
      status: "exceeding",
      companyId: COMPANY,
    },
    {
      id: "kpi-data-completeness-002",
      name: "Entity Submission Rate",
      value: 71.4,
      target: 90,
      unit: "%",
      trend: "improving",
      category: "quality",
      status: "atRisk",
      companyId: COMPANY,
    },
    {
      id: "kpi-ic-match-rate-003",
      name: "IC Matching Rate",
      value: 35.7,
      target: 85,
      unit: "%",
      trend: "improving",
      category: "quality",
      status: "critical",
      companyId: COMPANY,
    },
    {
      id: "kpi-translation-progress-004",
      name: "Translation Completion",
      value: 66.7,
      target: 100,
      unit: "%",
      trend: "improving",
      category: "efficiency",
      status: "atRisk",
      companyId: COMPANY,
    },
    {
      id: "kpi-adjustment-resolution-005",
      name: "Adjustment Resolution Rate",
      value: 25,
      target: 80,
      unit: "%",
      trend: "worsening",
      category: "compliance",
      status: "critical",
      companyId: COMPANY,
    },
    {
      id: "kpi-audit-trail-006",
      name: "Audit Trail Coverage",
      value: 96,
      target: 100,
      unit: "%",
      trend: "stable",
      category: "compliance",
      status: "onTrack",
      companyId: COMPANY,
    },
  ];
  for (const kpi of kpis) svc.analytics.addMetric(kpi);
}
