import type {
  HealthMetric,
  AttentionItem,
  QueueCardData,
  ServiceCardData,
  ActivityEvent,
  QuickAction,
} from "./types";

export const healthMetrics: HealthMetric[] = [
  {
    id: "active-workflows",
    title: "Active Workflows",
    value: "24",
    trend: "up",
    trendLabel: "+12% today",
    color: "emerald",
    sparklineData: [12, 18, 14, 22, 20, 24],
    href: "/approvals",
  },
  {
    id: "pending-approvals",
    title: "Pending Approvals",
    value: "8",
    trend: "down",
    trendLabel: "-3 from yesterday",
    color: "amber",
    sparklineData: [14, 12, 10, 9, 8, 8],
    href: "/approvals",
  },
  {
    id: "failed-transactions",
    title: "Failed Transactions",
    value: "2",
    trend: "neutral",
    trendLabel: "Same as yesterday",
    color: "red",
    sparklineData: [3, 5, 1, 4, 2, 2],
    href: "/transactions?status=FAILED",
  },
  {
    id: "reconciliation-issues",
    title: "Reconciliation Issues",
    value: "5",
    trend: "up",
    trendLabel: "+2 new today",
    color: "red",
    sparklineData: [8, 6, 4, 3, 5, 5],
    href: "/reconciliation/exceptions",
  },
  {
    id: "high-risk-payments",
    title: "High Risk Payments",
    value: "3",
    trend: "down",
    trendLabel: "-1 since yesterday",
    color: "amber",
    sparklineData: [6, 5, 4, 4, 3, 3],
    href: "/risk/alerts",
  },
  {
    id: "system-health",
    title: "Overall System Health",
    value: "98.7%",
    trend: "up",
    trendLabel: "All systems nominal",
    color: "emerald",
    sparklineData: [99, 98, 99, 98, 99, 99],
    href: "#",
  },
];

export const attentionItems: AttentionItem[] = [
  {
    id: "attention-1",
    severity: "critical",
    category: "Approval",
    title: "CFO Approval Overdue",
    description: "Transaction #TXN-8821 awaiting CFO approval for 18+ hours. Escalation triggered.",
    owner: "CFO Office",
    age: "18h 32m",
    status: "Escalated",
    actionLabel: "Review",
    actionHref: "/approvals",
  },
  {
    id: "attention-2",
    severity: "critical",
    category: "Treasury",
    title: "Treasury Settlement Delayed",
    description: "Wire transfer batch #BATCH-441 stuck in PROCESSING for 45 minutes. Manual intervention may be required.",
    owner: "Treasury Ops",
    age: "45m",
    status: "Processing",
    actionLabel: "Investigate",
    actionHref: "/transactions",
  },
  {
    id: "attention-3",
    severity: "high",
    category: "Policy",
    title: "Policy Exception — Amount Threshold",
    description: "Transaction #TXN-8834 exceeds single-approval limit ($250k). Dual approval required but only one obtained.",
    owner: "Compliance",
    age: "4h 12m",
    status: "Pending Review",
    actionLabel: "View Policy",
    actionHref: "/policies",
  },
  {
    id: "attention-4",
    severity: "high",
    category: "Ledger",
    title: "Ledger Posting Failed",
    description: "Journal entry #JE-773 failed to post due to currency mismatch between debit and credit legs.",
    owner: "Engineering",
    age: "2h 05m",
    status: "Investigating",
    actionLabel: "View Ledger",
    actionHref: "/ledger",
  },
  {
    id: "attention-5",
    severity: "high",
    category: "Reconciliation",
    title: "Reconciliation Failure — Q1 Batch",
    description: "Bank statement reconciliation for Q1 batch #REC-2024-Q1 failed with 14 unmatched transactions.",
    owner: "Finance Ops",
    age: "6h 40m",
    status: "Failed",
    actionLabel: "Review",
    actionHref: "/reconciliation/reports",
  },
  {
    id: "attention-6",
    severity: "medium",
    category: "Webhooks",
    title: "Webhook Delivery Retrying",
    description: "Webhook endpoint https://internal.corp/webhooks/payments has been retrying for 22 minutes. 3 deliveries failed.",
    owner: "Integrations",
    age: "22m",
    status: "Retrying",
    actionLabel: "View Webhooks",
    actionHref: "/admin/webhooks",
  },
  {
    id: "attention-7",
    severity: "medium",
    category: "Connectors",
    title: "Bank Connection Warning",
    description: "Silvergate Bank connection reporting degraded latency (2.4s response time). 4 retries in last hour.",
    owner: "Treasury Ops",
    age: "1h 15m",
    status: "Degraded",
    actionLabel: "Inspect",
    actionHref: "/connectors",
  },
  {
    id: "attention-8",
    severity: "low",
    category: "Notifications",
    title: "Notification Queue Backlog",
    description: "97 unsent notifications in delivery queue. No delivery failures detected — processing at normal rate.",
    owner: "System",
    age: "12m",
    status: "Monitoring",
    actionLabel: "View Queue",
    actionHref: "/admin/queue",
  },
];

export const queueCards: QueueCardData[] = [
  {
    id: "queue-pending-approvals",
    title: "Pending Approvals",
    count: 8,
    trend: "down",
    trendLabel: "Improving",
    avgWait: "4h 22m",
    largestItem: "$250k — CFO approval",
    href: "/approvals",
  },
  {
    id: "queue-high-risk",
    title: "High Risk Reviews",
    count: 3,
    trend: "down",
    trendLabel: "-1 since yesterday",
    avgWait: "2h 15m",
    largestItem: "$1.2M — Wire transfer",
    href: "/risk/alerts",
  },
  {
    id: "queue-failed-txns",
    title: "Failed Transactions",
    count: 2,
    trend: "neutral",
    trendLabel: "Same as yesterday",
    avgWait: "3h 40m",
    largestItem: "JE-773 — Currency mismatch",
    href: "/transactions",
  },
  {
    id: "queue-reconciliation",
    title: "Reconciliation Queue",
    count: 5,
    trend: "up",
    trendLabel: "+2 new exceptions",
    avgWait: "8h 10m",
    largestItem: "Q1 batch — 14 unmatched",
    href: "/reconciliation/exceptions",
  },
  {
    id: "queue-policy-exceptions",
    title: "Policy Exceptions",
    count: 4,
    trend: "neutral",
    trendLabel: "Stable",
    avgWait: "6h 30m",
    largestItem: "Dual approval rule violation",
    href: "/policies",
  },
];

export const serviceCards: ServiceCardData[] = [
  {
    id: "svc-approval-engine",
    name: "Approval Engine",
    status: "healthy",
    description: "Processing all approval workflows within SLA",
    lastChecked: "30s ago",
    latency: "120ms",
  },
  {
    id: "svc-policy-engine",
    name: "Policy Engine",
    status: "healthy",
    description: "All policy rules evaluating normally",
    lastChecked: "30s ago",
    latency: "45ms",
  },
  {
    id: "svc-ledger-engine",
    name: "Ledger Engine",
    status: "warning",
    description: "1 recent posting failure, all others normal",
    lastChecked: "30s ago",
    latency: "180ms",
  },
  {
    id: "svc-treasury-engine",
    name: "Treasury Engine",
    status: "warning",
    description: "Settlement batch delayed — manual review flagged",
    lastChecked: "30s ago",
    latency: "230ms",
  },
  {
    id: "svc-notifications",
    name: "Notification Delivery",
    status: "healthy",
    description: "All notification channels operational",
    lastChecked: "15s ago",
    latency: "60ms",
  },
  {
    id: "svc-audit",
    name: "Audit Logging",
    status: "healthy",
    description: "All events being recorded in real-time",
    lastChecked: "15s ago",
    latency: "35ms",
  },
  {
    id: "svc-api",
    name: "API Services",
    status: "healthy",
    description: "API gateway healthy, all rate limits nominal",
    lastChecked: "10s ago",
    latency: "85ms",
  },
  {
    id: "svc-auth",
    name: "Authentication",
    status: "healthy",
    description: "Auth service operational, no failed logins detected",
    lastChecked: "10s ago",
    latency: "55ms",
  },
];

export const recentActivity: ActivityEvent[] = [
  {
    id: "act-1",
    type: "approved",
    label: "Approval Completed",
    description: "Transaction TXN-8819 approved by CFO — $50,000 wire transfer",
    timestamp: new Date(Date.now() - 2 * 60000).toISOString(),
    href: "/transactions/TXN-8819",
  },
  {
    id: "act-2",
    type: "policy",
    label: "Policy Triggered",
    description: "Rule 'High-Value Wire' triggered for TXN-8834 — $250,000 requires dual approval",
    timestamp: new Date(Date.now() - 8 * 60000).toISOString(),
    href: "/policies",
  },
  {
    id: "act-3",
    type: "posted",
    label: "Ledger Posted",
    description: "Journal entry JE-771 posted — 12 ledger lines, all balanced",
    timestamp: new Date(Date.now() - 15 * 60000).toISOString(),
    href: "/ledger",
  },
  {
    id: "act-4",
    type: "treasury",
    label: "Treasury Executed",
    description: "Wire batch BATCH-440 executed — 8 transfers totaling $320,000",
    timestamp: new Date(Date.now() - 30 * 60000).toISOString(),
    href: "/transactions",
  },
  {
    id: "act-5",
    type: "audit",
    label: "Audit Event Recorded",
    description: "User 'john.smith@corp.com' exported transaction report",
    timestamp: new Date(Date.now() - 45 * 60000).toISOString(),
    href: "/audit-logs",
  },
  {
    id: "act-6",
    type: "risk",
    label: "Risk Review Completed",
    description: "Alert ALERT-442 resolved — flagged transaction reviewed and cleared",
    timestamp: new Date(Date.now() - 60 * 60000).toISOString(),
    href: "/risk/alerts",
  },
  {
    id: "act-7",
    type: "exception",
    label: "Reconciliation Exception",
    description: "New exception detected in batch REC-2024-Q1 — 2 transactions unmatched",
    timestamp: new Date(Date.now() - 90 * 60000).toISOString(),
    href: "/reconciliation/exceptions",
  },
];

export const quickActions: QuickAction[] = [
  {
    id: "qa-create-payment",
    label: "Create Payment",
    description: "Initiate a new wire or ACH transfer",
    icon: "send",
    href: "/transactions",
    variant: "primary",
  },
  {
    id: "qa-review-approvals",
    label: "Review Approvals",
    description: "Approve or reject pending transactions",
    icon: "check-square",
    href: "/approvals",
  },
  {
    id: "qa-view-treasury",
    label: "View Treasury",
    description: "Monitor liquidity and settlement status",
    icon: "landmark",
    href: "/treasury",
  },
  {
    id: "qa-investigate-risk",
    label: "Investigate Risk",
    description: "Review alerts and incident reports",
    icon: "alert-triangle",
    href: "/risk",
  },
  {
    id: "qa-run-reconciliation",
    label: "Run Reconciliation",
    description: "Match ledger entries with bank statements",
    icon: "refresh-cw",
    href: "/reconciliation",
  },
  {
    id: "qa-open-audit",
    label: "Open Audit Logs",
    description: "Inspect the immutable event trail",
    icon: "scroll-text",
    href: "/audit-logs",
  },
  {
    id: "qa-manage-policies",
    label: "Manage Policies",
    description: "Configure approval rules and controls",
    icon: "file-check",
    href: "/policies",
  },
];
