export type IntelligenceCategory =
  | "liquidity"
  | "treasury"
  | "risk"
  | "operational"
  | "executive"
  | "compliance"
  | "process";

export type InsightSeverity = "critical" | "high" | "medium" | "low" | "info";

export type InsightDirection = "up" | "down" | "stable" | "volatile";

export interface Insight {
  id: string;
  category: IntelligenceCategory;
  title: string;
  description: string;
  severity: InsightSeverity;
  confidence: number;
  direction?: InsightDirection;
  sourceData: string[];
  timestamp: string;
  affectedEntities?: string[];
  affectedAccounts?: string[];
  metadata?: Record<string, unknown>;
  explainability: ExplainabilityInfo;
  sourceService: string;
}

export interface Recommendation {
  id: string;
  title: string;
  description: string;
  severity: InsightSeverity;
  confidence: number;
  category: IntelligenceCategory;
  affectedEntities: string[];
  affectedAccounts: string[];
  supportingEvidence: string[];
  suggestedActions: string[];
  relatedInsightIds: string[];
  relatedEventIds: string[];
  timestamp: string;
  acknowledgedAt?: string;
  resolvedAt?: string;
  resolution?: string;
  explainability: ExplainabilityInfo;
  sourceService: string;
}

export function makeInsight(base: Omit<Insight, "explainability" | "sourceService"> & { explainability?: Partial<ExplainabilityInfo>; sourceService?: string }): Insight {
  return {
    ...base,
    explainability: {
      why: base.explainability?.why ?? `Insight generated by analysis of ${base.sourceData.join(", ")}`,
      evidence: base.explainability?.evidence ?? base.sourceData,
      confidenceCalculation: base.explainability?.confidenceCalculation ?? `Based on ${base.confidence}% confidence from data analysis`,
      whatToDo: base.explainability?.whatToDo ?? "Review the insight details and take appropriate action",
      dataFreshness: base.timestamp,
      relatedSources: base.explainability?.relatedSources ?? base.sourceData,
    },
    sourceService: base.sourceService ?? "enterprise-intelligence",
  };
}

export function makeRecommendation(base: Omit<Recommendation, "explainability" | "sourceService"> & { explainability?: Partial<ExplainabilityInfo>; sourceService?: string }): Recommendation {
  return {
    ...base,
    explainability: {
      why: base.explainability?.why ?? `Recommendation based on ${base.supportingEvidence.length} pieces of evidence`,
      evidence: base.explainability?.evidence ?? base.supportingEvidence,
      confidenceCalculation: base.explainability?.confidenceCalculation ?? `Confidence: ${base.confidence}%`,
      whatToDo: base.explainability?.whatToDo ?? base.suggestedActions[0] ?? "Review and take action",
      dataFreshness: base.timestamp,
      relatedSources: base.explainability?.relatedSources ?? [],
    },
    sourceService: base.sourceService ?? "enterprise-intelligence",
  };
}

export interface ExplainabilityInfo {
  why: string;
  evidence: string[];
  confidenceCalculation: string;
  whatToDo: string;
  dataFreshness: string;
  relatedSources: string[];
}

export interface ExecutiveSummary {
  id: string;
  type: "daily" | "weekly" | "monthly" | "quarterly";
  title: string;
  period: { start: string; end: string };
  generatedAt: string;
  sections: ExecutiveSummarySection[];
  topRecommendations: Recommendation[];
  metrics: SummaryMetric[];
  strategicHighlights: StrategicHighlight[];
}

export interface ExecutiveSummarySection {
  title: string;
  summary: string;
  details: string;
  insights: Insight[];
  recommendations: Recommendation[];
  confidence: "high" | "medium" | "low";
}

export interface SummaryMetric {
  label: string;
  value: string;
  previousValue?: string;
  change?: string;
  direction?: InsightDirection;
  insight?: string;
}

export interface StrategicHighlight {
  id: string;
  label: string;
  description: string;
  impact: "positive" | "negative" | "neutral";
  change: string;
}

export interface IntelligenceEngineResult {
  insights: Insight[];
  recommendations: Recommendation[];
  evaluatedAt: string;
  durationMs: number;
}

export interface KnowledgeDocument {
  id: string;
  moduleName: string;
  recordCount: number;
  summary: string;
  details: string;
  sourceService: string;
}

export interface ContextDocument {
  id: string;
  type: string;
  label: string;
  content: string;
  priority: number;
  sourceService: string;
}

export function formatCurrency(amount: number): string {
  if (amount >= 1_000_000_000) return `$${(amount / 1_000_000_000).toFixed(2)}B`;
  if (amount >= 1_000_000) return `$${(amount / 1_000_000).toFixed(2)}M`;
  if (amount >= 1_000) return `$${(amount / 1_000).toFixed(2)}K`;
  return `$${amount.toFixed(2)}`;
}
