export { ConnectorPlatformRegistry, connectorPlatformRegistry } from "./registry";
export { ConnectorLifecycle } from "./lifecycle";
export { LegacyConnectorAdapter } from "./adapters/legacy";
export { SlackConnector } from "./adapters/slack-connector";
export { TeamsConnector } from "./adapters/teams-connector";
export { PlaidConnector } from "./adapters/plaid-adapter";
export { QuickBooksConnector } from "./adapters/quickbooks-connector";
export { PlaidBankingService } from "./services/plaid-banking.service";
export { QuickBooksAccountingService } from "./services/quickbooks-accounting.service";
export { connectorEventBus } from "./event-hooks";
export type { ConnectorEventPayload } from "./event-hooks";
export { connectorMetadataRegistry } from "./metadata";
export type { ConnectorMetadata, ConnectorKindSummary } from "./metadata";
export { resolveConnectorSecrets, storeConnectorSecret, getConnectorSecretSchema } from "./secrets";
export type { SecretReference, ConnectorSecretSchema } from "./secrets";
export { ConnectorDiscovery, connectorDiscovery } from "./discovery";
export type { DiscoveryQuery } from "./discovery";
export { ConnectorOrchestrator, connectorOrchestrator } from "./orchestrator";
export type { OrchestrationConfig } from "./orchestrator";
export { enableConnectorWebhookBridge, disableConnectorWebhookBridge } from "./webhook-bridge";
export type { IConnector, ConnectorAuthConfig, ConnectorSyncOptions } from "./interface";
export * from "./types";
export * from "./config";
